import { and, eq, gt, isNull } from "drizzle-orm";
import { generateAuthenticationOptions, generateRegistrationOptions, verifyAuthenticationResponse, verifyRegistrationResponse } from "@simplewebauthn/server";
import type { AuthenticationResponseJSON, RegistrationResponseJSON } from "@simplewebauthn/server";
import { webauthnChallenges, webauthnCredentials } from "@/db/schema";
import { db } from "@/lib/db";
import { activePasskeys } from "@/lib/auth/accessSecurityRuntime";
import { recordSecurityEvent } from "@/security/securityRuntimeGuards";

const RP_NAME="Ares Farms Furlong";
function rp(req: Request){ const u=new URL(req.url); return { rpID: process.env.WEBAUTHN_RP_ID?.trim()||u.hostname, origin: process.env.WEBAUTHN_ORIGIN?.trim()||u.origin }; }
async function saveChallenge(userId:string,challenge:string,purpose:string){ const challengeId=crypto.randomUUID(); await db.insert(webauthnChallenges).values({challengeId,userId,challenge,purpose,expiresAt:new Date(Date.now()+5*60_000)}); return challengeId; }
async function consume(userId:string,challengeId:string,purpose:string){ const rows=await db.select().from(webauthnChallenges).where(and(eq(webauthnChallenges.challengeId,challengeId),eq(webauthnChallenges.userId,userId),eq(webauthnChallenges.purpose,purpose),isNull(webauthnChallenges.consumedAt),gt(webauthnChallenges.expiresAt,new Date()))).limit(1); const row=rows[0]; if(!row)throw new Error("MFA challenge is invalid or expired."); await db.update(webauthnChallenges).set({consumedAt:new Date()}).where(eq(webauthnChallenges.id,row.id)); return row.challenge; }
export async function registrationOptions(req:Request,user:{id:string;email:string;name?:string|null}){ const {rpID}=rp(req); const creds=await activePasskeys(user.id); const options=await generateRegistrationOptions({rpName:RP_NAME,rpID,userName:user.email,userDisplayName:user.name||user.email,userID:new TextEncoder().encode(user.id),attestationType:"none",excludeCredentials:creds.map(c=>({id:c.credentialId as never,transports:(Array.isArray(c.transports)?c.transports:[]) as never})),authenticatorSelection:{residentKey:"preferred",userVerification:"required"}}); return {options,challengeId:await saveChallenge(user.id,options.challenge,"REGISTER")}; }
export async function verifyRegistration(req:Request,userId:string,challengeId:string,response:RegistrationResponseJSON,label?:string){ const expectedChallenge=await consume(userId,challengeId,"REGISTER"); const {rpID,origin}=rp(req); const result=await verifyRegistrationResponse({response,expectedChallenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true}); if(!result.verified||!result.registrationInfo?.userVerified)throw new Error("Passkey registration was not user-verified."); const c=result.registrationInfo.credential; await db.insert(webauthnCredentials).values({userId,credentialId:c.id,publicKeyB64:Buffer.from(c.publicKey).toString("base64"),counter:c.counter,transports:(c.transports??[]) as never,deviceType:result.registrationInfo.credentialDeviceType,backedUp:String(result.registrationInfo.credentialBackedUp),label:label?.slice(0,80)||"Passkey"}); recordSecurityEvent({type:"MFA_PASSKEY_ENROLLED",severity:"high",summary:"Phishing-resistant passkey enrolled",detail:{userId,credentialId:c.id,deviceType:result.registrationInfo.credentialDeviceType}}); return true; }
export async function authenticationOptions(req:Request,userId:string){ const {rpID}=rp(req); const creds=await activePasskeys(userId); if(!creds.length)throw new Error("No active passkey is enrolled."); const options=await generateAuthenticationOptions({rpID,userVerification:"required",allowCredentials:creds.map(c=>({id:c.credentialId as never,transports:(Array.isArray(c.transports)?c.transports:[]) as never}))}); return {options,challengeId:await saveChallenge(userId,options.challenge,"AUTHENTICATE")}; }
export async function verifyAuthentication(req:Request,userId:string,challengeId:string,response:AuthenticationResponseJSON){ const expectedChallenge=await consume(userId,challengeId,"AUTHENTICATE"); const rows=await db.select().from(webauthnCredentials).where(and(eq(webauthnCredentials.userId,userId),eq(webauthnCredentials.credentialId,response.id),isNull(webauthnCredentials.revokedAt))).limit(1); const stored=rows[0]; if(!stored)throw new Error("Passkey is not active for this user."); const {rpID,origin}=rp(req); const result=await verifyAuthenticationResponse({response,expectedChallenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true,credential:{id:stored.credentialId as never,publicKey:new Uint8Array(Buffer.from(stored.publicKeyB64,"base64")),counter:stored.counter,transports:(Array.isArray(stored.transports)?stored.transports:[]) as never}}); if(!result.verified||!result.authenticationInfo.userVerified)throw new Error("Passkey authentication failed user verification."); await db.update(webauthnCredentials).set({counter:result.authenticationInfo.newCounter,lastUsedAt:new Date(),updatedAt:new Date()}).where(eq(webauthnCredentials.id,stored.id)); recordSecurityEvent({type:"MFA_PASSKEY_VERIFIED",severity:"info",summary:"Fresh passkey MFA verified",detail:{userId,credentialId:stored.credentialId}}); return true; }
