import {
  boolean,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Borrower Financial Control Chain
 *
 * Implements the evidence links required before borrower-facing professional
 * service charges can become recognized platform revenue. These tables do not
 * authorize live payment capture by themselves.
 */
export const engagementScopeAcceptances = pgTable("engagement_scope_acceptances", {
  id: uuid("id").defaultRandom().primaryKey(),
  scopeAcceptanceId: text("scope_acceptance_id").notNull().unique(),
  borrowerId: text("borrower_id"),
  customerSubjectRef: text("customer_subject_ref"),
  tenantId: text("tenant_id").notNull(),
  moduleId: text("module_id").notNull(),
  serviceCode: text("service_code").notNull(),
  scopeVersion: text("scope_version").notNull(),
  scopeSummary: text("scope_summary").notNull(),
  scopeHash: text("scope_hash").notNull(),
  quotedAmount: numeric("quoted_amount", { precision: 20, scale: 2 }),
  quotedRate: numeric("quoted_rate", { precision: 20, scale: 2 }),
  currency: text("currency").notNull().default("USD"),
  acceptedBy: text("accepted_by").notNull(),
  acceptanceMethod: text("acceptance_method").notNull(),
  feeControlId: text("fee_control_id"),
  status: text("status").notNull().default("accepted"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("CONFIDENTIAL"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const serviceDeliveryEvidenceRecords = pgTable("service_delivery_evidence_records", {
  id: uuid("id").defaultRandom().primaryKey(),
  evidenceId: text("evidence_id").notNull().unique(),
  scopeAcceptanceId: text("scope_acceptance_id").notNull(),
  feeControlId: text("fee_control_id").notNull(),
  moduleId: text("module_id").notNull(),
  serviceCode: text("service_code").notNull(),
  workType: text("work_type").notNull(),
  actualWorkSummary: text("actual_work_summary").notNull(),
  performedBy: text("performed_by").notNull(),
  evidenceRefs: jsonb("evidence_refs").notNull(),
  billableUnits: numeric("billable_units", { precision: 20, scale: 4 }),
  amountEligible: numeric("amount_eligible", { precision: 20, scale: 2 }),
  currency: text("currency").notNull().default("USD"),
  verified: boolean("verified").notNull().default(false),
  verifiedBy: text("verified_by"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("CONFIDENTIAL"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  workStartedAt: timestamp("work_started_at", { withTimezone: true }),
  workCompletedAt: timestamp("work_completed_at", { withTimezone: true }),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const governedPaymentRecords = pgTable("governed_payment_records", {
  id: uuid("id").defaultRandom().primaryKey(),
  paymentRecordId: text("payment_record_id").notNull().unique(),
  provider: text("provider").notNull(),
  providerPaymentRef: text("provider_payment_ref").notNull(),
  billingEventId: text("billing_event_id"),
  scopeAcceptanceId: text("scope_acceptance_id"),
  feeControlId: text("fee_control_id"),
  actualWorkEvidenceId: text("actual_work_evidence_id"),
  moduleAttribution: text("module_attribution").notNull(),
  amount: numeric("amount", { precision: 20, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USD"),
  paymentPurpose: text("payment_purpose").notNull(),
  status: text("status").notNull(),
  liveCapture: boolean("live_capture").notNull().default(false),
  treasuryLedgerRef: text("treasury_ledger_ref"),
  revenueEventRef: text("revenue_event_ref"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("CONFIDENTIAL"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  authorizedAt: timestamp("authorized_at", { withTimezone: true }),
  capturedAt: timestamp("captured_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const moduleRevenueAttributionRecords = pgTable("module_revenue_attribution_records", {
  id: uuid("id").defaultRandom().primaryKey(),
  attributionId: text("attribution_id").notNull().unique(),
  paymentRecordId: text("payment_record_id").notNull(),
  revenueEventId: text("revenue_event_id"),
  moduleId: text("module_id").notNull(),
  serviceCode: text("service_code").notNull(),
  providerEntity: text("provider_entity").notNull(),
  grossAmount: numeric("gross_amount", { precision: 20, scale: 2 }).notNull(),
  refundAmount: numeric("refund_amount", { precision: 20, scale: 2 }).notNull().default("0"),
  netAmount: numeric("net_amount", { precision: 20, scale: 2 }).notNull(),
  contributorShare: numeric("contributor_share", { precision: 20, scale: 2 }).notNull().default("0"),
  platformOverhead: numeric("platform_overhead", { precision: 20, scale: 2 }).notNull().default("0"),
  currency: text("currency").notNull().default("USD"),
  restrictions: jsonb("restrictions"),
  taxPosture: text("tax_posture"),
  relatedParty: boolean("related_party").notNull().default(false),
  relatedPartyReviewRef: text("related_party_review_ref"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("RESTRICTED"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const governedRefundRecords = pgTable("governed_refund_records", {
  id: uuid("id").defaultRandom().primaryKey(),
  refundRecordId: text("refund_record_id").notNull().unique(),
  paymentRecordId: text("payment_record_id").notNull(),
  providerRefundRef: text("provider_refund_ref"),
  amount: numeric("amount", { precision: 20, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USD"),
  reason: text("reason").notNull(),
  status: text("status").notNull(),
  treasuryLedgerRef: text("treasury_ledger_ref"),
  approvalId: text("approval_id"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("CONFIDENTIAL"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const treasuryReconciliationRecords = pgTable("treasury_reconciliation_records", {
  id: uuid("id").defaultRandom().primaryKey(),
  reconciliationId: text("reconciliation_id").notNull().unique(),
  periodStart: timestamp("period_start", { withTimezone: true }).notNull(),
  periodEnd: timestamp("period_end", { withTimezone: true }).notNull(),
  internalLedgerTotal: numeric("internal_ledger_total", { precision: 20, scale: 2 }).notNull(),
  providerSettlementTotal: numeric("provider_settlement_total", { precision: 20, scale: 2 }).notNull(),
  custodyStatementTotal: numeric("custody_statement_total", { precision: 20, scale: 2 }).notNull(),
  accountingSystemTotal: numeric("accounting_system_total", { precision: 20, scale: 2 }).notNull(),
  recognizedRevenueTotal: numeric("recognized_revenue_total", { precision: 20, scale: 2 }).notNull(),
  refundTotal: numeric("refund_total", { precision: 20, scale: 2 }).notNull().default("0"),
  variance: numeric("variance", { precision: 20, scale: 2 }).notNull(),
  varianceDisposition: text("variance_disposition"),
  sourceRefs: jsonb("source_refs").notNull(),
  reconcilerActor: text("reconciler_actor").notNull(),
  attestationActor: text("attestation_actor").notNull(),
  separationOfDutiesConfirmed: boolean("separation_of_duties_confirmed").notNull().default(false),
  distributionAllowed: boolean("distribution_allowed").notNull().default(false),
  approvalId: text("approval_id"),
  status: text("status").notNull().default("pending"),
  exceptionRef: text("exception_ref"),
  governanceVersion: text("governance_version").notNull(),
  classification: text("classification").notNull().default("RESTRICTED"),
  replayRef: text("replay_ref"),
  traceId: text("trace_id"),
  source: text("source"),
  metadata: jsonb("metadata"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export type EngagementScopeAcceptanceRow = typeof engagementScopeAcceptances.$inferSelect;
export type ServiceDeliveryEvidenceRow = typeof serviceDeliveryEvidenceRecords.$inferSelect;
export type GovernedPaymentRecordRow = typeof governedPaymentRecords.$inferSelect;
export type ModuleRevenueAttributionRecordRow = typeof moduleRevenueAttributionRecords.$inferSelect;
export type GovernedRefundRecordRow = typeof governedRefundRecords.$inferSelect;
export type TreasuryReconciliationRecordRow = typeof treasuryReconciliationRecords.$inferSelect;
