import { createHash, createHmac } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { consolidatedLaunchAuthorization as authorization, launchAuthorizationDecisions as decisions, launchAuthorizationRequirements as requirements, CONSOLIDATED_LAUNCH_LEDGER_VERSION as ledgerVersion } from "@/lib/governance/consolidatedLaunchAuthorizationLedger";
const PROJECT=process.env.GCP_PROJECT??"furlong-staging-499102"; const REVISION=process.env.LAUNCH_LEDGER_REVISION??"furlong-core-00103-lgb";
function sh(cmd:string,args:string[]):string{return execFileSync(cmd,args,{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();} function gcloud(args:string[]):string{return sh("gcloud",[...args,"--project",PROJECT]);}
function main():void{
 const checks:Array<{name:string;pass:boolean;evidence:string}>=[]; const add=(name:string,pass:boolean,evidence:string)=>checks.push({name,pass,evidence});
 const liveRevision=gcloud(["run","services","describe","furlong-core","--region","us-central1","--format","value(status.latestReadyRevisionName)"]); const liveImage=gcloud(["run","services","describe","furlong-core","--region","us-central1","--format","value(spec.template.spec.containers[0].image)"]);
 add("target revision is live",liveRevision===REVISION,`${liveRevision} expected ${REVISION}`); add("live image is digest pinned",liveImage.includes("@sha256:"),liveImage); add("all P5 blockers represented",requirements.length===10,`${requirements.length} blockers`); add("all authority roles have decision slots",decisions.length===requirements.reduce((n,x)=>n+x.authorityRoles.length,0),`${decisions.length} decisions`); add("all human decisions remain pending",decisions.every(x=>x.decision==="PENDING"&&!x.decidedBy),"no automated approvals"); add("proxy approval forbidden",authorization.proxyApprovalForbidden,"true"); add("separation of duties required",authorization.separationOfDutiesRequired,"true");
 const dir=path.join(process.cwd(),"artifacts","deployments","staging"); const files=existsSync(dir)?readdirSync(dir):[]; const evidence=requirements.map(r=>({blockerId:r.blockerId,pattern:r.evidencePattern,matchingFiles:files.filter(f=>f.includes(r.evidencePattern)&&f.endsWith(".json")&&!f.includes("signature"))}));
 add("signed technical evidence catalogued",evidence.filter(x=>x.blockerId!=="P5-B01").every(x=>x.matchingFiles.length>0),JSON.stringify(evidence)); add("named tester approval remains separate",evidence.find(x=>x.blockerId==="P5-B01")?.matchingFiles.length===0,"runtime attestation required"); add("final launch hold remains intact",!authorization.finalLaunchHoldReleased,"false"); add("production authorization remains false",!authorization.productionAuthorized,"false");
 const failed=checks.filter(x=>!x.pass); const generatedAtUtc=new Date().toISOString(); const report={schemaVersion:"consolidated-launch-authorization-readiness-v1",environment:"staging",targetRevision:REVISION,targetImage:liveImage,ledgerVersion,blockerStatus:failed.length?"OPEN":"EVIDENCE_READY_HUMAN_APPROVAL_REQUIRED",outcome:failed.length?"FAIL":"PASS",requirements,decisions,evidenceCatalog:evidence,authorization,checks,productionAuthorized:false,generatedAtUtc};
 const bytes=JSON.stringify(report,null,2); const secret=gcloud(["secrets","versions","access","latest","--secret","REPORT_SIGNING_SECRET"]); const signatureRecord={algorithm:"HMAC-SHA256",keyId:"gcp-secret-manager://REPORT_SIGNING_SECRET/latest",reportSha256:createHash("sha256").update(bytes).digest("hex"),signature:createHmac("sha256",secret).update(bytes).digest("base64url"),signedAtUtc:generatedAtUtc}; const stamp=generatedAtUtc.replace(/[:.]/g,"-"); mkdirSync(dir,{recursive:true}); const reportPath=path.join(dir,`${stamp}-consolidated-launch-authorization.json`); const signaturePath=path.join(dir,`${stamp}-consolidated-launch-authorization-signature.json`); writeFileSync(reportPath,bytes); writeFileSync(signaturePath,JSON.stringify(signatureRecord,null,2)); console.log(JSON.stringify({outcome:report.outcome,blockerStatus:report.blockerStatus,passed:checks.length-failed.length,total:checks.length,failed:failed.map(x=>x.name),reportPath:path.relative(process.cwd(),reportPath),signaturePath:path.relative(process.cwd(),signaturePath),...signatureRecord},null,2)); if(failed.length)process.exit(1);
}
main();
