import { institutionalRemediationAuthority } from "@/lib/platform/institutionalRemediationAuthority";
import type { InstitutionalOutcomeReconciliation } from "@/lib/platform/institutionalOutcomeReconciliationAuthority";

function assert(c: boolean, m: string): asserts c { if (!c) throw new Error(m); }
const reconciliation = Object.freeze({ reconciliationId: "recon-1", schemaVersion: "institutional-outcome-reconciliation-v1", governanceVersion: "gov-1", receiptId: "receipt-1", claimId: "claim-1", actionType: "WORKFLOW_TRANSITION", state: "EXCEPTION_OPEN", severity: "HIGH", expectedOutcome: Object.freeze({ status: "approved" }), observedOutcome: Object.freeze({ status: "pending" }), mismatchFields: Object.freeze(["status"]), exceptionRef: "exception-1", remediationRefs: Object.freeze([]), reversalReceiptRef: null, humanReviewRefs: Object.freeze(["review-1"]), reconciledAt: "2026-07-22T06:00:00Z", resolvedAt: null, evidenceRefs: Object.freeze(["evidence-1"]), auditRefs: Object.freeze(["audit-1"]), replayRef: "replay-recon-1", versionRefs: Object.freeze(["version-1"]) }) as InstitutionalOutcomeReconciliation;
const policy = institutionalRemediationAuthority.createPolicy({ policyId: "policy-1", governanceVersion: "gov-1", allowedTypes: ["CORRECTIVE_UPDATE", "REVERSAL"], requireOpenException: true, requireHumanApproval: true, requireDualControl: true, requireRollbackPlan: true, requireAffectedPartyNotice: false, compensationAuthorized: false, reversalAuthorized: true, retryAuthorized: false, requiredEvidenceRefs: ["evidence-1"], auditRefs: ["audit-policy"], replayRef: "replay-policy", versionRefs: ["version-policy"] });
const allowed = institutionalRemediationAuthority.evaluate({ reconciliation, policy, remediationType: "REVERSAL", approvalRefs: ["approval-a", "approval-b"], rollbackPlanRef: "rollback-1", evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:10:00Z", auditRefs: ["audit-eval"], replayRef: "replay-eval" });
const review = institutionalRemediationAuthority.evaluate({ reconciliation, policy, remediationType: "CORRECTIVE_UPDATE", approvalRefs: ["approval-a"], rollbackPlanRef: null, evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:10:00Z", auditRefs: ["audit-eval-2"], replayRef: "replay-eval-2" });
const blocked = institutionalRemediationAuthority.evaluate({ reconciliation, policy, remediationType: "COMPENSATION", approvalRefs: ["approval-a", "approval-b"], rollbackPlanRef: "rollback-1", evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:10:00Z", auditRefs: ["audit-eval-3"], replayRef: "replay-eval-3" });
assert(allowed.decision === "ALLOW", "Expected allowed remediation."); assert(review.decision === "REVIEW_REQUIRED", "Expected review-required remediation."); assert(blocked.decision === "BLOCK", "Expected blocked remediation.");
console.log(JSON.stringify({ ok: true, schemaVersion: allowed.schemaVersion, allowed: allowed.decision, review: review.decision, blocked: blocked.decision, message: "Institutional remediation authority conformance passed." }, null, 2));
