import assert from "node:assert/strict";
import type { InstitutionalLifecycleCycleEvaluation } from "@/lib/platform/institutionalLifecycleCycleAuthority";
import { createInstitutionalLifecycleCycleReopeningPolicy, evaluateInstitutionalLifecycleCycleReopening } from "@/lib/platform/institutionalLifecycleCycleReopeningAuthority";
const cycle={schemaVersion:"institutional-lifecycle-cycle-v1",cyclePolicyId:"cycle-policy",cycleId:"cycle-2",parentCycleId:"cycle-1",canonicalObjectId:"case-1",generation:2,sourceProjectionSchemaVersion:"projection-v1",sourceProjectionPolicyId:"projection-policy",decision:"ALLOW",resultingState:"OPEN",reasons:[],approvalRefs:["approval-1"],evidenceRefs:["evidence-cycle"],openedAt:"2026-07-22T19:00:00Z",auditRefs:["audit-cycle"],replayRef:"replay-1"} as InstitutionalLifecycleCycleEvaluation;
const policy=createInstitutionalLifecycleCycleReopeningPolicy({policyId:"reopening-policy",governanceVersion:"gov-1",allowedBases:["NEW_EVIDENCE","FRAUD_INDICATOR"],requireIndependentReview:true,requireMaterialityEvidence:true,requireLegalReview:false,requireFraudEscalation:false,fullReopeningAuthorized:true,requiredEvidenceRefs:["evidence-required"],auditRefs:["audit-policy"],replayRef:"replay-1",versionRefs:["version-1"]});
const base={cycle,policy,basis:"NEW_EVIDENCE" as const,fullReopeningRequested:false,independentReviewRefs:["review-1"],materialityEvidenceRef:"materiality-1",evidenceRefs:["evidence-required"],evaluatedAt:"2026-07-22T20:00:00Z",auditRefs:["audit-eval"],replayRef:"replay-1"};
const allowed=evaluateInstitutionalLifecycleCycleReopening(base);const review=evaluateInstitutionalLifecycleCycleReopening({...base,independentReviewRefs:[]});const full=evaluateInstitutionalLifecycleCycleReopening({...base,fullReopeningRequested:true});const blocked=evaluateInstitutionalLifecycleCycleReopening({...base,replayRef:"replay-2"});
assert.equal(allowed.decision,"ALLOW");assert.equal(allowed.resultingState,"REOPENED_RESTRICTED");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(full.resultingState,"REOPENED_FULL");assert.equal(blocked.decision,"BLOCK");assert.equal(allowed.generation,2);assert.equal(allowed.cycleId,"cycle-2");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,full:full.resultingState,blocked:blocked.decision,generation:allowed.generation,message:"Institutional lifecycle cycle reopening authority conformance passed."},null,2));
