import assert from "node:assert/strict";
import { institutionalAppealRemandArchiveReopeningSuspensionAuthority as authority } from "@/lib/platform/institutionalAppealRemandArchiveReopeningSuspensionAuthority";
import type { InstitutionalAppealRemandArchiveReopeningEvaluation } from "@/lib/platform/institutionalAppealRemandArchiveReopeningAuthority";

const reopening=Object.freeze({schemaVersion:"institutional-appeal-remand-archive-reopening-v1",projectionPolicyId:"projection",reopeningPolicyId:"reopening",canonicalObjectId:"case-1",basis:"NEW_EVIDENCE",decision:"ALLOW",resultingState:"REOPENED_RESTRICTED",reasons:Object.freeze([]),reviewRefs:Object.freeze(["review"]),evidenceRefs:Object.freeze(["evidence-reopen"]),evaluatedAt:"2026-07-22T17:40:00Z",auditRefs:Object.freeze(["audit-reopen"]),replayRef:"replay-1"}) as InstitutionalAppealRemandArchiveReopeningEvaluation;
const policy=authority.createPolicy({policyId:"suspension",governanceVersion:"gov-1",allowedScopes:["PUBLICATION","RELIANCE","FULL_MATTER"],requireReopenedMatter:true,requireRiskEvidence:true,requireHumanApproval:true,requireNotice:true,fullMatterSuspensionAuthorized:true,emergencySuspensionAuthorized:true,requiredEvidenceRefs:["evidence-risk"],auditRefs:["audit-policy"],replayRef:"replay-1",versionRefs:["version-1"]});
const base={reopening,policy,scopes:["PUBLICATION","RELIANCE"] as const,emergency:false,approvalRefs:["approval"],riskEvidenceRef:"risk",noticeRef:"notice",evidenceRefs:["evidence-risk"],evaluatedAt:"2026-07-22T17:45:00Z",auditRefs:["audit-eval"],replayRef:"replay-1"};
const allowed=authority.evaluate(base);const review=authority.evaluate({...base,approvalRefs:[]});const blocked=authority.evaluate({...base,replayRef:"replay-other"});const full=authority.evaluate({...base,scopes:["FULL_MATTER"]});
assert.equal(allowed.decision,"ALLOW");assert.equal(allowed.resultingState,"PARTIALLY_SUSPENDED");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(blocked.decision,"BLOCK");assert.equal(full.resultingState,"SUSPENDED");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,fullState:full.resultingState,message:"Institutional appeal remand archive reopening suspension authority conformance passed."},null,2));
