import fs from "node:fs";import os from "node:os";import path from "node:path";
function ok(v:unknown,m:string):asserts v{if(!v)throw new Error(m)}
async function main(){process.env.FURLONG_RUNTIME_STATE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),"furlong-handler-governance-"));process.env.EVIDENCE_REPLAY_SIGNING_SECRET="handler-governance-test";
 const registry=await import("@/lib/property/officialEvidenceRecomputationHandlerRegistry");const production=await import("@/lib/property/officialEvidenceProductionRecomputationHandlers");const packets=await import("@/lib/property/officialEvidenceReplayPacketStore");const replay=await import("@/lib/property/officialEvidenceReplayExecutor");const tax=await import("@/lib/property/ownershipCostModel");
 registry.clearGovernedRecomputationHandlers();production.registerProductionRecomputationBindings("2026-07-25T17:00:00Z");let registrations=registry.listGovernedRecomputationHandlers();ok(registrations.length===4&&registrations.every(r=>r.status==="pending"),"All four genuine generation paths must be durably registered pending review.");ok(Object.keys(registry.approvedRecomputationHandlers()).length===0,"Pending production bindings must not execute.");
 const real=async()=>({artifactHash:"a".repeat(64),dependencies:[],generatedAt:"2026-07-25T17:01:00Z",productionEvidence:true as const});const reg=registry.registerGovernedRecomputationHandler({handlerId:"tax-real-v2",kind:"tax-scenario",sourcePath:"src/lib/property/ownershipCostModel.ts#buildPostSaleTaxScenario",status:"pending",registeredAt:"2026-07-25T17:01:00Z"},real);
 const replayInput={price:200000,sellerCurrentAnnualTax:1000,currentTaxTransfersUnchanged:false,ownershipContext:{rates:{weekOf:"2026-07-23",rate30:6,rate15:null},taxContext:null,electricity:null,hpi:null}};const replayOutput=tax.buildPostSaleTaxScenario({price:200000,sellerCurrentAnnualTax:1000,currentTaxTransfersUnchanged:false},replayInput.ownershipContext as any);packets.preserveSignedReplayPacket({artifactId:"handler-tax-proof",propertyId:"p-handler",kind:"tax-scenario",dependencies:[],replayInput,replayOutput,capturedAt:"2026-07-25T17:01:30Z"});replay.attestDeterministicReplay({artifactId:"handler-tax-proof",handlerId:reg.handlerId,implementationHash:reg.implementationHash,at:"2026-07-25T17:01:45Z"});
 registry.decideGovernedRecomputationHandler({kind:"tax-scenario",decision:"APPROVE",reviewerId:"reviewer-1",reviewerName:"Reviewer One",reason:"Exact implementation and replay proof reviewed.",at:"2026-07-25T17:02:00Z"});ok(!!registry.approvedRecomputationHandlers()["tax-scenario"],"Exact reviewed implementation must resolve.");
 const changed=async()=>({artifactHash:"b".repeat(64),dependencies:[],generatedAt:"2026-07-25T17:03:00Z",productionEvidence:true as const});registry.registerGovernedRecomputationHandler({handlerId:"tax-real-v2",kind:"tax-scenario",sourcePath:"src/lib/property/ownershipCostModel.ts#buildPostSaleTaxScenario",status:"approved",registeredAt:"2026-07-25T17:03:00Z",reviewedBy:"reviewer-1",reviewedAt:"2026-07-25T17:02:00Z",reviewReason:"carry forward attempt"},changed);ok(!registry.approvedRecomputationHandlers()["tax-scenario"],"Changed implementation must reset to pending and lose execution authority.");registrations=registry.listGovernedRecomputationHandlers();ok(registrations.at(-1)?.status==="pending","Changed implementation must remain pending.");console.log(JSON.stringify({ok:true,rule:"OFFICIAL-EVIDENCE-DURABLE-HANDLER-GOVERNANCE-001",productionBindings:4,approvedAfterDrift:false,receipts:registry.listGovernedRecomputationHandlerReceipts().map(r=>r.decision)},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
