import assert from "node:assert/strict";
import type { InstitutionalAppealRemandDispositionImplementationEvaluation } from "@/lib/platform/institutionalAppealRemandDispositionImplementationAuthority";
import { institutionalAppealRemandImplementationMonitoringAuthority as authority } from "@/lib/platform/institutionalAppealRemandImplementationMonitoringAuthority";

const implementation={implementationPolicyId:"implementation-policy",reconciliationId:"recon-1",affectedScopes:["PUBLICATION"],decision:"ALLOW",resultingState:"PARTIALLY_IMPLEMENTED"} as unknown as InstitutionalAppealRemandDispositionImplementationEvaluation;
const policy=authority.createPolicy({policyId:"monitoring-policy",governanceVersion:"gov-1",monitoredScopes:["PUBLICATION"],reviewThreshold:.4,correctiveActionThreshold:.7,criticalSignalForcesEscalation:true,requireHumanReviewForMaterialSignals:true,requireCorrectiveActionNotice:true,requiredEvidenceRefs:["evidence-final"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=authority.evaluate({implementation,policy,signals:[authority.createSignal({signalId:"signal-1",scope:"PUBLICATION",severity:"INFO",score:.1,evidenceRefs:["signal-evidence"],observedAt:"2026-07-27T14:00:00Z"})],evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-27T14:10:00Z",auditRefs:["audit-eval"],replayRef:"replay-eval",monitoringComplete:true});
const review=authority.evaluate({implementation,policy,signals:[authority.createSignal({signalId:"signal-2",scope:"PUBLICATION",severity:"MATERIAL",score:.5,evidenceRefs:["signal-evidence"],observedAt:"2026-07-27T14:00:00Z"})],evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-27T14:10:00Z",auditRefs:["audit-review"],replayRef:"replay-review"});
const corrective=authority.evaluate({implementation,policy,signals:[authority.createSignal({signalId:"signal-3",scope:"PUBLICATION",severity:"WARNING",score:.8,evidenceRefs:["signal-evidence"],observedAt:"2026-07-27T14:00:00Z"})],correctiveActionNoticeRef:"notice-1",evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-27T14:10:00Z",auditRefs:["audit-corrective"],replayRef:"replay-corrective"});
const escalated=authority.evaluate({implementation,policy,signals:[authority.createSignal({signalId:"signal-4",scope:"PUBLICATION",severity:"CRITICAL",score:.9,evidenceRefs:["signal-evidence"],observedAt:"2026-07-27T14:00:00Z"})],humanReviewRefs:["review-1"],correctiveActionNoticeRef:"notice-2",evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-27T14:10:00Z",auditRefs:["audit-escalate"],replayRef:"replay-escalate"});
assert.equal(allowed.decision,"CONTINUE");assert.equal(allowed.resultingState,"COMPLETE");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(corrective.decision,"CORRECTIVE_ACTION");assert.equal(escalated.decision,"ESCALATE");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,corrective:corrective.decision,escalated:escalated.decision,state:allowed.resultingState,message:"Institutional appeal remand implementation monitoring authority conformance passed."},null,2));
