import { institutionalPostReinstatementMonitoringAuthority as authority } from "@/lib/platform/institutionalPostReinstatementMonitoringAuthority";
import type { InstitutionalReinstatementEvaluation } from "@/lib/platform/institutionalReinstatementAuthority";
function assert(condition: boolean, message: string): asserts condition { if (!condition) throw new Error(message); }
const reinstatement = Object.freeze({ schemaVersion: "institutional-reinstatement-v1", suspensionPolicyId: "suspend-policy", reinstatementPolicyId: "reinstate-policy", reconciliationId: "recon-1", mode: "LIFT_SELECTED", restoredScopes: Object.freeze(["PUBLICATION", "RELIANCE"]), remainingScopes: Object.freeze(["ACTION"]), decision: "ALLOW", resultingState: "PARTIALLY_REINSTATED", reasons: Object.freeze([]), reviewRefs: Object.freeze(["review-1"]), evidenceRefs: Object.freeze(["evidence-closure"]), evaluatedAt: "2026-07-22T08:00:00Z", auditRefs: Object.freeze(["audit-reinstate"]), replayRef: "replay-reinstate" }) as InstitutionalReinstatementEvaluation;
const policy = authority.createPolicy({ policyId: "monitor-policy", governanceVersion: "gov-1", monitoredScopes: ["PUBLICATION", "RELIANCE"], reviewThreshold: 0.4, resuspensionThreshold: 0.8, criticalSignalForcesEscalation: true, requireHumanReviewForMaterialSignals: true, requireNoticeOnResuspension: true, requiredEvidenceRefs: ["monitor-plan"], auditRefs: ["audit-policy"], replayRef: "replay-policy", versionRefs: ["version-1"] });
const warning = authority.createSignal({ signalId: "signal-warning", scope: "PUBLICATION", severity: "WARNING", score: 0.5, evidenceRefs: ["evidence-warning"], observedAt: "2026-07-22T08:10:00Z" });
const material = authority.createSignal({ signalId: "signal-material", scope: "RELIANCE", severity: "MATERIAL", score: 0.85, evidenceRefs: ["evidence-material"], observedAt: "2026-07-22T08:11:00Z" });
const critical = authority.createSignal({ signalId: "signal-critical", scope: "PUBLICATION", severity: "CRITICAL", score: 0.95, evidenceRefs: ["evidence-critical"], observedAt: "2026-07-22T08:12:00Z" });
const review = authority.evaluate({ reinstatement, policy, signals: [warning], evidenceRefs: ["monitor-plan"], evaluatedAt: "2026-07-22T08:20:00Z", auditRefs: ["audit-review"], replayRef: "replay-review" });
const resuspend = authority.evaluate({ reinstatement, policy, signals: [material], humanReviewRefs: ["human-review"], resuspensionNoticeRef: "notice-1", evidenceRefs: ["monitor-plan"], evaluatedAt: "2026-07-22T08:21:00Z", auditRefs: ["audit-resuspend"], replayRef: "replay-resuspend" });
const escalate = authority.evaluate({ reinstatement, policy, signals: [critical], humanReviewRefs: ["human-review"], resuspensionNoticeRef: "notice-2", evidenceRefs: ["monitor-plan"], evaluatedAt: "2026-07-22T08:22:00Z", auditRefs: ["audit-escalate"], replayRef: "replay-escalate" });
assert(review.decision === "REVIEW_REQUIRED" && review.resultingState === "REVIEW_PENDING", "Warning threshold must require review.");
assert(resuspend.decision === "RESUSPEND" && resuspend.resultingState === "RESUSPENSION_REQUIRED", "Material threshold must require resuspension.");
assert(escalate.decision === "ESCALATE" && escalate.resultingState === "ESCALATED", "Critical signal must escalate.");
console.log(JSON.stringify({ ok: true, schemaVersion: review.schemaVersion, review: review.decision, resuspend: resuspend.decision, escalate: escalate.decision, message: "Institutional post-reinstatement monitoring authority conformance passed." }, null, 2));
