import { institutionalRevocationAuthority } from "@/lib/platform/institutionalRevocationAuthority";
import type { InstitutionalMonitoringEvaluation } from "@/lib/platform/institutionalPostReinstatementMonitoringAuthority";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
const monitoring=Object.freeze({schemaVersion:"institutional-post-reinstatement-monitoring-v1",reinstatementPolicyId:"reinstate-policy",monitoringPolicyId:"monitor-policy",reconciliationId:"recon-1",decision:"RESUSPEND",resultingState:"RESUSPENSION_REQUIRED",aggregateScore:0.9,reasons:Object.freeze([]),affectedScopes:Object.freeze(["PUBLICATION","RELIANCE"]),signalRefs:Object.freeze(["signal-1"]),reviewRefs:Object.freeze(["review-1"]),evidenceRefs:Object.freeze(["evidence-monitor"]),evaluatedAt:"2026-07-22T14:00:00Z",auditRefs:Object.freeze(["audit-monitor"]),replayRef:"replay-monitor"}) as InstitutionalMonitoringEvaluation;
const policy=institutionalRevocationAuthority.createPolicy({policyId:"revoke-policy",governanceVersion:"gov-1",allowedModes:["REVOKE_SELECTED","DECLINE_REVOCATION"],requireMonitoringTrigger:true,requireHumanApproval:true,requireFinalNotice:true,fullRevocationAuthorized:false,claimRevocationAuthorized:false,publicationRevocationAuthorized:true,relianceRevocationAuthorized:true,actionRevocationAuthorized:false,requiredEvidenceRefs:["evidence-final"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalRevocationAuthority.evaluate({monitoring,policy,mode:"REVOKE_SELECTED",revokeScopes:["PUBLICATION","RELIANCE"],approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-22T14:10:00Z",auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=institutionalRevocationAuthority.evaluate({monitoring,policy,mode:"REVOKE_SELECTED",revokeScopes:["PUBLICATION"],evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-22T14:10:00Z",auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=institutionalRevocationAuthority.evaluate({monitoring,policy,mode:"REVOKE_SELECTED",revokeScopes:["ACTION"],approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],evaluatedAt:"2026-07-22T14:10:00Z",auditRefs:["audit-block"],replayRef:"replay-block"});
assert(allowed.decision==="ALLOW","Expected allowed revocation.");assert(allowed.resultingState==="PARTIALLY_REVOKED","Expected partial revocation.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required revocation.");assert(blocked.decision==="BLOCK","Expected blocked revocation.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional revocation authority conformance passed."},null,2));
