import { institutionalAppealRestorationMonitoringAuthority as authority } from "@/lib/platform/institutionalAppealRestorationMonitoringAuthority";
import type { InstitutionalAppealImplementationEvaluation } from "@/lib/platform/institutionalAppealImplementationAuthority";
function assert(v:boolean,m:string){if(!v)throw new Error(m);}
const implementation={implementationPolicyId:"implementation-policy",reconciliationId:"reconciliation-1",decision:"ALLOW",resultingState:"PARTIALLY_RESTORED",restoredScopes:["PUBLICATION"]} as unknown as InstitutionalAppealImplementationEvaluation;
const policy=authority.createPolicy({policyId:"monitor-policy",governanceVersion:"gov-1",monitoredScopes:["PUBLICATION"],reviewThreshold:0.4,resuspensionThreshold:0.8,criticalSignalForcesEscalation:true,requireHumanReviewForMaterialSignals:true,requireNoticeOnResuspension:true,requiredEvidenceRefs:["evidence-base"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const signal=(severity:"WARNING"|"MATERIAL"|"CRITICAL",score:number,id:string)=>authority.createSignal({signalId:id,scope:"PUBLICATION",severity,score,evidenceRefs:[`evidence-${id}`],observedAt:"2026-07-22T15:20:00Z"});
const review=authority.evaluate({implementation,policy,signals:[signal("WARNING",0.5,"review")],evidenceRefs:["evidence-base"],evaluatedAt:"2026-07-22T15:21:00Z",auditRefs:["audit-review"],replayRef:"replay-review"});
const resuspend=authority.evaluate({implementation,policy,signals:[signal("MATERIAL",0.9,"resuspend")],humanReviewRefs:["review-1"],resuspensionNoticeRef:"notice-1",evidenceRefs:["evidence-base"],evaluatedAt:"2026-07-22T15:21:00Z",auditRefs:["audit-resuspend"],replayRef:"replay-resuspend"});
const escalate=authority.evaluate({implementation,policy,signals:[signal("CRITICAL",0.2,"critical")],humanReviewRefs:["review-2"],evidenceRefs:["evidence-base"],evaluatedAt:"2026-07-22T15:21:00Z",auditRefs:["audit-escalate"],replayRef:"replay-escalate"});
assert(review.decision==="REVIEW_REQUIRED","Expected review.");assert(resuspend.decision==="RESUSPEND","Expected resuspension.");assert(escalate.decision==="ESCALATE","Expected escalation.");
console.log(JSON.stringify({ok:true,schemaVersion:review.schemaVersion,review:review.decision,resuspend:resuspend.decision,escalate:escalate.decision,message:"Institutional appeal restoration monitoring authority conformance passed."},null,2));
