import { institutionalReopeningAuthority } from "@/lib/platform/institutionalReopeningAuthority";
import type { InstitutionalClosureEvaluation } from "@/lib/platform/institutionalClosureAuthority";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
const closure=Object.freeze({schemaVersion:"institutional-closure-v1",reconciliationId:"recon-1",remediationPolicyId:"remediate-1",closurePolicyId:"closure-1",closureType:"CLOSE_AND_RESTORE",decision:"ALLOW",resultingState:"CLOSED_RESTORED",reasons:Object.freeze([]),reviewRefs:Object.freeze(["review-close"]),evidenceRefs:Object.freeze(["evidence-close"]),evaluatedAt:"2026-07-22T06:40:00Z",auditRefs:Object.freeze(["audit-close"]),replayRef:"replay-close"}) as InstitutionalClosureEvaluation;
const policy=institutionalReopeningAuthority.createPolicy({policyId:"reopen-1",governanceVersion:"gov-1",allowedBases:["NEW_EVIDENCE","LEGAL_MANDATE"],requireClosedMatter:true,requireIndependentReview:true,requireMaterialityEvidence:true,requireLegalReview:false,requireFraudEscalation:false,fullReopeningAuthorized:false,requiredEvidenceRefs:["evidence-new"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalReopeningAuthority.evaluate({closure,policy,basis:"NEW_EVIDENCE",fullReopeningRequested:false,independentReviewRefs:["review-1"],materialityEvidenceRef:"materiality-1",evidenceRefs:["evidence-new"],evaluatedAt:"2026-07-22T06:45:00Z",auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=institutionalReopeningAuthority.evaluate({closure,policy,basis:"LEGAL_MANDATE",fullReopeningRequested:false,independentReviewRefs:[],materialityEvidenceRef:null,legalReviewRef:null,evidenceRefs:["evidence-new"],evaluatedAt:"2026-07-22T06:45:00Z",auditRefs:["audit-eval-2"],replayRef:"replay-eval-2"});
const blocked=institutionalReopeningAuthority.evaluate({closure,policy,basis:"APPEAL",fullReopeningRequested:true,independentReviewRefs:["review-1"],materialityEvidenceRef:"materiality-1",evidenceRefs:["evidence-new"],evaluatedAt:"2026-07-22T06:45:00Z",auditRefs:["audit-eval-3"],replayRef:"replay-eval-3"});
assert(allowed.decision==="ALLOW","Expected allowed reopening.");assert(allowed.resultingState==="REOPENED_RESTRICTED","Expected restricted reopening.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required reopening.");assert(blocked.decision==="BLOCK","Expected blocked reopening.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional reopening authority conformance passed."},null,2));
