import type { InstitutionalRevocationEvaluation } from "@/lib/platform/institutionalRevocationAuthority";
import { institutionalRevocationAppealAuthority } from "@/lib/platform/institutionalRevocationAppealAuthority";
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
const revocation:InstitutionalRevocationEvaluation={schemaVersion:"institutional-revocation-v1",monitoringPolicyId:"monitor",revocationPolicyId:"revoke",reconciliationId:"reconcile",mode:"REVOKE_SELECTED",revokedScopes:["PUBLICATION","RELIANCE"],decision:"ALLOW",resultingState:"PARTIALLY_REVOKED",reasons:[],approvalRefs:["approval-revoke"],evidenceRefs:["evidence-revoke"],evaluatedAt:"2026-07-22T14:10:00Z",auditRefs:["audit-revoke"],replayRef:"replay-revoke"};
const policy=institutionalRevocationAppealAuthority.createPolicy({policyId:"appeal-policy",governanceVersion:"gov-1",allowedDispositions:["AFFIRM","MODIFY","REVERSE","REMAND"],filingWindowDays:30,requireStanding:true,requireIndependentReview:true,requireDispositionApproval:true,requireFinalNotice:true,scopeRestorationAuthorized:true,requiredEvidenceRefs:["evidence-appeal"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalRevocationAppealAuthority.evaluate({revocation,policy,disposition:"REVERSE",appealedScopes:["PUBLICATION"],filedAt:"2026-07-23T14:10:00Z",evaluatedAt:"2026-07-24T14:10:00Z",standingRefs:["standing-1"],independentReviewRefs:["review-1"],approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-appeal"],auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=institutionalRevocationAppealAuthority.evaluate({revocation,policy,disposition:"AFFIRM",appealedScopes:["PUBLICATION"],filedAt:"2026-07-23T14:10:00Z",evaluatedAt:"2026-07-24T14:10:00Z",evidenceRefs:["evidence-appeal"],auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=institutionalRevocationAppealAuthority.evaluate({revocation,policy,disposition:"REVERSE",appealedScopes:["ACTION"],filedAt:"2026-09-30T14:10:00Z",evaluatedAt:"2026-10-01T14:10:00Z",standingRefs:["standing-1"],independentReviewRefs:["review-1"],approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-appeal"],auditRefs:["audit-block"],replayRef:"replay-block"});
assert(allowed.decision==="ALLOW"&&allowed.resultingState==="REVERSED","Expected allowed reversal.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required appeal.");assert(blocked.decision==="BLOCK","Expected blocked appeal.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional revocation appeal authority conformance passed."},null,2));
