import { institutionalLifecycleCycleReinstatementAuthority as authority } from "@/lib/platform/institutionalLifecycleCycleReinstatementAuthority";
import type { InstitutionalLifecycleCycleSuspensionEvaluation } from "@/lib/platform/institutionalLifecycleCycleSuspensionAuthority";
const assert=(c:unknown,m:string)=>{if(!c)throw new Error(m)};
const suspension:InstitutionalLifecycleCycleSuspensionEvaluation={schemaVersion:"institutional-lifecycle-cycle-suspension-v1",cyclePolicyId:"cp",cycleId:"cycle-2",generation:2,reopeningPolicyId:"rp",suspensionPolicyId:"sp",canonicalObjectId:"case-1",scopes:["CLAIM","PUBLICATION"],emergency:false,decision:"ALLOW",resultingState:"PARTIALLY_SUSPENDED",reasons:[],approvalRefs:["approval"],evidenceRefs:["e"],evaluatedAt:"2026-07-04T00:00:00Z",auditRefs:["a"],replayRef:"replay-1"};
const policy=authority.createPolicy({policyId:"reip",governanceVersion:"g1",allowedModes:["LIFT_SELECTED","LIFT_ALL","KEEP_SUSPENDED","ESCALATE"],requireAllowedSuspension:true,requireRiskResolutionEvidence:true,requireIndependentReview:true,requireMonitoringPlan:true,requireAffectedPartyNotice:true,fullReinstatementAuthorized:true,claimReinstatementAuthorized:true,publicationReinstatementAuthorized:true,relianceReinstatementAuthorized:true,actionReinstatementAuthorized:true,requiredEvidenceRefs:["e"],auditRefs:["a"],replayRef:"replay-1",versionRefs:["v1"]});
const base={suspension,policy,mode:"LIFT_SELECTED" as const,restoreScopes:["CLAIM"] as const,riskResolutionEvidenceRef:"risk",independentReviewRefs:["review"],monitoringPlanRef:"monitor",affectedPartyNoticeRef:"notice",evidenceRefs:["e"],evaluatedAt:"2026-07-04T00:01:00Z",auditRefs:["a"],replayRef:"replay-1"} as const;
const allowed=authority.evaluate(base);const review=authority.evaluate({...base,monitoringPlanRef:null});const full=authority.evaluate({...base,mode:"LIFT_ALL",restoreScopes:[]});const blocked=authority.evaluate({...base,replayRef:"wrong"});
assert(allowed.decision==="ALLOW"&&allowed.resultingState==="PARTIALLY_REINSTATED","Expected partial reinstatement.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required reinstatement.");assert(full.decision==="ALLOW"&&full.resultingState==="FULLY_REINSTATED","Expected full reinstatement.");assert(blocked.decision==="BLOCK","Expected blocked reinstatement.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,full:full.resultingState,blocked:blocked.decision,generation:allowed.generation,message:"Institutional lifecycle cycle reinstatement authority conformance passed."},null,2));
