import assert from "node:assert/strict";
import { evaluateInstitutionalAppealRemandArchiveReopeningPostReinstatementMonitoring as evaluate } from "@/lib/platform/institutionalAppealRemandArchiveReopeningPostReinstatementMonitoringAuthority";
import type { InstitutionalAppealRemandArchiveReopeningPostReinstatementMonitoringPolicy } from "@/lib/platform/institutionalAppealRemandArchiveReopeningPostReinstatementMonitoringAuthority";
import type { InstitutionalAppealRemandArchiveReopeningReinstatementEvaluation } from "@/lib/platform/institutionalAppealRemandArchiveReopeningReinstatementAuthority";

const reinstatement=Object.freeze({schemaVersion:"institutional-appeal-remand-archive-reopening-reinstatement-v1",suspensionPolicyId:"suspend-1",reinstatementPolicyId:"reinstate-1",canonicalObjectId:"object-1",mode:"LIFT_SELECTED",restoredScopes:Object.freeze(["CLAIM"]),remainingScopes:Object.freeze(["PUBLICATION"]),decision:"ALLOW",resultingState:"PARTIALLY_REINSTATED",reasons:Object.freeze([]),reviewRefs:Object.freeze(["review-1"]),evidenceRefs:Object.freeze(["evidence-1"]),evaluatedAt:"2026-07-22T18:00:00Z",auditRefs:Object.freeze(["audit-1"]),replayRef:"replay-1"}) as InstitutionalAppealRemandArchiveReopeningReinstatementEvaluation;
const policy:InstitutionalAppealRemandArchiveReopeningPostReinstatementMonitoringPolicy=Object.freeze({policyId:"monitor-1",governanceVersion:"v1",monitoredScopes:Object.freeze(["CLAIM","PUBLICATION"] as const),reviewThreshold:.4,resuspensionThreshold:.8,criticalSignalForcesEscalation:true,requireHumanReviewForMaterialSignals:true,requireNoticeOnResuspension:true,requiredEvidenceRefs:Object.freeze(["evidence-1"]),auditRefs:Object.freeze(["audit-policy"]),replayRef:"replay-1",versionRefs:Object.freeze(["version-1"])});
const base={reinstatement,policy,evidenceRefs:["evidence-1"],evaluatedAt:"2026-07-22T18:10:00Z",auditRefs:["audit-eval"],replayRef:"replay-1"};
const allowed=evaluate({...base,signals:[{signalId:"info",scope:"CLAIM",severity:"INFO",score:.1,evidenceRefs:["evidence-1"],observedAt:"2026-07-22T18:05:00Z"}],monitoringComplete:true});
const review=evaluate({...base,signals:[{signalId:"material",scope:"CLAIM",severity:"MATERIAL",score:.5,evidenceRefs:["evidence-1"],observedAt:"2026-07-22T18:05:00Z"}]});
const resuspend=evaluate({...base,signals:[{signalId:"high",scope:"PUBLICATION",severity:"WARNING",score:.9,evidenceRefs:["evidence-1"],observedAt:"2026-07-22T18:05:00Z"}],resuspensionNoticeRef:"notice-1"});
const escalated=evaluate({...base,signals:[{signalId:"critical",scope:"CLAIM",severity:"CRITICAL",score:.7,evidenceRefs:["evidence-1"],observedAt:"2026-07-22T18:05:00Z"}],humanReviewRefs:["review-2"]});
assert.equal(allowed.decision,"CONTINUE");assert.equal(allowed.resultingState,"COMPLETE");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(resuspend.decision,"RESUSPEND");assert.equal(escalated.decision,"ESCALATE");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,resuspend:resuspend.decision,escalated:escalated.decision,state:allowed.resultingState,message:"Institutional appeal remand archive reopening post-reinstatement monitoring authority conformance passed."},null,2));
