import { institutionalSuspensionAuthority } from "@/lib/platform/institutionalSuspensionAuthority";
import type { InstitutionalReopeningEvaluation } from "@/lib/platform/institutionalReopeningAuthority";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
const reopening=Object.freeze({schemaVersion:"institutional-reopening-v1",closurePolicyId:"closure-1",reopeningPolicyId:"reopen-1",reconciliationId:"recon-1",basis:"NEW_EVIDENCE",decision:"ALLOW",resultingState:"REOPENED_RESTRICTED",reasons:Object.freeze([]),reviewRefs:Object.freeze(["review-1"]),evidenceRefs:Object.freeze(["evidence-risk"]),evaluatedAt:"2026-07-22T07:00:00Z",auditRefs:Object.freeze(["audit-reopen"]),replayRef:"replay-reopen"}) as InstitutionalReopeningEvaluation;
const policy=institutionalSuspensionAuthority.createPolicy({policyId:"suspend-1",governanceVersion:"gov-1",allowedScopes:["CLAIM","PUBLICATION","RELIANCE","ACTION"],requireReopenedMatter:true,requireRiskEvidence:true,requireHumanApproval:true,requireNotice:true,fullMatterSuspensionAuthorized:false,emergencySuspensionAuthorized:true,requiredEvidenceRefs:["evidence-risk"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalSuspensionAuthority.evaluate({reopening,policy,scopes:["PUBLICATION","RELIANCE","ACTION"],emergency:false,approvalRefs:["approval-1"],riskEvidenceRef:"risk-1",noticeRef:"notice-1",evidenceRefs:["evidence-risk"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-1"],replayRef:"replay-1"});
const review=institutionalSuspensionAuthority.evaluate({reopening,policy,scopes:["CLAIM"],emergency:false,approvalRefs:[],riskEvidenceRef:null,noticeRef:null,evidenceRefs:["evidence-risk"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-2"],replayRef:"replay-2"});
const blocked=institutionalSuspensionAuthority.evaluate({reopening,policy,scopes:["FULL_MATTER"],emergency:false,approvalRefs:["approval-1"],riskEvidenceRef:"risk-1",noticeRef:"notice-1",evidenceRefs:["evidence-risk"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-3"],replayRef:"replay-3"});
assert(allowed.decision==="ALLOW","Expected allowed suspension.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required suspension.");assert(blocked.decision==="BLOCK","Expected blocked suspension.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional suspension authority conformance passed."},null,2));
