import { institutionalAppealRemandResolutionAuthority as authority } from "@/lib/platform/institutionalAppealRemandResolutionAuthority";
import type { InstitutionalAppealImplementationEvaluation } from "@/lib/platform/institutionalAppealImplementationAuthority";
function assert(c:unknown,m:string):asserts c{if(!c)throw new Error(m);}
const implementation={implementationPolicyId:"implementation-policy",reconciliationId:"recon-1",decision:"ALLOW",resultingState:"REMANDED_PENDING"} as unknown as InstitutionalAppealImplementationEvaluation;
const policy=authority.createPolicy({policyId:"remand-policy",governanceVersion:"gov-1",allowedModes:["RETURN_AFFIRMED","RETURN_MODIFIED","RETURN_REVERSED","REQUIRE_FURTHER_ACTION"],requireAssignedAuthority:true,requireCompletionEvidence:true,requireDispositionApproval:true,requireResolutionNotice:true,requiredEvidenceRefs:["evidence-remand"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=authority.evaluate({implementation,policy,mode:"RETURN_MODIFIED",authorityRefs:["authority-1"],completionEvidenceRef:"completion-1",approvalRefs:["approval-1"],resolutionNoticeRef:"notice-1",evidenceRefs:["evidence-remand"],resolvedAt:"2026-07-22T16:35:00Z",auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=authority.evaluate({implementation,policy,mode:"RETURN_MODIFIED",evidenceRefs:["evidence-remand"],resolvedAt:"2026-07-22T16:35:00Z",auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=authority.evaluate({implementation:{...implementation,resultingState:"FULLY_RESTORED"} as InstitutionalAppealImplementationEvaluation,policy,mode:"RETURN_MODIFIED",authorityRefs:["authority-1"],completionEvidenceRef:"completion-1",approvalRefs:["approval-1"],resolutionNoticeRef:"notice-1",evidenceRefs:["evidence-remand"],resolvedAt:"2026-07-22T16:35:00Z",auditRefs:["audit-block"],replayRef:"replay-block"});
assert(allowed.decision==="ALLOW"&&allowed.resultingState==="RESOLVED_MODIFIED","Expected allowed remand resolution.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required remand resolution.");assert(blocked.decision==="BLOCK","Expected blocked remand resolution.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional appeal remand resolution authority conformance passed."},null,2));
