import { createInstitutionalClaim } from "@/lib/platform/institutionalClaimAuthority";
import { createInstitutionalPublicationPolicy, evaluateInstitutionalPublication } from "@/lib/platform/institutionalPublicationAuthority";
import { createUniversalInstitutionalGraph } from "@/lib/platform/universalInstitutionalGraphRuntime";
import { createCanonicalIdentity } from "@/lib/platform/canonicalIdentityAuthority";

function assert(condition: boolean, message: string): asserts condition { if (!condition) throw new Error(message); }
const at = "2026-07-22T06:00:00.000Z";
const identity = createCanonicalIdentity({ canonicalIdentityId: "identity:property:publication", domain: "property", governanceVersion: "master-volume-series-2026-07", status: "ACTIVE", aliases: ["Publication Farm"], confidence: "VERIFIED", matchScore: 1, provenanceRefs: ["source:property"], auditRefs: ["audit:identity"], replayRef: "replay:identity", versionRefs: ["version:identity"], createdAt: at, recordedAt: at });
const graph = createUniversalInstitutionalGraph({ governanceVersion: "master-volume-series-2026-07", replayRef: "replay:graph", identities: [identity], objectBindings: { "property:publication": identity.canonicalIdentityId }, relationships: [] });
const claim = createInstitutionalClaim({ claimId: "claim:property:publication", governanceVersion: "master-volume-series-2026-07", subjectCanonicalIdentityId: identity.canonicalIdentityId, predicate: "HAS_ADVISORY_MARKET_PROFILE", value: { available: true }, authority: { authorityId: "authority:market-intelligence", authorityType: "ADVISORY_SOURCE_AUTHORITY", scope: ["market-profile"] }, basis: { nodeIds: [identity.canonicalIdentityId], sourceRefs: ["source:market"] }, verificationStatus: "VERIFIED", state: "ACTIVE", audience: ["public", "borrower"], effectiveAt: at, recordedAt: at, validationRefs: ["validation:claim"], escalationRefs: [], auditRefs: ["audit:claim"], replayRef: "replay:claim", versionRefs: ["version:claim"] });
const policy = createInstitutionalPublicationPolicy({ policyId: "policy:public-advisory", governanceVersion: "master-volume-series-2026-07", surface: "PUBLIC", allowedAudiences: ["public"], allowedAuthorityTypes: ["ADVISORY_SOURCE_AUTHORITY"], maximumRelianceLevel: "ADVISORY_ONLY", requiredDisclosures: ["advisory-only", "not-an-approval", "not-public-verification"], prohibitedPredicates: ["IS_APPROVED", "IS_CERTIFIED"], requireHumanReview: false, publicVerificationAuthorized: false, officialRelianceAuthorized: false, auditRefs: ["audit:policy"], replayRef: "replay:policy", versionRefs: ["version:policy"] });
const allowed = evaluateInstitutionalPublication({ claim, graph, policy, requestedRelianceLevel: "ADVISORY_ONLY", audience: "public", evaluatedAt: at, auditRefs: ["audit:evaluation"], replayRef: "replay:evaluation" });
assert(allowed.decision === "ALLOW", "Advisory public claim should be allowed.");
const blocked = evaluateInstitutionalPublication({ claim, graph, policy, requestedRelianceLevel: "OFFICIAL", audience: "public", evaluatedAt: at, auditRefs: ["audit:evaluation:blocked"], replayRef: "replay:evaluation:blocked" });
assert(blocked.decision === "BLOCK" && blocked.reasons.includes("reliance-exceeds-policy"), "Official reliance must fail closed.");
const reviewPolicy = createInstitutionalPublicationPolicy({ ...policy, policyId: "policy:borrower-review", surface: "BORROWER", allowedAudiences: ["borrower"], requireHumanReview: true });
const review = evaluateInstitutionalPublication({ claim, graph, policy: reviewPolicy, requestedRelianceLevel: "ADVISORY_ONLY", audience: "borrower", evaluatedAt: at, auditRefs: ["audit:evaluation:review"], replayRef: "replay:evaluation:review" });
assert(review.decision === "REVIEW_REQUIRED", "Human review policy must route to review.");
console.log(JSON.stringify({ ok: true, schemaVersion: allowed.schemaVersion, allowed: allowed.decision, blocked: blocked.decision, review: review.decision, message: "Institutional publication authority conformance passed." }, null, 2));
