import fs from "node:fs";import os from "node:os";import path from "node:path";
function ok(v:unknown,m:string):asserts v{if(!v)throw new Error(m)}
async function main(){process.env.FURLONG_RUNTIME_STATE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),"furlong-prod-replay-"));process.env.EVIDENCE_REPLAY_SIGNING_SECRET="production-replay-test-secret";
 const store=await import("@/lib/property/officialEvidenceRuntimeStore");const capture=await import("@/lib/property/officialEvidenceGenerationCapture");const replay=await import("@/lib/property/officialEvidenceReplayExecutor");const registry=await import("@/lib/property/officialEvidenceRecomputationHandlerRegistry");const tax=await import("@/lib/property/ownershipCostModel");const ranking=await import("@/lib/intelligence/scenarioRankingPlan");const market=await import("@/lib/intelligence/marketComparablePlan");const capital=await import("@/lib/intelligence/preliminaryCapitalPlan");const financing=await import("@/lib/financing/intakeRuntime");const brief=await import("@/lib/property/propertyBriefIntelligence");
 store.writeOfficialEvidenceRefreshState({sourceId:"parcel-tax-authority",snapshots:[],receipts:[],publishedVersion:"tax-representative-v1"});store.writeOfficialEvidenceRefreshState({sourceId:"well-permit-authority",snapshots:[],receipts:[],publishedVersion:"well-representative-v1"});
 const taxInput={price:425000,sellerCurrentAnnualTax:1800,currentTaxTransfersUnchanged:false,ownershipContext:{rates:{weekOf:"2026-07-23",rate30:6.2,rate15:null},taxContext:{medianAnnualTax:3200,medianHomeValue:290000,effectiveRatePct:1.1},electricity:null,hpi:null}};const taxOutput=tax.buildPostSaleTaxScenario({price:taxInput.price,sellerCurrentAnnualTax:taxInput.sellerCurrentAnnualTax,currentTaxTransfersUnchanged:false},taxInput.ownershipContext as any);
 const marketPlan=market.buildMarketComparablePlan({profileId:"farm",comparables:[]});const capitalPlan=capital.buildPreliminaryCapitalPlan({profileId:"farm",listedPrice:425000,requestedAmount:null,pathwayNames:["FSA Direct Farm Ownership"]});const topInput={profileId:"farm" as const,marketPlan,capitalPlan,pathwayCount:1,taxImpact:{acquisitionPrice:425000,stabilizedAnnual:4675,adverseAnnual:5844},infrastructureRisk:null};const topOutput=ranking.buildScenarioRankingPlan(topInput);
 const qualificationInput={applicationId:"representative-application",purpose:"acquisition" as const,programInterest:"fsa" as const,contactName:"Representative Applicant",contactEmail:"representative@example.test",propertyDescriptor:"Representative Farm",location:{state:"MD",county:"Caroline"},estimatedProjectCost:425000,scopeSummary:"Representative deterministic replay",timeline:"12 months",feeDisclosureAcknowledged:true,consentAcknowledged:true};const qualificationOutput=financing.evaluateFinancingIntake(qualificationInput);const capturedAt=qualificationOutput.generatedAt;
 const briefInput={propertyId:null,sourceId:null,propertyType:"farm",priceLabel:"$425,000",county:"Caroline County",town:"Federalsburg",stateCode:"MD",pathwayList:["FSA Direct Farm Ownership"],description:"Representative working farm"};const briefOutput=brief.buildPropertyBriefIntelligence(briefInput);
 const fixtures=[{kind:"tax-scenario" as const,id:"representative:tax",input:taxInput,output:taxOutput},{kind:"top-three" as const,id:"representative:top-three",input:topInput,output:topOutput},{kind:"qualification-result" as const,id:"representative:qualification",input:qualificationInput,output:qualificationOutput,at:capturedAt},{kind:"property-report" as const,id:"representative:report",input:briefInput,output:briefOutput}];
 const handler=()=>({artifactHash:"a".repeat(64),dependencies:[],generatedAt:"2026-07-25T18:00:00Z",productionEvidence:true as const});const matched:string[]=[];
 for(const f of fixtures){capture.captureGeneratedEvidenceArtifact({kind:f.kind,propertyId:"representative-property",artifactId:f.id,generatedAt:f.at??"2026-07-25T18:00:00Z",replayInput:f.input,replayOutput:f.output});const registration=registry.registerGovernedRecomputationHandler({handlerId:`production-${f.kind}-v1`,kind:f.kind,sourcePath:`src/production/${f.kind}.ts`,status:"pending"},handler);const attestation=replay.attestDeterministicReplay({artifactId:f.id,handlerId:registration.handlerId,implementationHash:registration.implementationHash});ok(attestation.matched,`${f.kind} representative replay must match.`);registry.decideGovernedRecomputationHandler({kind:f.kind,decision:"APPROVE",reviewerId:"module45-test-reviewer",reviewerName:"Module 45 Test Reviewer",reason:"Representative deterministic replay matched exact implementation."});matched.push(f.kind)}
 ok(Object.keys(registry.approvedRecomputationHandlers()).length===4,"All four exact test implementations must be approved after matching proof.");const page=fs.readFileSync("src/app/internal/evidence-recomputation/page.tsx","utf8");ok(page.includes("Run deterministic replay")&&page.includes("Approve exact implementation"),"Human review surface must expose proof and approval actions.");console.log(JSON.stringify({ok:true,rule:"OFFICIAL-EVIDENCE-PRODUCTION-REPLAY-REVIEW-001",matched,approved:4,reviewSurface:"/internal/evidence-recomputation"},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
