import { institutionalClosureAuthority } from "@/lib/platform/institutionalClosureAuthority";
import type { InstitutionalOutcomeReconciliation } from "@/lib/platform/institutionalOutcomeReconciliationAuthority";
import type { InstitutionalRemediationEvaluation } from "@/lib/platform/institutionalRemediationAuthority";

function assert(c: boolean, m: string): asserts c { if (!c) throw new Error(m); }
const reconciliation = Object.freeze({ reconciliationId: "recon-closure-1", schemaVersion: "institutional-outcome-reconciliation-v1", governanceVersion: "gov-1", receiptId: "receipt-1", claimId: "claim-1", actionType: "WORKFLOW_TRANSITION", state: "REMEDIATION_PENDING", severity: "HIGH", expectedOutcome: Object.freeze({ status: "approved" }), observedOutcome: Object.freeze({ status: "pending" }), mismatchFields: Object.freeze(["status"]), exceptionRef: "exception-1", remediationRefs: Object.freeze(["remediation-1"]), reversalReceiptRef: null, humanReviewRefs: Object.freeze(["review-1"]), reconciledAt: "2026-07-22T06:00:00Z", resolvedAt: null, evidenceRefs: Object.freeze(["evidence-1"]), auditRefs: Object.freeze(["audit-1"]), replayRef: "replay-recon", versionRefs: Object.freeze(["version-1"]) }) as InstitutionalOutcomeReconciliation;
const remediation = Object.freeze({ schemaVersion: "institutional-remediation-v1", reconciliationId: reconciliation.reconciliationId, exceptionRef: "exception-1", policyId: "remediation-policy-1", remediationType: "CORRECTIVE_UPDATE", decision: "ALLOW", reasons: Object.freeze([]), approvalRefs: Object.freeze(["approval-a", "approval-b"]), evidenceRefs: Object.freeze(["evidence-1"]), evaluatedAt: "2026-07-22T06:10:00Z", auditRefs: Object.freeze(["audit-remediation"]), replayRef: "replay-remediation" }) as InstitutionalRemediationEvaluation;
const policy = institutionalClosureAuthority.createPolicy({ policyId: "closure-policy-1", governanceVersion: "gov-1", allowedTypes: ["CLOSE_AND_RESTORE", "CLOSE_RESTRICTED", "KEEP_OPEN"], requireAllowedRemediation: true, requireIndependentReview: true, requireResolutionEvidence: true, requireMonitoringPlan: true, requireAffectedPartyConfirmation: false, claimRestorationAuthorized: true, publicationRestorationAuthorized: true, relianceRestorationAuthorized: true, requiredEvidenceRefs: ["evidence-1"], auditRefs: ["audit-policy"], replayRef: "replay-policy", versionRefs: ["version-policy"] });
const allowed = institutionalClosureAuthority.evaluate({ reconciliation, remediation, policy, closureType: "CLOSE_AND_RESTORE", independentReviewRefs: ["independent-review-1"], resolutionEvidenceRef: "resolution-evidence-1", monitoringPlanRef: "monitoring-1", evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:20:00Z", auditRefs: ["audit-eval"], replayRef: "replay-eval" });
const review = institutionalClosureAuthority.evaluate({ reconciliation, remediation, policy, closureType: "CLOSE_RESTRICTED", independentReviewRefs: [], resolutionEvidenceRef: null, monitoringPlanRef: null, evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:20:00Z", auditRefs: ["audit-eval-2"], replayRef: "replay-eval-2" });
const restrictedPolicy = institutionalClosureAuthority.createPolicy({ ...policy, policyId: "closure-policy-2", allowedTypes: ["CLOSE_RESTRICTED"], claimRestorationAuthorized: false, publicationRestorationAuthorized: false, relianceRestorationAuthorized: false });
const blocked = institutionalClosureAuthority.evaluate({ reconciliation, remediation, policy: restrictedPolicy, closureType: "CLOSE_AND_RESTORE", independentReviewRefs: ["review-1"], resolutionEvidenceRef: "resolution-1", monitoringPlanRef: "monitoring-1", evidenceRefs: ["evidence-1"], evaluatedAt: "2026-07-22T06:20:00Z", auditRefs: ["audit-eval-3"], replayRef: "replay-eval-3" });
assert(allowed.decision === "ALLOW" && allowed.resultingState === "CLOSED_RESTORED", "Expected restored closure.");
assert(review.decision === "REVIEW_REQUIRED", "Expected review-required closure.");
assert(blocked.decision === "BLOCK", "Expected blocked restoration.");
console.log(JSON.stringify({ ok: true, schemaVersion: allowed.schemaVersion, allowed: allowed.decision, review: review.decision, blocked: blocked.decision, state: allowed.resultingState, message: "Institutional closure authority conformance passed." }, null, 2));
