import { institutionalAppealMonitoringDischargeAuthority } from "@/lib/platform/institutionalAppealMonitoringDischargeAuthority";
import type { InstitutionalAppealRestorationMonitoringEvaluation } from "@/lib/platform/institutionalAppealRestorationMonitoringAuthority";
function assert(v:unknown,m:string):asserts v{if(!v)throw new Error(m);}
const monitoring={monitoringPolicyId:"monitoring-policy",reconciliationId:"reconciliation-1",decision:"CONTINUE",resultingState:"COMPLETE"} as unknown as InstitutionalAppealRestorationMonitoringEvaluation;
const policy=institutionalAppealMonitoringDischargeAuthority.createPolicy({policyId:"discharge-policy",governanceVersion:"gov-1",minimumMonitoringDays:30,requireCleanReviewHistory:true,requireFinalAssessment:true,requireHumanApproval:true,requireFinalNotice:true,requiredEvidenceRefs:["evidence-final"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalAppealMonitoringDischargeAuthority.evaluate({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-06-01T00:00:00Z",evaluatedAt:"2026-07-22T15:40:00Z",cleanReviewHistory:true,finalAssessmentRef:"assessment-1",approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=institutionalAppealMonitoringDischargeAuthority.evaluate({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-06-01T00:00:00Z",evaluatedAt:"2026-07-22T15:40:00Z",cleanReviewHistory:true,evidenceRefs:["evidence-final"],auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=institutionalAppealMonitoringDischargeAuthority.evaluate({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-07-10T00:00:00Z",evaluatedAt:"2026-07-22T15:40:00Z",cleanReviewHistory:true,finalAssessmentRef:"assessment-1",approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],auditRefs:["audit-block"],replayRef:"replay-block"});
assert(allowed.decision==="ALLOW","Expected allowed discharge.");assert(allowed.resultingState==="DISCHARGED","Expected discharged state.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required discharge.");assert(blocked.decision==="BLOCK","Expected blocked discharge.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional appeal monitoring discharge authority conformance passed."},null,2));
