import assert from "node:assert/strict";
import { institutionalAppealRemandArchiveReopeningReinstatementAuthority as A } from "@/lib/platform/institutionalAppealRemandArchiveReopeningReinstatementAuthority";
import type { InstitutionalAppealRemandArchiveReopeningSuspensionEvaluation } from "@/lib/platform/institutionalAppealRemandArchiveReopeningSuspensionAuthority";
const suspension=Object.freeze({schemaVersion:"institutional-appeal-remand-archive-reopening-suspension-v1",reopeningPolicyId:"rp",suspensionPolicyId:"sp",canonicalObjectId:"case-1",scopes:Object.freeze(["CLAIM","ACTION"]),emergency:false,decision:"ALLOW",resultingState:"PARTIALLY_SUSPENDED",reasons:Object.freeze([]),approvalRefs:Object.freeze(["a"]),evidenceRefs:Object.freeze(["e"]),evaluatedAt:"2026-07-01T00:00:00Z",auditRefs:Object.freeze(["a"]),replayRef:"replay-1"}) as InstitutionalAppealRemandArchiveReopeningSuspensionEvaluation;
const policy=A.createPolicy({policyId:"ip",governanceVersion:"g1",allowedModes:["LIFT_SELECTED","LIFT_ALL","KEEP_SUSPENDED","ESCALATE"],requireAllowedSuspension:true,requireRiskResolutionEvidence:true,requireIndependentReview:true,requireMonitoringPlan:true,requireAffectedPartyNotice:true,fullReinstatementAuthorized:true,claimReinstatementAuthorized:true,publicationReinstatementAuthorized:true,relianceReinstatementAuthorized:true,actionReinstatementAuthorized:true,requiredEvidenceRefs:["e"],auditRefs:["a"],replayRef:"replay-1",versionRefs:["v1"]});
const base={suspension,policy,riskResolutionEvidenceRef:"risk",independentReviewRefs:["review"],monitoringPlanRef:"monitor",affectedPartyNoticeRef:"notice",evidenceRefs:["e"],evaluatedAt:"2026-07-02T00:00:00Z",auditRefs:["a"],replayRef:"replay-1"} as const;
const allowed=A.evaluate({...base,mode:"LIFT_SELECTED",restoreScopes:["CLAIM"]});const full=A.evaluate({...base,mode:"LIFT_ALL"});const review=A.evaluate({...base,mode:"LIFT_SELECTED",restoreScopes:["CLAIM"],monitoringPlanRef:null});const blocked=A.evaluate({...base,mode:"LIFT_SELECTED",restoreScopes:["PUBLICATION"]});
assert.equal(allowed.decision,"ALLOW");assert.equal(allowed.resultingState,"PARTIALLY_REINSTATED");assert.equal(full.resultingState,"FULLY_REINSTATED");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(blocked.decision,"BLOCK");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,fullState:full.resultingState,message:"Institutional appeal remand archive reopening reinstatement authority conformance passed."},null,2));
