import assert from "node:assert/strict";
import type { InstitutionalAppealRemandImplementationMonitoringEvaluation } from "@/lib/platform/institutionalAppealRemandImplementationMonitoringAuthority";
import { createInstitutionalAppealRemandMonitoringDischargePolicy, evaluateInstitutionalAppealRemandMonitoringDischarge } from "@/lib/platform/institutionalAppealRemandMonitoringDischargeAuthority";

const monitoring={monitoringPolicyId:"remand-monitor-policy",reconciliationId:"reconciliation-1",decision:"CONTINUE",resultingState:"COMPLETE"} as unknown as InstitutionalAppealRemandImplementationMonitoringEvaluation;
const policy=createInstitutionalAppealRemandMonitoringDischargePolicy({policyId:"remand-discharge-policy",governanceVersion:"gov-1",minimumMonitoringDays:30,requireCleanReviewHistory:true,requireFinalAssessment:true,requireHumanApproval:true,requireFinalNotice:true,requiredEvidenceRefs:["evidence-final"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=evaluateInstitutionalAppealRemandMonitoringDischarge({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-06-01T00:00:00Z",evaluatedAt:"2026-07-26T00:00:00Z",cleanReviewHistory:true,finalAssessmentRef:"assessment-1",approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=evaluateInstitutionalAppealRemandMonitoringDischarge({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-06-01T00:00:00Z",evaluatedAt:"2026-07-26T00:00:00Z",cleanReviewHistory:true,evidenceRefs:["evidence-final"],auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=evaluateInstitutionalAppealRemandMonitoringDischarge({monitoring,policy,mode:"DISCHARGE",monitoringStartedAt:"2026-07-20T00:00:00Z",evaluatedAt:"2026-07-26T00:00:00Z",cleanReviewHistory:true,finalAssessmentRef:"assessment-1",approvalRefs:["approval-1"],finalNoticeRef:"notice-1",evidenceRefs:["evidence-final"],auditRefs:["audit-block"],replayRef:"replay-block"});
assert.equal(allowed.decision,"ALLOW");assert.equal(allowed.resultingState,"DISCHARGED");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(blocked.decision,"BLOCK");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional appeal remand monitoring discharge authority conformance passed."},null,2));
