import { institutionalReinstatementAuthority } from "@/lib/platform/institutionalReinstatementAuthority";
import type { InstitutionalSuspensionEvaluation } from "@/lib/platform/institutionalSuspensionAuthority";
function assert(c:boolean,m:string):asserts c{if(!c)throw new Error(m);}
const suspension=Object.freeze({schemaVersion:"institutional-suspension-v1",reopeningPolicyId:"reopen-policy",suspensionPolicyId:"suspend-policy",reconciliationId:"recon-1",scopes:Object.freeze(["PUBLICATION","RELIANCE","ACTION"]),emergency:false,decision:"ALLOW",resultingState:"PARTIALLY_SUSPENDED",reasons:Object.freeze([]),approvalRefs:Object.freeze(["approval-1"]),evidenceRefs:Object.freeze(["risk-1"]),evaluatedAt:"2026-07-22T07:00:00Z",auditRefs:Object.freeze(["audit-suspend"]),replayRef:"replay-suspend"}) as InstitutionalSuspensionEvaluation;
const policy=institutionalReinstatementAuthority.createPolicy({policyId:"reinstate-policy",governanceVersion:"gov-1",allowedModes:["LIFT_SELECTED","KEEP_SUSPENDED"],requireAllowedSuspension:true,requireRiskResolutionEvidence:true,requireIndependentReview:true,requireMonitoringPlan:true,requireAffectedPartyNotice:false,fullReinstatementAuthorized:false,claimReinstatementAuthorized:false,publicationReinstatementAuthorized:true,relianceReinstatementAuthorized:true,actionReinstatementAuthorized:false,requiredEvidenceRefs:["evidence-closure"],auditRefs:["audit-policy"],replayRef:"replay-policy",versionRefs:["version-1"]});
const allowed=institutionalReinstatementAuthority.evaluate({suspension,policy,mode:"LIFT_SELECTED",restoreScopes:["PUBLICATION","RELIANCE"],riskResolutionEvidenceRef:"risk-resolved",independentReviewRefs:["review-1"],monitoringPlanRef:"monitor-1",evidenceRefs:["evidence-closure"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-eval"],replayRef:"replay-eval"});
const review=institutionalReinstatementAuthority.evaluate({suspension,policy,mode:"LIFT_SELECTED",restoreScopes:["PUBLICATION"],evidenceRefs:["evidence-closure"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-review"],replayRef:"replay-review"});
const blocked=institutionalReinstatementAuthority.evaluate({suspension,policy,mode:"LIFT_SELECTED",restoreScopes:["ACTION"],riskResolutionEvidenceRef:"risk-resolved",independentReviewRefs:["review-1"],monitoringPlanRef:"monitor-1",evidenceRefs:["evidence-closure"],evaluatedAt:"2026-07-22T07:10:00Z",auditRefs:["audit-block"],replayRef:"replay-block"});
assert(allowed.decision==="ALLOW","Expected allowed reinstatement.");assert(allowed.resultingState==="PARTIALLY_REINSTATED","Expected partial reinstatement.");assert(review.decision==="REVIEW_REQUIRED","Expected review-required reinstatement.");assert(blocked.decision==="BLOCK","Expected blocked reinstatement.");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,blocked:blocked.decision,state:allowed.resultingState,message:"Institutional reinstatement authority conformance passed."},null,2));
