import fs from "node:fs";import os from "node:os";import path from "node:path";
function ok(v:unknown,m:string):asserts v{if(!v)throw new Error(m)}
async function main(){process.env.FURLONG_RUNTIME_STATE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),"furlong-replay-exec-"));process.env.EVIDENCE_REPLAY_SIGNING_SECRET="replay-test-secret";
 const store=await import("@/lib/property/officialEvidenceRuntimeStore");const capture=await import("@/lib/property/officialEvidenceGenerationCapture");const replay=await import("@/lib/property/officialEvidenceReplayExecutor");const registry=await import("@/lib/property/officialEvidenceRecomputationHandlerRegistry");const tax=await import("@/lib/property/ownershipCostModel");
 store.writeOfficialEvidenceRefreshState({sourceId:"parcel-tax-authority",snapshots:[],receipts:[],publishedVersion:"tax-v1"});store.writeOfficialEvidenceRefreshState({sourceId:"well-permit-authority",snapshots:[],receipts:[],publishedVersion:"well-v1"});
 const replayInput={price:250000,sellerCurrentAnnualTax:1200,currentTaxTransfersUnchanged:false,ownershipContext:{rates:{weekOf:"2026-07-23",rate30:6.2,rate15:null},taxContext:{medianAnnualTax:2200,medianHomeValue:200000,effectiveRatePct:1.1},electricity:null,hpi:null}};const output=tax.buildPostSaleTaxScenario({price:replayInput.price,sellerCurrentAnnualTax:replayInput.sellerCurrentAnnualTax,currentTaxTransfersUnchanged:false},replayInput.ownershipContext as any);
 capture.captureGeneratedEvidenceArtifact({kind:"tax-scenario",propertyId:"p4",artifactId:"tax-scenario:p4",generatedAt:"2026-07-25T17:10:00Z",replayInput,replayOutput:output});
 const handler=()=>({artifactHash:"a".repeat(64),dependencies:[],generatedAt:"2026-07-25T17:10:00Z",productionEvidence:true as const});const registration=registry.registerGovernedRecomputationHandler({handlerId:"tax-replay-v1",kind:"tax-scenario",sourcePath:"src/lib/property/ownershipCostModel.ts#buildPostSaleTaxScenario",status:"pending"},handler);
 let approvalBlocked=false;try{registry.decideGovernedRecomputationHandler({kind:"tax-scenario",decision:"APPROVE",reviewerId:"r1",reviewerName:"Reviewer",reason:"before proof"})}catch{approvalBlocked=true}ok(approvalBlocked,"Approval must be blocked before replay proof.");
 const attestation=replay.attestDeterministicReplay({artifactId:"tax-scenario:p4",handlerId:registration.handlerId,implementationHash:registration.implementationHash,at:"2026-07-25T17:11:00Z"});ok(attestation.matched,"Deterministic replay must match original output hash.");
 const approved=registry.decideGovernedRecomputationHandler({kind:"tax-scenario",decision:"APPROVE",reviewerId:"r1",reviewerName:"Reviewer",reason:"Replay proof matched exact implementation.",at:"2026-07-25T17:12:00Z"});ok(approved.status==="approved","Approval must succeed after matching proof.");
 console.log(JSON.stringify({ok:true,rule:"OFFICIAL-EVIDENCE-DETERMINISTIC-REPLAY-001",approvalBlocked,matched:attestation.matched,outputHash:attestation.actualOutputHash},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
