import assert from "node:assert/strict";
import type { InstitutionalLifecycleCycleReopeningEvaluation } from "@/lib/platform/institutionalLifecycleCycleReopeningAuthority";
import { createInstitutionalLifecycleCycleSuspensionPolicy, evaluateInstitutionalLifecycleCycleSuspension } from "@/lib/platform/institutionalLifecycleCycleSuspensionAuthority";
const reopening={cyclePolicyId:"cp",cycleId:"cycle-2",generation:2,reopeningPolicyId:"rp",canonicalObjectId:"case-1",decision:"ALLOW",resultingState:"REOPENED_RESTRICTED",replayRef:"replay-1"} as unknown as InstitutionalLifecycleCycleReopeningEvaluation;
const policy=createInstitutionalLifecycleCycleSuspensionPolicy({policyId:"sp",governanceVersion:"g1",allowedScopes:["CLAIM","FULL_MATTER"],requireRiskEvidence:true,requireHumanApproval:true,requireNotice:true,fullMatterSuspensionAuthorized:true,emergencySuspensionAuthorized:true,requiredEvidenceRefs:["e1"],auditRefs:["a1"],replayRef:"replay-1",versionRefs:["v1"]});
const base={reopening,policy,scopes:["CLAIM"] as const,emergency:false,approvalRefs:["approval-1"],riskEvidenceRef:"risk-1",noticeRef:"notice-1",evidenceRefs:["e1"],evaluatedAt:"2026-07-22T20:00:00Z",auditRefs:["a2"],replayRef:"replay-1"};
const allowed=evaluateInstitutionalLifecycleCycleSuspension(base);const review=evaluateInstitutionalLifecycleCycleSuspension({...base,noticeRef:null});const full=evaluateInstitutionalLifecycleCycleSuspension({...base,scopes:["FULL_MATTER"] as const});const blocked=evaluateInstitutionalLifecycleCycleSuspension({...base,replayRef:"replay-drift"});
assert.equal(allowed.decision,"ALLOW");assert.equal(review.decision,"REVIEW_REQUIRED");assert.equal(full.resultingState,"SUSPENDED");assert.equal(blocked.decision,"BLOCK");
console.log(JSON.stringify({ok:true,schemaVersion:allowed.schemaVersion,allowed:allowed.decision,review:review.decision,full:full.resultingState,blocked:blocked.decision,generation:allowed.generation,message:"Institutional lifecycle cycle suspension authority conformance passed."},null,2));
