CREATE TABLE IF NOT EXISTS customer_revenue_opportunity_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  revenue_opportunity_id text NOT NULL UNIQUE,
  customer_type text NOT NULL,
  geography_scope text NOT NULL,
  eligible_entity_types jsonb NOT NULL,
  product_or_service_category text NOT NULL,
  program_refs jsonb NOT NULL,
  estimated_revenue_range text,
  estimated_cost_range text,
  seasonality_profile text,
  compliance_constraints jsonb NOT NULL,
  age_restrictions jsonb,
  licensing_requirements jsonb,
  confidence_score integer NOT NULL DEFAULT 0,
  projection_basis text NOT NULL DEFAULT 'assumption',
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sellable_catalog_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id text NOT NULL UNIQUE,
  common_name text NOT NULL,
  scientific_name text,
  category text NOT NULL,
  allowed_regions jsonb NOT NULL,
  restricted_regions jsonb NOT NULL,
  suitable_climate_zones jsonb NOT NULL,
  soil_requirements jsonb,
  water_requirements jsonb,
  growing_season text,
  production_cycle text,
  licensing_requirements jsonb NOT NULL,
  program_eligibility_refs jsonb NOT NULL,
  prohibited_customer_types jsonb,
  minor_operator_constraints jsonb,
  market_price_refs jsonb NOT NULL,
  confidence_score integer NOT NULL DEFAULT 0,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS program_graph_nodes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id text NOT NULL UNIQUE,
  program_name text NOT NULL,
  sponsor_type text NOT NULL,
  geography_scope jsonb NOT NULL,
  eligible_customer_types jsonb NOT NULL,
  eligible_uses jsonb NOT NULL,
  prohibited_uses jsonb NOT NULL,
  age_constraints jsonb,
  entity_constraints jsonb,
  stacking_rules jsonb NOT NULL,
  conflict_rules jsonb NOT NULL,
  deadline_profile text,
  review_status text NOT NULL DEFAULT 'REVIEW_REQUIRED',
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS program_graph_edges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  edge_id text NOT NULL UNIQUE,
  from_program_id text NOT NULL,
  to_ref text NOT NULL,
  edge_type text NOT NULL,
  compatibility_status text NOT NULL,
  conflict_refs jsonb,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS program_stacking_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stacking_rule_id text NOT NULL UNIQUE,
  program_id text NOT NULL,
  compatible_program_refs jsonb NOT NULL,
  prohibited_program_refs jsonb NOT NULL,
  rule_basis text NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS program_conflict_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conflict_rule_id text NOT NULL UNIQUE,
  program_id text NOT NULL,
  conflict_type text NOT NULL,
  conflict_summary text NOT NULL,
  conflict_source_refs jsonb NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS marketplace_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  marketplace_item_id text NOT NULL UNIQUE,
  category text NOT NULL,
  manufacturer text,
  model text,
  condition text,
  price_range text,
  availability_region jsonb NOT NULL,
  vendor_refs jsonb NOT NULL,
  program_use_refs jsonb NOT NULL,
  revenue_opportunity_refs jsonb NOT NULL,
  price_basis text NOT NULL DEFAULT 'estimated-price',
  last_verified_at timestamptz,
  confidence_score integer NOT NULL DEFAULT 0,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supplier_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id text NOT NULL UNIQUE,
  supplier_name text NOT NULL,
  supplier_category text NOT NULL,
  availability_region jsonb NOT NULL,
  certification_status text NOT NULL,
  live_availability_blocked boolean NOT NULL DEFAULT true,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS marketplace_price_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  price_snapshot_id text NOT NULL UNIQUE,
  marketplace_item_id text NOT NULL,
  price_range text NOT NULL,
  price_basis text NOT NULL,
  effective_at timestamptz DEFAULT now(),
  freshness_status text NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS operating_cost_signals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cost_signal_id text NOT NULL UNIQUE,
  category text NOT NULL,
  geography_scope text NOT NULL,
  customer_type text NOT NULL,
  price_range text NOT NULL,
  price_basis text NOT NULL DEFAULT 'estimated-price',
  effective_at timestamptz DEFAULT now(),
  freshness_status text NOT NULL,
  volatility_score integer,
  uncertainty_classification text NOT NULL DEFAULT 'ESTIMATE',
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS market_signal_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  market_signal_id text NOT NULL UNIQUE,
  commodity_or_category text NOT NULL,
  geography_scope text NOT NULL,
  market_type text NOT NULL,
  current_price integer,
  price_unit text,
  trend_direction text,
  volatility_score integer,
  signal_basis text NOT NULL DEFAULT 'market-snapshot',
  fetched_at timestamptz DEFAULT now(),
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS market_signal_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  market_snapshot_id text NOT NULL UNIQUE,
  market_signal_id text NOT NULL,
  snapshot_type text NOT NULL,
  price_value integer,
  price_unit text,
  source_cadence text NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS geospatial_source_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  geo_source_id text NOT NULL UNIQUE,
  geo_source_name text NOT NULL,
  data_layer text NOT NULL,
  authority_tier text NOT NULL,
  update_cadence text NOT NULL,
  jurisdiction_scope jsonb NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS geo_suitability_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  geo_profile_id text NOT NULL UNIQUE,
  geography_scope text NOT NULL,
  parcel_refs jsonb,
  soil_refs jsonb NOT NULL,
  weather_refs jsonb NOT NULL,
  climate_refs jsonb NOT NULL,
  water_refs jsonb NOT NULL,
  infrastructure_refs jsonb NOT NULL,
  suitability_scores jsonb NOT NULL,
  weighting_assumptions jsonb NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS state_regulatory_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  state_record_id text NOT NULL UNIQUE,
  jurisdiction text NOT NULL,
  regulatory_domain text NOT NULL,
  affected_customer_types jsonb NOT NULL,
  affected_products_or_services jsonb NOT NULL,
  requirement_summary text NOT NULL,
  effective_at timestamptz,
  expiration_or_review_date timestamptz,
  legal_advice_blocked boolean NOT NULL DEFAULT true,
  conflict_review_required boolean NOT NULL DEFAULT true,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customer_type_eligibility_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id text NOT NULL UNIQUE,
  customer_type text NOT NULL,
  eligible_programs jsonb NOT NULL,
  eligible_revenue_categories jsonb NOT NULL,
  prohibited_or_restricted_categories jsonb NOT NULL,
  required_documents jsonb NOT NULL,
  licensing_constraints jsonb NOT NULL,
  age_constraints jsonb,
  geography_constraints jsonb NOT NULL,
  preliminary_only boolean NOT NULL DEFAULT true,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS advisory_fusion_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fusion_result_id text NOT NULL UNIQUE,
  customer_id text,
  customer_type text NOT NULL,
  geography_scope text NOT NULL,
  opportunity_refs jsonb NOT NULL,
  conflict_refs jsonb NOT NULL,
  assumptions jsonb NOT NULL,
  confidence_score integer NOT NULL DEFAULT 0,
  required_human_review boolean NOT NULL DEFAULT true,
  facts_estimates_forecasts_assumptions jsonb NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS revenue_claim_validation_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_validation_id text NOT NULL UNIQUE,
  subject_ref text NOT NULL,
  claim_text text NOT NULL,
  validation_status text NOT NULL,
  blocked_reasons jsonb NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS revenue_human_review_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  review_event_id text NOT NULL UNIQUE,
  subject_ref text NOT NULL,
  review_queue text NOT NULL,
  review_reason text NOT NULL,
  review_status text NOT NULL,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS revenue_source_lineage_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lineage_record_id text NOT NULL UNIQUE,
  subject_ref text NOT NULL,
  source_authority_refs jsonb NOT NULL,
  pricing_refs jsonb,
  program_rule_refs jsonb,
  assumption_refs jsonb,
  conflict_refs jsonb,
  governance_version text NOT NULL,
  classification_level text NOT NULL,
  replay_ref text NOT NULL,
  trace_id text,
  source_refs jsonb,
  replay_refs jsonb,
  claims_profile text NOT NULL DEFAULT 'advisory-only',
  human_review_required boolean NOT NULL DEFAULT true,
  production_blocked boolean NOT NULL DEFAULT true,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_revenue_opportunity_customer_type
  ON customer_revenue_opportunity_registry (customer_type);
CREATE INDEX IF NOT EXISTS idx_sellable_catalog_items_category
  ON sellable_catalog_items (category);
CREATE INDEX IF NOT EXISTS idx_program_graph_nodes_sponsor_type
  ON program_graph_nodes (sponsor_type);
CREATE INDEX IF NOT EXISTS idx_marketplace_items_category
  ON marketplace_items (category);
CREATE INDEX IF NOT EXISTS idx_operating_cost_signals_category
  ON operating_cost_signals (category);
CREATE INDEX IF NOT EXISTS idx_market_signal_registry_category
  ON market_signal_registry (commodity_or_category);
CREATE INDEX IF NOT EXISTS idx_state_regulatory_records_jurisdiction
  ON state_regulatory_records (jurisdiction);
CREATE INDEX IF NOT EXISTS idx_customer_type_eligibility_profiles_type
  ON customer_type_eligibility_profiles (customer_type);
