/**
 * hudPublicSafeGenerated — GENERATED FILE. Do not edit by hand.
 *
 * CLIENT-SAFE: public-safe projection only — NO exact address, NO lat/long.
 * Safe to bundle into the homepage map. Written by src/scripts/ingestHudReo.ts.
 *
 * Ingested at: 2026-06-10T23:39:59.517Z
 */

import type { PublicSafeProperty } from "./propertyTypes";

export const HUD_PUBLIC_SAFE_BY_STATE: Record<string, PublicSafeProperty> = {
  "AK": {
    "id": "hud-111-144877",
    "sourceId": "hud",
    "state": "AK",
    "county": "Unknown",
    "town": "North Pole",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in North Pole, AK — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "AL": {
    "id": "hud-011-625906",
    "sourceId": "hud",
    "state": "AL",
    "county": "Unknown",
    "town": "Alpine",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Alpine, AL — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "AR": {
    "id": "hud-031-566104",
    "sourceId": "hud",
    "state": "AR",
    "county": "Unknown",
    "town": "Summers",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Summers, AR — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "AZ": {
    "id": "hud-022-304274",
    "sourceId": "hud",
    "state": "AZ",
    "county": "Unknown",
    "town": "Tucson",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Tucson, AZ — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "CA": {
    "id": "hud-048-434197",
    "sourceId": "hud",
    "state": "CA",
    "county": "Unknown",
    "town": "Banning",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Banning, CA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "CO": {
    "id": "hud-052-331338",
    "sourceId": "hud",
    "state": "CO",
    "county": "Unknown",
    "town": "Alamosa",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Alamosa, CO — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "CT": {
    "id": "hud-061-366631",
    "sourceId": "hud",
    "state": "CT",
    "county": "Unknown",
    "town": "East Haven",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in East Haven, CT — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "DC": {
    "id": "hud-081-083376",
    "sourceId": "hud",
    "state": "DC",
    "county": "Unknown",
    "town": "Washington",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Washington, DC — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "FL": {
    "id": "hud-091-534963",
    "sourceId": "hud",
    "state": "FL",
    "county": "Unknown",
    "town": "Hawthorne",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Hawthorne, FL — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "GA": {
    "id": "hud-106-265176",
    "sourceId": "hud",
    "state": "GA",
    "county": "Unknown",
    "town": "Hephzibah",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Hephzibah, GA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "IA": {
    "id": "hud-161-404005",
    "sourceId": "hud",
    "state": "IA",
    "county": "Unknown",
    "town": "Long Grove",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Long Grove, IA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "ID": {
    "id": "hud-121-396539",
    "sourceId": "hud",
    "state": "ID",
    "county": "Unknown",
    "town": "Weiser",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Weiser, ID — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "IL": {
    "id": "hud-131-984976",
    "sourceId": "hud",
    "state": "IL",
    "county": "Unknown",
    "town": "Chicago",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Chicago, IL — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "IN": {
    "id": "hud-156-351402",
    "sourceId": "hud",
    "state": "IN",
    "county": "Unknown",
    "town": "Lowell",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Lowell, IN — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "KS": {
    "id": "hud-181-311255",
    "sourceId": "hud",
    "state": "KS",
    "county": "Unknown",
    "town": "Galva",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Galva, KS — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "KY": {
    "id": "hud-201-644970",
    "sourceId": "hud",
    "state": "KY",
    "county": "Unknown",
    "town": "Bardstown",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Bardstown, KY — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "LA": {
    "id": "hud-221-573954",
    "sourceId": "hud",
    "state": "LA",
    "county": "Unknown",
    "town": "Marrero",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Marrero, LA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MA": {
    "id": "hud-251-527089",
    "sourceId": "hud",
    "state": "MA",
    "county": "Unknown",
    "town": "Chicopee",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Chicopee, MA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MD": {
    "id": "hud-244-206516",
    "sourceId": "hud",
    "state": "MD",
    "county": "Unknown",
    "town": "Halethorpe",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Halethorpe, MD — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MI": {
    "id": "hud-263-576346",
    "sourceId": "hud",
    "state": "MI",
    "county": "Unknown",
    "town": "Newberry",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Newberry, MI — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MN": {
    "id": "hud-277-008106",
    "sourceId": "hud",
    "state": "MN",
    "county": "Unknown",
    "town": "Saint Paul",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Saint Paul, MN — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MO": {
    "id": "hud-291-554530",
    "sourceId": "hud",
    "state": "MO",
    "county": "Unknown",
    "town": "Niangua",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Niangua, MO — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MS": {
    "id": "hud-281-513217",
    "sourceId": "hud",
    "state": "MS",
    "county": "Unknown",
    "town": "De Kalb",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in De Kalb, MS — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "MT": {
    "id": "hud-311-258013",
    "sourceId": "hud",
    "state": "MT",
    "county": "Unknown",
    "town": "Billings",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Billings, MT — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "NC": {
    "id": "hud-387-052116",
    "sourceId": "hud",
    "state": "NC",
    "county": "Unknown",
    "town": "Roanoke Rapids",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Roanoke Rapids, NC — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "ND": {
    "id": "hud-401-154702",
    "sourceId": "hud",
    "state": "ND",
    "county": "Unknown",
    "town": "Williston",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Williston, ND — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "NJ": {
    "id": "hud-352-539965",
    "sourceId": "hud",
    "state": "NJ",
    "county": "Unknown",
    "town": "Rockaway",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Rockaway, NJ — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "NM": {
    "id": "hud-361-440938",
    "sourceId": "hud",
    "state": "NM",
    "county": "Unknown",
    "town": "Artesia",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Artesia, NM — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "NV": {
    "id": "hud-331-192165",
    "sourceId": "hud",
    "state": "NV",
    "county": "Unknown",
    "town": "Ely",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Ely, NV — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "NY": {
    "id": "hud-372-219162",
    "sourceId": "hud",
    "state": "NY",
    "county": "Unknown",
    "town": "Campbell",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Campbell, NY — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "OH": {
    "id": "hud-411-657526",
    "sourceId": "hud",
    "state": "OH",
    "county": "Unknown",
    "town": "Lebanon",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Lebanon, OH — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "OK": {
    "id": "hud-421-493043",
    "sourceId": "hud",
    "state": "OK",
    "county": "Unknown",
    "town": "Mountain View",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Mountain View, OK — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "OR": {
    "id": "hud-431-683224",
    "sourceId": "hud",
    "state": "OR",
    "county": "Unknown",
    "town": "Ontario",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Ontario, OR — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "PA": {
    "id": "hud-441-807901",
    "sourceId": "hud",
    "state": "PA",
    "county": "Unknown",
    "town": "Tremont",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Tremont, PA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "PR": {
    "id": "hud-501-696388",
    "sourceId": "hud",
    "state": "PR",
    "county": "Unknown",
    "town": "San Juan",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in San Juan, PR — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "SC": {
    "id": "hud-461-777412",
    "sourceId": "hud",
    "state": "SC",
    "county": "Unknown",
    "town": "Beaufort",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Beaufort, SC — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "SD": {
    "id": "hud-471-146760",
    "sourceId": "hud",
    "state": "SD",
    "county": "Unknown",
    "town": "Aberdeen",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Aberdeen, SD — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "TN": {
    "id": "hud-483-631541",
    "sourceId": "hud",
    "state": "TN",
    "county": "Unknown",
    "town": "Mount Pleasant",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Mount Pleasant, TN — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "TX": {
    "id": "hud-494-483453",
    "sourceId": "hud",
    "state": "TX",
    "county": "Unknown",
    "town": "Snyder",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Snyder, TX — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "VA": {
    "id": "hud-544-351944",
    "sourceId": "hud",
    "state": "VA",
    "county": "Unknown",
    "town": "Radford",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Radford, VA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "WA": {
    "id": "hud-566-301243",
    "sourceId": "hud",
    "state": "WA",
    "county": "Unknown",
    "town": "Port Orchard",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Port Orchard, WA — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "WI": {
    "id": "hud-581-459960",
    "sourceId": "hud",
    "state": "WI",
    "county": "Unknown",
    "town": "Milwaukee",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Milwaukee, WI — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "WV": {
    "id": "hud-571-158534",
    "sourceId": "hud",
    "state": "WV",
    "county": "Unknown",
    "town": "Wheeling",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Wheeling, WV — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  },
  "WY": {
    "id": "hud-591-137289",
    "sourceId": "hud",
    "state": "WY",
    "county": "Unknown",
    "town": "Thermopolis",
    "propertyType": "home",
    "acreageBand": "Acreage not specified",
    "priceBand": "Price on request",
    "whyMayFit": "HUD-owned (FHA) home in Thermopolis, WY — a current government listing; providers can help you explore financing.",
    "sourceCitation": "Source: U.S. HUD — FHA (HUD Home Store)",
    "asOf": "2026-06-10T23:39:59.517Z",
    "isCurrent": true,
    "vintageStamp": "current listing"
  }
};
