/**
 * listhubListingsGenerated — GENERATED FILE. Do not edit by hand.
 *
 * ListHub Syndication API snapshot (RESO Web API; publishers store data on
 * their own systems per ListHub docs). Re-run: npm run ingest:listhub
 *
 * SANDBOX RUN — fake data excluded by the hard guard; counts/structure only.
 * Display requires the publisher agreement + Module 23 + Module 22. Snapshot only.
 */

export const LISTHUB_PROVENANCE = {
  fetchedAt: "2026-07-18T03:14:41.917Z",
  sandbox: true,
  source: "ListHub Syndication API (api.listhub.com/odata/Property)",
  pulled: 600,
  committed: 0,
  byType: {
  "Other / Farm": 7,
  "Residential Lease / Multi Family": 4,
  "Commercial Sale / Mobile Home": 2,
  "Other / Single Family Residence": 9,
  "Commercial Lease / Mobile Home": 5,
  "Other / Cabin": 4,
  "Other / Other": 7,
  "Residential Multi Family / Manufactured Home": 5,
  "Residential Common Interest / Apartment": 3,
  "Farm / Stock Cooperative": 4,
  "Other / Own Your": 3,
  "Commercial Lease / Cabin": 2,
  "Farm / Single Family Residence": 3,
  "Residential / Townhouse": 1,
  "Residential Multi Family / Townhouse": 3,
  "Farm / Duplex": 7,
  "Commercial Lease / Own Your": 6,
  "Residential Lease / Triplex": 4,
  "Residential Lease / Single Family Residence": 2,
  "Residential Lease / Manufactured Home": 1,
  "Residential Lease / Mobile Home": 7,
  "Residential Common Interest / Boat Slip": 2,
  "Commercial Sale / Triplex": 6,
  "Residential Multi Family / Boat Slip": 3,
  "Residential Multi Family / Apartment": 3,
  "Residential Lease / Farm": 4,
  "Residential Lease / Quadruplex": 2,
  "Residential / Timeshare": 4,
  "Residential Lease / Duplex": 3,
  "Residential Lease / Own Your": 4,
  "Farm / Farm": 1,
  "Commercial Sale / Duplex": 5,
  "Residential Common Interest / Timeshare": 5,
  "Residential Common Interest / Stock Cooperative": 5,
  "Land / Deeded Parking": 3,
  "Residential / Own Your": 3,
  "Commercial Lease / Apartment": 2,
  "Residential Lease / Other": 4,
  "Residential Common Interest / Triplex": 3,
  "Commercial Lease / Timeshare": 4,
  "Other / Duplex": 2,
  "Land / Stock Cooperative": 2,
  "Residential / Deeded Parking": 3,
  "Residential Multi Family / Stock Cooperative": 7,
  "Residential / Farm": 6,
  "Residential / Cabin": 5,
  "Residential / Apartment": 4,
  "Commercial Sale / Manufactured Home": 6,
  "Other / Apartment": 3,
  "Residential Common Interest / Deeded Parking": 3,
  "Residential / Boat Slip": 2,
  "Commercial Sale / Cabin": 3,
  "Commercial Lease / Farm": 6,
  "Commercial Sale / Multi Family": 4,
  "Commercial Sale / Deeded Parking": 2,
  "Land / Mobile Home": 3,
  "Residential Common Interest / Duplex": 4,
  "Commercial Lease / Single Family Residence": 3,
  "Commercial Lease / Triplex": 6,
  "Land / Duplex": 5,
  "Land / Timeshare": 1,
  "Residential Lease / Stock Cooperative": 7,
  "Residential Multi Family / Quadruplex": 8,
  "Other / Triplex": 4,
  "Residential Lease / Cabin": 3,
  "Other / Quadruplex": 3,
  "Farm / Multi Family": 4,
  "Commercial Sale / Single Family Residence": 3,
  "Farm / Townhouse": 4,
  "Other / Boat Slip": 6,
  "Residential Multi Family / Deeded Parking": 3,
  "Land / Farm": 6,
  "Commercial Sale / Other": 3,
  "Land / Cabin": 2,
  "Residential Multi Family / Farm": 5,
  "Commercial Sale / Stock Cooperative": 3,
  "Farm / Other": 3,
  "Residential / Triplex": 6,
  "Residential Lease / Boat Slip": 4,
  "Commercial Lease / Deeded Parking": 4,
  "Residential Multi Family / Other": 4,
  "Residential Multi Family / Single Family Residence": 9,
  "Commercial Sale / Quadruplex": 3,
  "Residential Multi Family / Cabin": 2,
  "Commercial Lease / Manufactured Home": 1,
  "Commercial Sale / Timeshare": 3,
  "Residential Common Interest / Mobile Home": 3,
  "Land / Triplex": 6,
  "Residential Common Interest / Multi Family": 4,
  "Commercial Lease / Other": 11,
  "Residential Lease / Condominium": 8,
  "Residential / Multi Family": 3,
  "Land / Own Your": 3,
  "Commercial Lease / Townhouse": 5,
  "Commercial Sale / Apartment": 1,
  "Residential Lease / Townhouse": 1,
  "Other / Manufactured Home": 2,
  "Other / Multi Family": 6,
  "Farm / Manufactured Home": 7,
  "Land / Multi Family": 3,
  "Farm / Timeshare": 4,
  "Residential Common Interest / Cabin": 5,
  "Farm / Cabin": 3,
  "Farm / Condominium": 7,
  "Commercial Lease / Duplex": 5,
  "Other / Mobile Home": 6,
  "Land / Condominium": 5,
  "Other / Stock Cooperative": 1,
  "Residential / Other": 3,
  "Land / Apartment": 4,
  "Residential Multi Family / Own Your": 4,
  "Commercial Sale / Condominium": 8,
  "Residential Multi Family / Condominium": 2,
  "Farm / Deeded Parking": 7,
  "Residential Common Interest / Farm": 5,
  "Land / Single Family Residence": 1,
  "Residential Multi Family / Triplex": 5,
  "Commercial Sale / Townhouse": 4,
  "Commercial Sale / Farm": 4,
  "Commercial Sale / Boat Slip": 3,
  "Commercial Sale / Own Your": 3,
  "Farm / Own Your": 2,
  "Residential Common Interest / Townhouse": 3,
  "Land / Townhouse": 5,
  "Commercial Lease / Quadruplex": 4,
  "Residential / Stock Cooperative": 5,
  "Other / Deeded Parking": 4,
  "Farm / Quadruplex": 3,
  "Commercial Lease / Condominium": 4,
  "Commercial Lease / Boat Slip": 1,
  "Commercial Lease / Multi Family": 2,
  "Residential Multi Family / Multi Family": 4,
  "Farm / Boat Slip": 1,
  "Land / Other": 3,
  "Residential Common Interest / Own Your": 3,
  "Land / Boat Slip": 5,
  "Residential Lease / Apartment": 5,
  "Residential Common Interest / Other": 4,
  "Residential Multi Family / Duplex": 2,
  "Other / Townhouse": 5,
  "Farm / Apartment": 4,
  "Farm / Mobile Home": 2,
  "Residential Multi Family / Mobile Home": 4,
  "Residential / Duplex": 4,
  "Residential Multi Family / Timeshare": 1,
  "Residential Common Interest / Condominium": 2,
  "Other / Timeshare": 3,
  "Residential / Manufactured Home": 3,
  "Commercial Lease / Stock Cooperative": 2,
  "Farm / Triplex": 1,
  "Land / Manufactured Home": 3,
  "Residential / Single Family Residence": 2,
  "Residential / Mobile Home": 3,
  "Residential Lease / Timeshare": 1,
  "Residential Common Interest / Quadruplex": 2,
  "Residential Common Interest / Single Family Residence": 3,
  "Other / Condominium": 1,
  "Residential / Quadruplex": 2,
  "Residential Common Interest / Manufactured Home": 2
},
} as const;

export interface ListhubListing {
  listingKey: string;
  propertyType: string | null;
  propertySubType: string | null;
  standardStatus: string | null;
  listPrice: number | null;
  city: string | null;
  stateOrProvince: string | null;
  postalCode: string | null;
  county: string | null;
  unparsedAddress: string | null;
  lotSizeAcres: number | null;
  livingArea: number | null;
  bedroomsTotal: number | null;
  yearBuilt: number | null;
  latitude: number | null;
  longitude: number | null;
  listingUrl: string | null;
  modificationTimestamp: string | null;
}

export const LISTHUB_LISTINGS: ListhubListing[] = JSON.parse("[]");
