export const productionDomainCutoverAuthorizationVersion = "p5-b10-domain-cutover-authorization-v1";

export const productionDomainCutoverAuthorizationInventory = [
  "FURLONGPATHWAYS_APEX",
  "FURLONGPATHWAYS_WWW",
  "FURLONGHUB_APEX",
  "FURLONGHUB_WWW",
  "PUBLIC_API_EDGE",
  "BORROWER_PORTAL_EDGE",
].map((surfaceId) => ({
  surfaceId,
  domainOwnershipVerifiedRequired: true,
  dnsZoneAuthorityVerifiedRequired: true,
  exactDnsChangeSetRequired: true,
  ttlReductionPlanRequired: true,
  managedCertificateRequired: true,
  certificateIssuanceVerifiedRequired: true,
  tlsPolicyRequired: true,
  cdnPolicyRequired: true,
  wafPolicyRequired: true,
  rateLimitPolicyRequired: true,
  healthProbeRequired: true,
  monitoringAndAlertingRequired: true,
  cutoverRunbookRequired: true,
  rollbackRunbookRequired: true,
  rollbackTargetRequired: true,
  rollbackDrillRequired: true,
  incidentBridgeRequired: true,
  changeWindowRequired: true,
  qualifiedReleaseManagerRequired: true,
  releaseBoardApprovalRequired: true,
  finalLaunchHoldReleaseRequired: true,
  dnsCutoverApproved: false,
  certificateActivationApproved: false,
  publicExposureApproved: false,
  finalLaunchHoldReleased: false,
}));

export const productionDomainCutoverAuthorization = {
  blockerId: "P5-B10",
  ownerRole: "QUALIFIED_RELEASE_MANAGER",
  securityApproverRole: "SECURITY_AUTHORITY",
  releaseBoardRequired: true,
  approvalRequired: true,
  approvalGranted: false,
  dnsCutoverApproved: false,
  certificateActivationApproved: false,
  publicProductionExposureApproved: false,
  rollbackDrillApproved: false,
  finalLaunchHoldReleased: false,
  productionAuthorized: false,
} as const;
