import { getServerSession } from "next-auth";
import { revalidatePath } from "next/cache";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { canApproveSourceLegal, operatorByEmail } from "@/lib/auth/operatorRegistry";
import { attestDeterministicReplay, listReplayAttestations } from "@/lib/property/officialEvidenceReplayExecutor";
import { listEvidenceReplayPackets } from "@/lib/property/officialEvidenceReplayPacketStore";
import { decideGovernedRecomputationHandler, listGovernedRecomputationHandlerReceipts, listGovernedRecomputationHandlers } from "@/lib/property/officialEvidenceRecomputationHandlerRegistry";
import type { DownstreamArtifactKind } from "@/lib/property/officialEvidenceDownstreamInvalidation";

async function runReplay(formData:FormData):Promise<void>{"use server";const session=await getServerSession(authOptions);const email=session?.user?.email??null;if(!canApproveSourceLegal(email))throw new Error("Module 45 source/legal authority is required.");const kind=String(formData.get("kind")) as DownstreamArtifactKind;const artifactId=String(formData.get("artifactId")??"");const registration=[...listGovernedRecomputationHandlers()].reverse().find(r=>r.kind===kind);if(!registration)throw new Error("No handler registration exists for this artifact class.");attestDeterministicReplay({artifactId,handlerId:registration.handlerId,implementationHash:registration.implementationHash});revalidatePath("/internal/evidence-recomputation");}
async function decide(formData:FormData):Promise<void>{"use server";const session=await getServerSession(authOptions);const email=session?.user?.email??null;if(!canApproveSourceLegal(email))throw new Error("Module 45 source/legal authority is required.");const operator=operatorByEmail(email)!;const kind=String(formData.get("kind")) as DownstreamArtifactKind;const decision=String(formData.get("decision")) as "APPROVE"|"SUSPEND";const reason=String(formData.get("reason")??"").trim();if(!reason)throw new Error("A review reason is required.");decideGovernedRecomputationHandler({kind,decision,reviewerId:operator.id,reviewerName:operator.name,reason});revalidatePath("/internal/evidence-recomputation");}
export default async function EvidenceRecomputationPage(){const session=await getServerSession(authOptions);const mayApprove=canApproveSourceLegal(session?.user?.email??null);const registrations=listGovernedRecomputationHandlers();const latest=[...registrations].reverse().filter((r,i,a)=>a.findIndex(x=>x.kind===r.kind)===i);const packets=listEvidenceReplayPackets().slice().reverse();const attestations=listReplayAttestations().slice().reverse();const receipts=listGovernedRecomputationHandlerReceipts().slice(-30).reverse();return <main style={{maxWidth:1120,margin:"0 auto",padding:"28px 24px 80px",display:"grid",gap:18}}><header><div style={{fontSize:12,fontWeight:800,color:"#9a3412"}}>INTERNAL · MODULE 45 RECOMPUTATION REVIEW</div><h1>Evidence recomputation approvals</h1><p>Approval requires a successful deterministic replay attestation for the exact handler implementation hash. No attestation, no approval.</p></header>{latest.map(r=><section key={r.kind} style={{padding:20,border:"1px solid #d7deea",borderRadius:12,display:"grid",gap:8}}><strong>{r.kind} · {r.handlerId}</strong><div>Status: <b>{r.status}</b></div><code style={{overflowWrap:"anywhere"}}>Implementation {r.implementationHash}</code><div>Source: {r.sourcePath}</div>{mayApprove&&<form action={decide} style={{display:"grid",gap:8,maxWidth:700}}><input type="hidden" name="kind" value={r.kind}/><textarea name="reason" required placeholder="Human review reason"/><div style={{display:"flex",gap:8}}><button name="decision" value="APPROVE">Approve exact implementation</button><button name="decision" value="SUSPEND">Suspend</button></div></form>}</section>)}<section style={{padding:20,border:"1px solid #d7deea",borderRadius:12}}><h2>Signed replay packets</h2>{packets.length===0?<p>No replay packets are available yet.</p>:packets.map(p=><div key={p.packetId} style={{padding:"10px 0",borderTop:"1px solid #e2e8f0"}}><b>{p.kind}</b> · {p.artifactId}<br/><code>{p.outputHash}</code>{mayApprove&&<form action={runReplay} style={{marginTop:8}}><input type="hidden" name="kind" value={p.kind}/><input type="hidden" name="artifactId" value={p.artifactId}/><button>Run deterministic replay</button></form>}</div>)}</section><section style={{padding:20,border:"1px solid #d7deea",borderRadius:12}}><h2>Replay attestations</h2>{attestations.map(a=><div key={a.attestationId} style={{padding:"10px 0",borderTop:"1px solid #e2e8f0"}}><b>{a.matched?"MATCH":"FAIL"}</b> · {a.kind} · {a.artifactId} · {a.executedAt}<br/><code>{a.implementationHash}</code>{a.reasons.length?<><br/>{a.reasons.join(", ")}</>:null}</div>)}</section><section style={{padding:20,border:"1px solid #d7deea",borderRadius:12}}><h2>Approval receipts</h2>{receipts.map(r=><div key={r.receiptId} style={{padding:"8px 0",borderTop:"1px solid #e2e8f0"}}><b>{r.decision}</b> · {r.kind} · {r.actorName} · {r.at}<br/>{r.reason}</div>)}</section></main>;}
