import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy | Furlong" };

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section style={{ marginTop: 32 }}><h2 style={{ fontSize: 24, lineHeight: 1.2 }}>{title}</h2>{children}</section>
);

export default function PrivacyPolicyPage() {
  return <main style={{maxWidth:860,margin:"0 auto",padding:"48px 24px 80px",lineHeight:1.7,color:"#162033"}}>
    <p style={{fontWeight:800,letterSpacing:".08em",fontSize:12}}>ARES FARMS INC. / FURLONG</p>
    <h1 style={{fontSize:42,lineHeight:1.1}}>Privacy Policy</h1>
    <p><strong>Version 1.1</strong> · Effective and last reviewed August 8, 2026 · Reviewed at least annually and on material legal, provider, product, security, or data-practice change.</p>
    <p><strong>Core privacy rule:</strong> Furlong collects, uses, retains, and shares personal information only for disclosed and authorized purposes. Furlong does not sell personal information and does not use private financial information to build advertising profiles.</p>

    <Section title="1. Scope and role of Furlong"><p>This policy applies to personal information processed through Furlong public and authenticated application surfaces, including Compass to Capital financing workflows, borrower and professional workflows, documents and signatures, Plaid-connected financial accounts, payments, identity-verification evidence, and supporting security and audit systems.</p><p>Furlong is a governed coordination and information platform. It is not a bank, lender, credit bureau, or government agency and does not itself make regulated credit decisions or issue government approvals.</p></Section>
    <Section title="2. Information we may process"><p>Depending on the workflow you choose, Furlong may process identity and contact information; Plaid-authorized financial-account information; uploaded or lender-provided documents; signature and consent evidence; Stripe transaction and connected-account references; professional credential evidence; and access, device/session, security, and audit events.</p></Section>
    <Section title="3. Plaid and connected financial accounts"><p>If you choose to connect a financial account, Plaid processes the connection and provides only the information authorized for the stated workflow. Furlong does not receive or store your online-banking password. Plaid access tokens and Plaid-derived consumer data are restricted financial information.</p><p>Plaid data may be persisted only through Furlong&apos;s ciphertext-only Plaid secure store. Sensitive Plaid data is encrypted before database persistence using AES-256-GCM application-layer encryption. Plaintext access tokens are not written to database columns, browser storage, audit payloads, or application logs.</p><p>When a linked account is disconnected, permission is withdrawn, or the financing purpose no longer requires access, Furlong revokes provider access and cryptographically purges eligible local encrypted records unless a documented legal, regulatory, fraud, dispute, security, forensic, or audit hold applies.</p></Section>
    <Section title="4. Consent, authorization, and transparency"><p>Furlong uses versioned, purpose-specific consent records. Sensitive financial-account access requires explicit consent before Plaid Link or equivalent connectivity is used. Consequential document sharing and dispatch workflows require action-specific authorization for the identified package, recipient, and purpose.</p><p>Consent and authorization evidence records the applicable version, timestamp, subject/deal references, and tamper-evident audit evidence. Consumers may withdraw future access or disconnect a linked account, subject to lawful retention obligations.</p></Section>
    <Section title="5. Identity, authentication, and professional access"><p>Furlong uses layered identity and access controls appropriate to the sensitivity of the action. Privileged access requires phishing-resistant multi-factor authentication using passkeys. Access is role- and purpose-bound, and sensitive actions may require fresh or step-up verification.</p><p>Where identity-verification providers are enabled, Furlong retains minimum verification evidence and provider references rather than unnecessarily copying raw identity documents. Professional credentials are separately verified against appropriate credential authorities or governed review procedures.</p></Section>
    <Section title="6. Documents, signatures, and provenance"><p>Uploaded documents are subject to governed intake controls, including malware/quarantine scanning before release to normal workflows. Furlong records chain-of-custody and integrity evidence such as exact-byte cryptographic hashes, source references, timestamps, consent or attestation evidence, and workflow events.</p><p>Cryptographic hashes prove integrity and custody of specific bytes; they do not by themselves prove factual truth. Furlong therefore distinguishes direct-source, corroborated, forensic-consistency, review-required, discrepancy, and rejected authenticity states where applicable.</p></Section>
    <Section title="7. Payments and financial transactions"><p>Payment processing is performed through governed service providers such as Stripe. Furlong stores transaction and connected-account references, authorization/risk evidence, and limited payment metadata needed for reconciliation and audit rather than raw card or bank credentials.</p></Section>
    <Section title="8. How information is used and shared"><p>Furlong uses personal information to provide authorized workflows; authenticate users; organize financing, property, and document information; connect authorized parties; prevent fraud; maintain auditability; comply with lawful obligations; and improve reliability and security.</p><p>Information is shared only with providers, lenders, professionals, counterparties, or authorities when necessary for an authorized workflow, disclosed operational purpose, or lawful requirement. Furlong prefers references and minimum-necessary evidence over unnecessary duplication.</p></Section>
    <Section title="9. Security safeguards"><p>Furlong uses encrypted transport and storage, least-privilege access, phishing-resistant MFA for privileged access, protected secret management, malware scanning, tamper-evident audit chains, vulnerability/dependency/secret/container/code scanning, security logging, and governed incident-response controls. Client/server traffic is required to use HTTPS/TLS, and restricted Plaid data receives AES-256-GCM application-layer encryption before persistence.</p></Section>
    <Section title="10. Retention and disposal"><p>Personal information is retained only for an active, disclosed purpose and any documented legal, regulatory, dispute, fraud, security, forensic, or audit hold. Indefinite retention is prohibited. Deletion requests involving regulated, signed, disputed, lender-relied-upon, security, or legally significant records are human-reviewed. Where underlying content may be deleted, minimum-necessary non-secret process evidence may be preserved to prove what occurred.</p></Section>
    <Section title="11. Your choices and data rights"><p>Subject to applicable law and legitimate retention obligations, you may request access, export, correction, restriction, deletion, or human review of personal information Furlong holds about you. You may withdraw future consent, disconnect financial accounts, and request correction of inaccurate information.</p></Section>
    <Section title="12. Cookies, local storage, and session data"><p>Furlong may use strictly necessary cookies or equivalent session mechanisms for authentication, security, workflow continuity, and preferences. Sensitive Plaid access tokens and raw financial-account credentials are not stored in browser local storage. Private financial data is not used for behavioral advertising.</p></Section>
    <Section title="13. Service providers and subprocessors"><p>Furlong may use providers for defined functions such as financial-account connectivity, identity verification, payment processing, cloud hosting, secure storage, communications, malware scanning, and credential/source verification. Provider changes do not remove Furlong&apos;s requirements for purpose limitation, minimum-necessary processing, security, auditability, and consumer rights.</p></Section>
    <Section title="14. Automated processing and credit decisions"><p>Furlong may use rules, calculations, and artificial intelligence to organize information, explain pathways, identify possibilities, surface inconsistencies, or support human review. Furlong does not itself make regulated credit decisions, determine government eligibility as an authoritative agency, or replace the independent judgment of a lender, licensed professional, or government authority.</p></Section>
    <Section title="15. Changes to this policy"><p>Material changes are versioned and reviewed before becoming effective. Related executable controls, consent language, data-rights procedures, and retention rules are expected to remain aligned with the published policy.</p></Section>
    <Section title="16. Contact and privacy requests"><p>Privacy and data-rights requests may be submitted through the Furlong data-rights process or the organization&apos;s authorized support/contact channel. Requests are authenticated as appropriate before personal information is disclosed, corrected, exported, restricted, or deleted.</p></Section>
  </main>;
}
