import { getServerSession } from "next-auth";
import { revalidatePath } from "next/cache";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { canApproveSourceLegal, operatorByEmail } from "@/lib/auth/operatorRegistry";
import { readOfficialEvidenceQuarantine } from "@/lib/property/officialEvidenceQuarantineStore";
import { decideEvidenceQuarantine, type QuarantineDecision } from "@/lib/property/officialEvidenceQuarantineResolution";

async function decide(formData:FormData):Promise<void>{ "use server"; const session=await getServerSession(authOptions); const email=session?.user?.email??null; if(!canApproveSourceLegal(email)) throw new Error("Module 45 source/legal authority is required."); const operator=operatorByEmail(email)!; const quarantineId=String(formData.get("quarantineId")??""); const decision=String(formData.get("decision")??"") as QuarantineDecision; const reason=String(formData.get("reason")??"").trim(); if(!["ACKNOWLEDGE","REMEDIATION","REVERIFY"].includes(decision)) throw new Error("Invalid quarantine decision."); decideEvidenceQuarantine({quarantineId,decision,actorId:operator.id,actorName:operator.name,reason}); revalidatePath("/internal/evidence-quarantine"); }
export default async function EvidenceQuarantinePage(){ const session=await getServerSession(authOptions); const email=session?.user?.email??null; const mayDecide=canApproveSourceLegal(email); const records=readOfficialEvidenceQuarantine().slice().reverse(); return <main style={{maxWidth:1100,margin:"0 auto",padding:"28px 24px 80px",display:"grid",gap:18}}>
<header><div style={{fontSize:12,fontWeight:800,color:"#9a3412",textTransform:"uppercase"}}>Internal · governed diagnostics</div><h1>Evidence provenance quarantine</h1><p>Operators may acknowledge and document remediation. Release is automatic only after independent provenance verification passes; there is no manual override.</p></header>
{records.length===0?<section style={{padding:20,border:"1px solid #d7deea",borderRadius:12}}>No quarantined evidence.</section>:records.map(r=><section key={r.quarantineId} style={{padding:20,border:"1px solid #f59e0b",borderRadius:12,display:"grid",gap:8}}>
<strong>{r.sourceId} · {r.sourceVersion}</strong><span>Detected {r.detectedAt} · status <b>{r.status}</b></span><span>Connector {r.connectorId??"unknown"} · parser {r.parserVersion??"unknown"}</span><code style={{overflowWrap:"anywhere"}}>Implementation {r.implementationHash??"unknown"}</code><div><strong>Failure reasons:</strong> {r.reasons.join(", ")}</div><div>Refresh receipt: {r.receiptId??"missing"}</div>
{mayDecide&&r.status!=="released"&&<form action={decide} style={{display:"grid",gap:8,maxWidth:700}}><input type="hidden" name="quarantineId" value={r.quarantineId}/><textarea name="reason" required placeholder="Investigation or remediation note"/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button name="decision" value="ACKNOWLEDGE">Acknowledge</button><button name="decision" value="REMEDIATION">Record remediation</button><button name="decision" value="REVERIFY">Reverify and release if valid</button></div></form>}
<details><summary>Resolution history ({r.events.length})</summary>{r.events.slice().reverse().map(e=><div key={e.eventId} style={{padding:"8px 0",borderTop:"1px solid #e2e8f0"}}><b>{e.action}</b> · {e.actorName} · {e.at}<br/>{e.reason}{e.verificationReasons?.length?<><br/>Verification: {e.verificationReasons.join(", ")}</>:null}</div>)}</details>
</section>)}</main>; }
