import { ClassificationLevel } from "@/lib/runtime/classificationRuntime";

import { moduleManifests } from "@/lib/modules/moduleRegistry";

/**
 * Cross-Module Event Contract Registry
 *
 * Master Volume Governance:
 * - Vol I: prevents implicit module coupling from replacing accountable
 *   constitutional authority.
 * - Vol II: keeps regulated workflows tied to explicit human-review and
 *   disclosure boundaries.
 * - Vol III: supports replay-safe, deterministic module integration.
 * - Vol III-B: exposes runtime observability and event provenance.
 * - Vol IV: supports operational handoff and recovery.
 * - Vol V: preserves source authority, classification, replay, and controlled
 *   disclosure for cross-module events.
 */

export type EventContract = {
  eventType: string;
  producerModuleId: string;
  consumerModuleIds: string[];
  classificationLevel: ClassificationLevel;
  replayRequired: boolean;
  publicSurfaceAllowed: boolean;
  productionBlocked: boolean;
  payloadFields: string[];
  purpose: string;
};

export const eventContractRegistry: EventContract[] = [
  {
    eventType: "borrower.onboarding.submitted",
    producerModuleId: "portal-borrower-onboarding",
    consumerModuleIds: [
      "portal-borrower-applications",
      "portal-borrower-financing-pathways",
      "portal-borrower-documents",
      "portal-borrower-readiness",
      "portal-borrower-environmental-intake",
      "portal-borrower-opportunities",
      "portal-borrower-data-rights",
      "reviews",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "borrower_id",
      "readiness_percent",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record governed borrower onboarding submission and route review-bound handoffs without approval, eligibility, financing, legal, permitting, or regulatory reliance.",
  },
  {
    eventType: "financing.pathway.evaluated",
    producerModuleId: "portal-borrower-financing-pathways",
    consumerModuleIds: [
      "portal-borrower-applications",
      "portal-borrower-documents",
      "portal-borrower-readiness",
      "reviews",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "borrower_id",
      "readiness_percent",
      "pathway_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record advisory financing pathway guidance and route review-bound handoffs without approval, eligibility, preapproval, underwriting, lender commitment, guarantee, legal, or regulatory reliance.",
  },
  {
    eventType: "application.review.requested",
    producerModuleId: "applications",
    consumerModuleIds: [
      "documents",
      "rules",
      "reviews",
      "case-command",
      "environmental-compliance",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["application_id", "borrower_id", "tenant_id", "replay_ref"],
    purpose: "Move an application into governed review posture.",
  },
  {
    eventType: "document.metadata.received",
    producerModuleId: "documents",
    consumerModuleIds: ["operator-queue", "reviews", "case-command"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["document_id", "application_id", "borrower_id", "replay_ref"],
    purpose: "Record document metadata receipt without raw document processing.",
  },
  {
    eventType: "notice.packet.prepared",
    producerModuleId: "notices",
    consumerModuleIds: [
      "operator-queue",
      "portal-borrower-notices",
      "audit-replay",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["notice_id", "application_id", "delivery_status", "replay_ref"],
    purpose: "Prepare notice packet state without external notice send.",
  },
  {
    eventType: "connector.certification.checked",
    producerModuleId: "connectors",
    consumerModuleIds: [
      "source-ingestion",
      "promotion",
      "live-scraper-activation",
      "source-legal-review",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["source_id", "adapter_id", "certification_status", "replay_ref"],
    purpose: "Verify connector certification posture without live external calls.",
  },
  {
    eventType: "promotion.gate.blocked",
    producerModuleId: "promotion",
    consumerModuleIds: [
      "governance",
      "module-readiness",
      "sponsor-readiness",
      "production-reliance-verification",
      "production-regulatory-examination",
      "production-regulatory-response",
    ],
    classificationLevel: "INTERNAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["gate_id", "blocked_reason", "target_module_id", "replay_ref"],
    purpose: "Preserve controlled production activation boundaries.",
  },
  {
    eventType: "rule.overlay.evaluated",
    producerModuleId: "rules",
    consumerModuleIds: ["decisions", "lender-overlays"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["evaluation_id", "application_id", "advisory_only", "replay_ref"],
    purpose: "Share advisory overlay posture without eligibility or approval claims.",
  },
  {
    eventType: "decision.finalization.checked",
    producerModuleId: "decisions",
    consumerModuleIds: ["notices"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "decision_notice_id",
      "application_id",
      "final_action_allowed",
      "replay_ref",
    ],
    purpose:
      "Record final-action gate posture before notice packet preparation.",
  },
  {
    eventType: "review.transition.approved",
    producerModuleId: "reviews",
    consumerModuleIds: ["rules", "decisions", "notices"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["transition_id", "human_review_id", "application_id", "replay_ref"],
    purpose: "Record human-reviewed transition posture before final-action controls.",
  },
  {
    eventType: "report.advisory.prepared",
    producerModuleId: "reports",
    consumerModuleIds: ["evidence-packets", "data-rights", "portal-borrower-reports"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["report_id", "application_id", "advisory_only", "replay_ref"],
    purpose: "Expose advisory report preparation without official report publication.",
  },
  {
    eventType: "audit.replay.checked",
    producerModuleId: "audit-replay",
    consumerModuleIds: ["evidence-packets", "governance"],
    classificationLevel: "INTERNAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["audit_ref", "replay_status", "module_id", "replay_ref"],
    purpose: "Move replay verification posture into evidence preparation.",
  },
  {
    eventType: "evidence.packet.prepared",
    producerModuleId: "evidence-packets",
    consumerModuleIds: ["lender-evidence", "module-readiness"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["evidence_packet_id", "application_id", "advisory_only", "replay_ref"],
    purpose: "Prepare governed evidence packets without public verification claims.",
  },
  {
    eventType: "data.rights.export.prepared",
    producerModuleId: "data-rights",
    consumerModuleIds: ["portal-borrower-data-rights", "reports"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["export_id", "borrower_id", "application_id", "replay_ref"],
    purpose: "Prepare governed borrower portability and review state.",
  },
  {
    eventType: "module.readiness.checked",
    producerModuleId: "module-readiness",
    consumerModuleIds: [
      "promotion",
      "operator-demo",
      "production-portal-readiness",
      "production-launch-evidence",
      "deployment-environment-readiness",
      "release-candidate-freeze",
      "production-cutover-hold",
      "production-release-board",
      "production-reliance-verification",
      "production-regulatory-examination",
      "production-regulatory-response",
    ],
    classificationLevel: "INTERNAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["readiness_id", "module_count", "promotion_blocked", "replay_ref"],
    purpose: "Move platform readiness posture into promotion review.",
  },
  {
    eventType: "governance.posture.reviewed",
    producerModuleId: "governance",
    consumerModuleIds: ["audit-replay", "module-readiness"],
    classificationLevel: "INTERNAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["governance_posture_id", "review_status", "replay_ref"],
    purpose: "Record governance review posture for readiness and replay surfaces.",
  },
  {
    eventType: "operator.queue.item.created",
    producerModuleId: "operator-queue",
    consumerModuleIds: ["reviews", "exception-remediation"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["queue_item_id", "source_type", "source_id", "replay_ref"],
    purpose: "Create operator review posture without automated final action.",
  },
  {
    eventType: "notice.exception.opened",
    producerModuleId: "notices",
    consumerModuleIds: ["operator-queue", "exception-remediation"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["notice_exception_id", "delivery_id", "application_id", "replay_ref"],
    purpose: "Route notice exceptions to governed remediation.",
  },
  {
    eventType: "partner.workflow.opened",
    producerModuleId: "partners",
    consumerModuleIds: ["lender-dashboard", "sponsor-dashboard", "case-command"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["workflow_id", "partner_type", "application_id", "replay_ref"],
    purpose: "Coordinate lender and sponsor workflows without commitments.",
  },
  {
    eventType: "payment.capture.blocked",
    producerModuleId: "billing",
    consumerModuleIds: ["promotion", "module-readiness"],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["billing_event_id", "payment_execution_id", "blocked_reason", "replay_ref"],
    purpose: "Preserve no-payment-capture posture before production promotion.",
  },
  {
    eventType: "source.ingestion.gate.checked",
    producerModuleId: "source-ingestion",
    consumerModuleIds: [
      "connectors",
      "promotion",
      "environmental-compliance",
      "portal-property-discovery",
      "lender-property-opportunities",
      "sponsor-project-discovery",
      "customer-revenue",
      "live-scraper-activation",
      "source-legal-review",
      "source-promotion-packets",
      "source-production-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["ingestion_event_id", "credential_vault_ref", "ready_for_session", "replay_ref"],
    purpose: "Record credentialed source ingestion readiness without external request.",
  },
  {
    eventType: "source.legal.reviewed",
    producerModuleId: "source-legal-review",
    consumerModuleIds: [
      "source-ingestion",
      "connectors",
      "live-scraper-activation",
      "source-promotion-packets",
      "source-production-readiness",
      "promotion",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "source_id",
      "legal_review_status",
      "tos_review_status",
      "activation_blocked",
      "replay_ref",
    ],
    purpose:
      "Record source legal, ToS, licensing, anti-bulk, and permitted-use review posture without providing legal advice or activating live source access.",
  },
  {
    eventType: "scraper.activation.reviewed",
    producerModuleId: "live-scraper-activation",
    consumerModuleIds: [
      "source-ingestion",
      "connectors",
      "source-legal-review",
      "source-promotion-packets",
      "source-production-readiness",
      "promotion",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "scraper_id",
      "source_id",
      "activation_blocked",
      "blocking_reasons",
      "replay_ref",
    ],
    purpose:
      "Record live scraper activation readiness while keeping live fetch, public verification, and production source reliance blocked.",
  },
  {
    eventType: "source.promotion.packet.reviewed",
    producerModuleId: "source-promotion-packets",
    consumerModuleIds: [
      "source-legal-review",
      "live-scraper-activation",
      "source-production-readiness",
      "controlled-promotion-activation",
      "promotion",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "packet_id",
      "source_id",
      "promotion_packet_status",
      "production_blocked",
      "live_fetch_performed",
      "replay_ref",
    ],
    purpose:
      "Record source promotion packet review posture while keeping legal advice, live fetch, public verification, and production source activation blocked.",
  },
  {
    eventType: "source.production.readiness.reviewed",
    producerModuleId: "source-production-readiness",
    consumerModuleIds: [
      "source-promotion-packets",
      "source-legal-review",
      "live-scraper-activation",
      "controlled-promotion-activation",
      "promotion",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "readiness_id",
      "source_id",
      "readiness_status",
      "production_blocked",
      "promotion_allowed",
      "live_fetch_performed",
      "replay_ref",
    ],
    purpose:
      "Record final source production-readiness review posture while keeping source promotion, live fetch, public verification, official reliance, and production activation blocked.",
  },
  {
    eventType: "controlled.promotion.activation.reviewed",
    producerModuleId: "controlled-promotion-activation",
    consumerModuleIds: [
      "source-production-readiness",
      "source-promotion-packets",
      "live-scraper-activation",
      "promotion",
      "production-portal-readiness",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "activation_review_id",
      "source_id",
      "activation_review_status",
      "production_blocked",
      "activation_executed",
      "live_fetch_performed",
      "replay_ref",
    ],
    purpose:
      "Record controlled promotion activation ceremony review posture while keeping activation execution, source promotion, live fetch, public verification, official reliance, and production activation blocked.",
  },
  {
    eventType: "production.portal.readiness.reviewed",
    producerModuleId: "production-portal-readiness",
    consumerModuleIds: [
      "controlled-promotion-activation",
      "module-readiness",
      "governance",
      "production-launch-evidence",
      "portal-borrower",
      "lender-dashboard",
      "sponsor-dashboard",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "readiness_review_id",
      "surface_id",
      "route",
      "audience",
      "launch_readiness_status",
      "production_blocked",
      "portal_launch_executed",
      "public_launch_allowed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production portal readiness preflight posture while keeping portal launch, live external action, payment capture, borrower notice sends, official report publication, public verification, and official reliance blocked.",
  },
  {
    eventType: "production.launch.evidence.reviewed",
    producerModuleId: "production-launch-evidence",
    consumerModuleIds: [
      "production-portal-readiness",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
      "deployment-environment-readiness",
      "release-candidate-freeze",
      "production-cutover-hold",
      "production-release-board",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "launch_evidence_packet_id",
      "packet_status",
      "production_blocked",
      "release_candidate",
      "go_live_approved",
      "portal_launch_executed",
      "public_launch_allowed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production launch evidence packet review posture while keeping go-live release, portal launch, public verification, live external action, payment capture, notice sends, official report publication, and official reliance blocked.",
  },
  {
    eventType: "deployment.environment.readiness.reviewed",
    producerModuleId: "deployment-environment-readiness",
    consumerModuleIds: [
      "production-launch-evidence",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
      "release-candidate-freeze",
      "production-cutover-hold",
      "production-release-board",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "deployment_environment_review_id",
      "review_status",
      "production_blocked",
      "release_candidate_approved",
      "deployment_executed",
      "environment_promotion_allowed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record deployment environment readiness posture while keeping release candidate approval, deployment, environment promotion, secret activation, DNS cutover, production migrations, live actions, payment capture, notice sends, official reports, public verification, and official reliance blocked.",
  },
  {
    eventType: "release.candidate.freeze.reviewed",
    producerModuleId: "release-candidate-freeze",
    consumerModuleIds: [
      "deployment-environment-readiness",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
      "production-cutover-hold",
      "production-release-board",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "release_candidate_freeze_plan_id",
      "plan_status",
      "production_blocked",
      "release_candidate_freeze_approved",
      "release_candidate_frozen",
      "release_candidate_approved",
      "deployment_executed",
      "environment_promotion_allowed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record release-candidate freeze review posture while keeping freeze approval, candidate freeze, deployment, environment promotion, secret activation, DNS cutover, production migrations, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.cutover.hold.reviewed",
    producerModuleId: "production-cutover-hold",
    consumerModuleIds: [
      "production-reliance-verification",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
      "production-release-board",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_cutover_hold_review_id",
      "review_status",
      "production_blocked",
      "production_cutover_approved",
      "production_cutover_executed",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production cutover hold posture while keeping cutover approval, cutover execution, launch hold release, deployment hold release, freeze hold release, deployment, secret activation, DNS cutover, production migrations, public API exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.release.board.reviewed",
    producerModuleId: "production-release-board",
    consumerModuleIds: [
      "production-operations-monitoring",
      "production-reliance-verification",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_release_board_review_id",
      "review_status",
      "production_blocked",
      "release_board_approval_granted",
      "cutover_authority_granted",
      "production_cutover_approved",
      "production_cutover_executed",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production release board evidence posture while keeping board approval, cutover authority, cutover approval, cutover execution, launch hold release, deployment hold release, freeze hold release, deployment, secret activation, DNS cutover, production migrations, public API exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.operations.monitoring.reviewed",
    producerModuleId: "production-operations-monitoring",
    consumerModuleIds: [
      "production-incident-response-readiness",
      "production-reliance-verification",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_operations_monitoring_review_id",
      "review_status",
      "production_blocked",
      "operations_monitoring_approval_granted",
      "production_monitoring_activated",
      "on_call_activated",
      "incident_bridge_activated",
      "rollback_authorized",
      "emergency_hold_released",
      "cutover_authority_granted",
      "production_cutover_executed",
      "deployment_executed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production operations monitoring evidence posture while keeping monitoring activation, on-call activation, incident bridge activation, rollback authorization, emergency hold release, cutover authority, deployment, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.incident.response.readiness.reviewed",
    producerModuleId: "production-incident-response-readiness",
    consumerModuleIds: [
      "production-support-communications-readiness",
      "production-reliance-verification",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_incident_response_readiness_review_id",
      "review_status",
      "production_blocked",
      "incident_response_approval_granted",
      "incident_response_activated",
      "incident_bridge_activated",
      "on_call_activated",
      "rollback_authorized",
      "emergency_rollback_executed",
      "emergency_hold_released",
      "kill_switch_activated",
      "customer_communications_released",
      "regulatory_communications_released",
      "public_status_page_enabled",
      "support_escalation_activated",
      "operations_monitoring_approval_granted",
      "production_monitoring_activated",
      "cutover_authority_granted",
      "production_cutover_executed",
      "deployment_executed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production incident response readiness evidence posture while keeping incident response activation, incident bridge activation, rollback authorization, emergency rollback execution, emergency hold release, kill-switch activation, customer communications, public status page, support escalation, cutover authority, deployment, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.support.communications.readiness.reviewed",
    producerModuleId: "production-support-communications-readiness",
    consumerModuleIds: [
      "production-final-authority",
      "production-reliance-verification",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_support_communications_readiness_review_id",
      "review_status",
      "production_blocked",
      "support_communications_approval_granted",
      "support_operations_activated",
      "support_escalation_activated",
      "customer_communications_released",
      "regulatory_communications_released",
      "public_status_page_enabled",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "legal_advice_provided",
      "official_reliance_allowed",
      "incident_response_activated",
      "incident_bridge_activated",
      "rollback_authorized",
      "emergency_rollback_executed",
      "emergency_hold_released",
      "kill_switch_activated",
      "cutover_authority_granted",
      "production_cutover_executed",
      "deployment_executed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production support communications readiness evidence posture while keeping support communications approval, support activation, support escalation, customer communications, regulatory communications, public status page, borrower notices, official reports, public verification, legal advice, official reliance, incident activation, rollback authorization, cutover authority, deployment, public production exposure, portal launch, live actions, and payment capture blocked.",
  },
  {
    eventType: "production.final.authority.reviewed",
    producerModuleId: "production-final-authority",
    consumerModuleIds: [
      "production-activation-ceremony",
      "production-reliance-verification",
      "production-regulatory-examination",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_final_authority_review_id",
      "review_status",
      "production_blocked",
      "final_authority_approval_granted",
      "go_live_approved",
      "production_launch_authorized",
      "constitutional_officer_attestation_received",
      "qualified_release_manager_approval_granted",
      "support_communications_approval_granted",
      "support_operations_activated",
      "support_escalation_activated",
      "customer_communications_released",
      "regulatory_communications_released",
      "public_status_page_enabled",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "legal_advice_provided",
      "official_reliance_allowed",
      "incident_response_activated",
      "incident_bridge_activated",
      "rollback_authorized",
      "emergency_rollback_executed",
      "emergency_hold_released",
      "kill_switch_activated",
      "cutover_authority_granted",
      "production_cutover_executed",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production final authority evidence posture while keeping final authority approval, go-live approval, production launch authorization, constitutional attestation, release-manager approval, support activation, communications release, public status page, notices, official reports, public verification, legal advice, official reliance, incident activation, rollback authorization, hold releases, cutover authority, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, and payment capture blocked.",
  },
  {
    eventType: "production.activation.ceremony.reviewed",
    producerModuleId: "production-activation-ceremony",
    consumerModuleIds: [
      "production-post-activation-verification",
      "production-reliance-verification",
      "production-regulatory-examination",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_activation_ceremony_review_id",
      "review_status",
      "production_blocked",
      "activation_ceremony_approval_granted",
      "activation_ceremony_executed",
      "production_activation_executed",
      "post_activation_verification_started",
      "post_activation_verification_completed",
      "final_authority_approval_granted",
      "go_live_approved",
      "production_launch_authorized",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "legal_advice_provided",
      "official_reliance_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production activation ceremony evidence posture while keeping ceremony approval, ceremony execution, production activation, post-activation verification, hold releases, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.post.activation.verification.reviewed",
    producerModuleId: "production-post-activation-verification",
    consumerModuleIds: [
      "production-reliance-verification",
      "production-regulatory-examination",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_post_activation_verification_review_id",
      "review_status",
      "production_blocked",
      "post_activation_verification_approval_granted",
      "post_activation_verification_started",
      "post_activation_verification_completed",
      "post_activation_verification_passed",
      "production_health_certified",
      "activation_ceremony_approval_granted",
      "activation_ceremony_executed",
      "production_activation_executed",
      "final_authority_approval_granted",
      "go_live_approved",
      "production_launch_authorized",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_allowed",
      "legal_advice_provided",
      "official_reliance_allowed",
      "replay_ref",
    ],
    purpose:
      "Record production post-activation verification evidence posture while keeping verification approval, verification start, verification completion, production health certification, activation ceremony approval, ceremony execution, production activation, hold releases, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, public verification, legal advice, and official reliance blocked.",
  },
  {
    eventType: "production.reliance.verification.reviewed",
    producerModuleId: "production-reliance-verification",
    consumerModuleIds: [
      "production-regulatory-examination",
      "production-regulatory-response",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_reliance_verification_review_id",
      "review_status",
      "production_blocked",
      "production_reliance_approval_granted",
      "public_verification_approval_granted",
      "public_verification_gateway_operational",
      "public_verification_artifact_published",
      "external_reliance_disclosure_approved",
      "regulatory_reliance_allowed",
      "official_reliance_allowed",
      "legal_advice_provided",
      "post_activation_verification_approval_granted",
      "post_activation_verification_started",
      "post_activation_verification_completed",
      "post_activation_verification_passed",
      "production_health_certified",
      "activation_ceremony_approval_granted",
      "activation_ceremony_executed",
      "production_activation_executed",
      "final_authority_approval_granted",
      "go_live_approved",
      "production_launch_authorized",
      "launch_hold_released",
      "deployment_hold_released",
      "freeze_hold_released",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "customer_communications_released",
      "public_status_page_enabled",
      "replay_ref",
    ],
    purpose:
      "Record production reliance and public verification boundary evidence posture while keeping production reliance, public verification, public verification gateway operation, public verification artifact publication, external reliance disclosure, regulatory reliance, official reliance, legal advice, post-activation verification, production health certification, activation, hold releases, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, communications, and public status blocked.",
  },
  {
    eventType: "production.regulatory.examination.reviewed",
    producerModuleId: "production-regulatory-examination",
    consumerModuleIds: [
      "production-regulatory-response",
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_regulatory_examination_review_id",
      "review_status",
      "production_blocked",
      "regulatory_examination_package_approved",
      "regulatory_examination_package_submitted",
      "regulator_portal_upload_allowed",
      "regulatory_response_issued",
      "examination_archive_certified",
      "evidence_retention_certified",
      "legal_hold_released",
      "external_examiner_disclosure_approved",
      "production_reliance_approval_granted",
      "public_verification_approval_granted",
      "public_verification_gateway_operational",
      "public_verification_artifact_published",
      "regulatory_reliance_allowed",
      "official_reliance_allowed",
      "legal_advice_provided",
      "post_activation_verification_approval_granted",
      "production_health_certified",
      "production_activation_executed",
      "go_live_approved",
      "production_launch_authorized",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "live_external_action_performed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "customer_communications_released",
      "public_status_page_enabled",
      "replay_ref",
    ],
    purpose:
      "Record production regulatory examination and evidence archive posture while keeping regulatory package approval, regulator submission, regulator portal upload, official regulator response, archive certification, retention certification, legal hold release, external examiner disclosure, production reliance, public verification, regulatory reliance, official reliance, legal advice, production health certification, activation, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, communications, and public status blocked.",
  },
  {
    eventType: "production.regulatory.response.reviewed",
    producerModuleId: "production-regulatory-response",
    consumerModuleIds: [
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
      "build-preservation",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "production_regulatory_response_review_id",
      "review_status",
      "production_blocked",
      "regulatory_response_package_approved",
      "official_regulator_response_issued",
      "corrective_action_plan_approved",
      "corrective_action_committed",
      "corrective_action_executed",
      "remediation_plan_approved",
      "remediation_executed",
      "examiner_finding_closed",
      "external_examiner_disclosure_approved",
      "legal_hold_released",
      "production_reliance_approval_granted",
      "public_verification_approval_granted",
      "regulatory_reliance_allowed",
      "official_reliance_allowed",
      "legal_advice_provided",
      "regulatory_examination_package_submitted",
      "examination_archive_certified",
      "production_health_certified",
      "production_activation_executed",
      "go_live_approved",
      "production_launch_authorized",
      "deployment_executed",
      "production_secrets_activated",
      "public_dns_cutover_allowed",
      "database_migration_allowed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "customer_communications_released",
      "public_status_page_enabled",
      "live_external_action_performed",
      "replay_ref",
    ],
    purpose:
      "Record production regulatory response and corrective-action posture while keeping response package approval, official regulator response issuance, corrective-action approval, corrective-action commitment, corrective-action execution, remediation approval, remediation execution, examiner finding closure, legal hold release, external examiner disclosure, production reliance, public verification, regulatory reliance, official reliance, legal advice, examination submission, archive certification, production health certification, activation, deployment, secrets, DNS, migrations, public production exposure, portal launch, live actions, payment capture, notice sends, official reports, communications, and public status blocked.",
  },
  {
    eventType: "build.preservation.archived",
    producerModuleId: "build-preservation",
    consumerModuleIds: [
      "module-readiness",
      "governance",
      "promotion",
      "doctrine-gap-ledger",
      "operator-demo",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "build_preservation_review_id",
      "checkpoint_id",
      "checkpoint_title",
      "checkpoint_commit_hash",
      "current_commit_hash",
      "review_status",
      "production_blocked",
      "checkpoint_recorded",
      "build_archive_generated",
      "tree_drift_detected",
      "tree_status",
      "ignored_sensitive_files_verified",
      "module_count",
      "highest_module_number",
      "event_contract_count",
      "handoff_count",
      "public_surface_count",
      "portable_surface_count",
      "app_page_route_count",
      "api_route_count",
      "static_pages_generated",
      "production_launch_authorized",
      "deployment_executed",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_approval_granted",
      "official_reliance_allowed",
      "legal_advice_provided",
      "live_external_action_performed",
      "replay_ref",
    ],
    purpose:
      "Record build preservation and evidence archive posture while keeping production launch, deployment, public production exposure, portal launch, payments, notices, official reports, public verification, official reliance, legal advice, regulatory response, corrective-action commitment, remediation execution, and live external actions blocked.",
  },
  {
    eventType: "doctrine.gap.ledger.reviewed",
    producerModuleId: "doctrine-gap-ledger",
    consumerModuleIds: [
      "module-readiness",
      "governance",
      "promotion",
      "operator-demo",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "doctrine_gap_ledger_review_id",
      "checkpoint_id",
      "total_requirements",
      "implemented_requirements",
      "awaiting_controlled_promotion",
      "named_gap_count",
      "unnamed_gap_count",
      "all_gaps_owned",
      "all_gaps_routed",
      "all_gaps_have_required_evidence",
      "all_gaps_have_promotion_conditions",
      "production_launch_authorized",
      "public_production_api_exposure_allowed",
      "production_portal_launch_executed",
      "payment_capture_allowed",
      "borrower_notice_send_allowed",
      "official_report_publication_allowed",
      "public_verification_approval_granted",
      "official_reliance_allowed",
      "legal_advice_provided",
      "live_external_action_performed",
      "replay_ref",
    ],
    purpose:
      "Record doctrine-to-code gap ledger posture while keeping all awaiting-controlled-promotion items named, owned, routed, evidenced, ticketed, and blocked from production launch, public exposure, portal launch, payments, notices, official reports, public verification, official reliance, legal advice, and live external actions.",
  },
  {
    eventType: "environmental.compliance.reviewed",
    producerModuleId: "environmental-compliance",
    consumerModuleIds: ["case-command", "evidence-packets", "promotion"],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "compliance_record_id",
      "application_id",
      "assessment_requirement_status",
      "loan_pathway_advancement_allowed",
      "replay_ref",
    ],
    purpose:
      "Record environmental review posture without official environmental report or live provider action.",
  },
  {
    eventType: "property.discovery.ingested",
    producerModuleId: "source-ingestion",
    consumerModuleIds: [
      "portal-property-discovery",
      "lender-property-opportunities",
      "sponsor-project-discovery",
      "customer-revenue",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "property_record_id",
      "source_refs",
      "canonicalization_status",
      "replay_ref",
    ],
    purpose:
      "Move property discovery metadata into governed consumers without treating listings as collateral truth.",
  },
  {
    eventType: "program.graph.updated",
    producerModuleId: "customer-revenue",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "lender-revenue-opportunities",
      "sponsor-revenue-opportunities",
      "evidence-packets",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "program_id",
      "source_refs",
      "review_status",
      "replay_ref",
    ],
    purpose:
      "Share preliminary program graph changes without approval, award, or legal-position claims.",
  },
  {
    eventType: "market.signal.refreshed",
    producerModuleId: "customer-revenue",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "lender-revenue-opportunities",
      "sponsor-revenue-opportunities",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "market_signal_id",
      "freshness_status",
      "source_refs",
      "replay_ref",
    ],
    purpose:
      "Share reviewed market signal freshness without forecast or revenue guarantee claims.",
  },
  {
    eventType: "geo.overlay.updated",
    producerModuleId: "source-ingestion",
    consumerModuleIds: [
      "portal-property-discovery",
      "lender-property-opportunities",
      "sponsor-project-discovery",
      "customer-revenue",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "geo_overlay_id",
      "layer_type",
      "freshness_status",
      "replay_ref",
    ],
    purpose:
      "Share geospatial overlay posture as planning intelligence only and preserve review boundaries.",
  },
  {
    eventType: "revenue.opportunity.generated",
    producerModuleId: "customer-revenue",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "lender-revenue-opportunities",
      "sponsor-revenue-opportunities",
      "evidence-packets",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "revenue_opportunity_id",
      "customer_type",
      "claims_profile",
      "replay_ref",
    ],
    purpose:
      "Generate advisory revenue opportunity posture without guaranteed revenue, approval, or commitment claims.",
  },
  {
    eventType: "scraper.run.completed",
    producerModuleId: "source-ingestion",
    consumerModuleIds: [
      "connectors",
      "operator-queue",
      "portal-property-discovery",
      "customer-revenue",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "scraper_run_id",
      "source_id",
      "fetch_count",
      "replay_ref",
    ],
    purpose:
      "Record completed source runtime metadata without authorizing live external source use.",
  },
  {
    eventType: "source.conflict.detected",
    producerModuleId: "source-ingestion",
    consumerModuleIds: [
      "operator-queue",
      "exception-remediation",
      "customer-revenue",
      "governance",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "conflict_event_id",
      "entity_type",
      "conflicting_source_refs",
      "replay_ref",
    ],
    purpose:
      "Escalate source conflicts while preserving all conflicting records and blocking certainty claims.",
  },
  {
    eventType: "human.review.required",
    producerModuleId: "reviews",
    consumerModuleIds: ["operator-queue", "governance", "module-readiness"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "review_ref",
      "trigger_event_type",
      "reason",
      "replay_ref",
    ],
    purpose:
      "Make human-review escalation explicit for source, revenue, document, notice, and module-readiness workflows.",
  },
  {
    eventType: "revenue.opportunity.reviewed",
    producerModuleId: "customer-revenue",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "lender-revenue-opportunities",
      "sponsor-revenue-opportunities",
      "evidence-packets",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "revenue_opportunity_id",
      "customer_type",
      "source_refs",
      "claims_profile",
      "replay_ref",
    ],
    purpose:
      "Share governed advisory revenue context without legal, program, revenue, underwriting, or commitment claims.",
  },
  {
    eventType: "case.context.updated",
    producerModuleId: "case-command",
    consumerModuleIds: ["applications", "documents", "reviews", "module-readiness"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["case_id", "application_id", "current_stage", "replay_ref"],
    purpose: "Coordinate shared case context across governed modules.",
  },
  {
    eventType: "exception.remediation.reviewed",
    producerModuleId: "exception-remediation",
    consumerModuleIds: ["operator-queue", "module-readiness"],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["remediation_id", "exception_type", "resolution_status", "replay_ref"],
    purpose: "Record exception remediation posture without live remediation action.",
  },
  {
    eventType: "demo.handoff.reviewed",
    producerModuleId: "operator-demo",
    consumerModuleIds: ["module-readiness"],
    classificationLevel: "INTERNAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: ["demo_case_id", "review_status", "replay_ref"],
    purpose: "Record governed operator demo handoff review.",
  },
  {
    eventType: "public.surface.viewed",
    producerModuleId: "portal-borrower",
    consumerModuleIds: ["governance"],
    classificationLevel: "PUBLIC",
    replayRequired: true,
    publicSurfaceAllowed: true,
    productionBlocked: true,
    payloadFields: ["surface_id", "audience", "trace_id", "replay_ref"],
    purpose: "Record public-safe translation-layer viewing posture.",
  },
  {
    eventType: "borrower.readiness.assessed",
    producerModuleId: "portal-borrower-readiness",
    consumerModuleIds: [
      "portal-borrower-onboarding",
      "portal-borrower-financing-pathways",
      "portal-borrower-applications",
      "portal-borrower-documents",
      "portal-borrower-opportunities",
      "portal-borrower-data-rights",
      "reviews",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "borrower_id",
      "overall_readiness_percent",
      "section_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record borrower readiness assessment posture and route review-bound handoffs without approval, eligibility, certification, public verification, lender commitment, legal, or regulatory reliance.",
  },
  {
    eventType: "borrower.environmental.intake.submitted",
    producerModuleId: "portal-borrower-environmental-intake",
    consumerModuleIds: [
      "environmental-compliance",
      "portal-borrower-applications",
      "portal-borrower-documents",
      "portal-borrower-readiness",
      "portal-borrower-data-rights",
      "reviews",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "borrower_id",
      "assessment_route",
      "pathway_posture",
      "readiness_percent",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record borrower environmental intake routing posture and route review-bound handoffs without environmental determination, clearance, permit, provider engagement, fee authorization, or legal or regulatory reliance.",
  },
  {
    eventType: "borrower.opportunity.discovery.viewed",
    producerModuleId: "portal-borrower-opportunities",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "portal-property-discovery",
      "portal-borrower-readiness",
      "portal-borrower-data-rights",
      "reviews",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "borrower_id",
      "section_count",
      "total_opportunity_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record borrower opportunity discovery review posture and route review-bound handoffs without guaranteed revenue, program approval, source certainty, property certification, lender commitment, live external action, or legal or regulatory reliance.",
  },
  {
    eventType: "governance.opportunity.discovery.v2.composed",
    producerModuleId: "governance-opportunity-discovery-v2",
    consumerModuleIds: [
      "governance-financing-pathway-engine-v2",
      "governance-revenue-intelligence-v2",
      "governance-capital-graph",
      "governance-customer-type-registry",
      "customer-revenue",
      "portal-revenue-opportunities",
      "portal-borrower-opportunities",
      "portal-borrower-financing-pathways",
      "lender-workflow",
      "governance-advanced-intelligence",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-registry-framework",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "customer_profile_count",
      "total_grant_card_count",
      "total_legacy_card_count",
      "conflict_signal_count",
      "cross_source_conflict_count",
      "sovereign_card_count",
      "review_required_count",
      "missing_information_count",
      "federation_gated_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record Opportunity Discovery v2 composition posture (Financing Pathway Engine v2 × Revenue Intelligence v2 × Customer Type × Capital Graph + legacy v1 opportunity discovery bridge) and route review-bound handoffs without autonomous customer eligibility determination, autonomous pathway determination, autonomous opportunity determination, credit decision, lender commitment, program approval, tax-credit allocation, environmental clearance, carbon-credit issuance, public verification, source certainty claim, payment authorization, live external action, or legal reliance.",
  },
  {
    eventType: "governance.financing.pathway.engine.v2.composed",
    producerModuleId: "governance-financing-pathway-engine-v2",
    consumerModuleIds: [
      "governance-revenue-intelligence-v2",
      "governance-capital-graph",
      "governance-customer-type-registry",
      "customer-revenue",
      "portal-revenue-opportunities",
      "portal-borrower-opportunities",
      "portal-borrower-financing-pathways",
      "lender-workflow",
      "governance-advanced-intelligence",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-registry-framework",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "customer_profile_count",
      "total_candidate_count",
      "total_legacy_candidate_count",
      "conflict_signal_count",
      "cross_source_conflict_count",
      "sovereign_candidate_count",
      "review_required_count",
      "missing_information_count",
      "federation_gated_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record Financing Pathway Engine v2 composition posture (Revenue Intelligence v2 × Customer Type × Capital Graph + legacy v1 compatibility bridge) and route review-bound handoffs without autonomous customer eligibility determination, autonomous pathway determination, credit decision, lender commitment, program approval, tax-credit allocation, environmental clearance, carbon-credit issuance, public verification, regulatory reliance, payment authorization, live external action, or legal reliance.",
  },
  {
    eventType: "governance.revenue.intelligence.v2.composed",
    producerModuleId: "governance-revenue-intelligence-v2",
    consumerModuleIds: [
      "governance-capital-graph",
      "governance-customer-type-registry",
      "customer-revenue",
      "portal-revenue-opportunities",
      "portal-borrower-opportunities",
      "portal-borrower-financing-pathways",
      "lender-workflow",
      "governance-advanced-intelligence",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-registry-framework",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "customer_profile_count",
      "total_composed_program_count",
      "total_legacy_opportunity_count",
      "conflict_signal_count",
      "cross_source_conflict_count",
      "sovereign_program_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record Revenue Intelligence v2 composition posture (Customer Type Registry × Capital Graph + legacy compatibility bridge) and route review-bound handoffs without autonomous customer eligibility determination, credit decision, lender commitment, public verification, regulatory reliance, tax-credit allocation, environmental clearance, carbon-credit issuance, payment authorization, live external action, or legal reliance.",
  },
  {
    eventType: "governance.customer.type.composed",
    producerModuleId: "governance-customer-type-registry",
    consumerModuleIds: [
      "governance-capital-graph",
      "portal-borrower-financing-pathways",
      "portal-borrower-opportunities",
      "portal-revenue-opportunities",
      "customer-revenue",
      "lender-workflow",
      "governance-advanced-intelligence",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-registry-framework",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "archetype_count",
      "customer_type_count",
      "matched_type_count",
      "total_eligible_capital_ref_count",
      "conflict_signal_count",
      "sovereign_type_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record canonical Customer Type Registry composition posture and route review-bound handoffs without autonomous customer eligibility determination, credit decision, lender commitment, public verification, regulatory reliance, tax-credit allocation, environmental clearance, carbon-credit issuance, payment authorization, live external action, or legal reliance.",
  },
  {
    eventType: "governance.capital.graph.composed",
    producerModuleId: "governance-capital-graph",
    consumerModuleIds: [
      "portal-borrower-financing-pathways",
      "portal-borrower-opportunities",
      "portal-revenue-opportunities",
      "customer-revenue",
      "lender-workflow",
      "governance-advanced-intelligence",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-registry-framework",
      "governance-connector-certification",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "category_count",
      "program_count",
      "matched_program_count",
      "pathway_candidate_count",
      "conflict_signal_count",
      "sovereign_program_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record canonical Capital Graph composition posture and route review-bound handoffs without autonomous lending decision, program approval, public verification, regulatory reliance, lender commitment, tax-credit allocation, environmental clearance, carbon-credit issuance, payment authorization, live external action, or legal reliance.",
  },
  {
    eventType: "governance.intelligence.composed",
    producerModuleId: "governance-advanced-intelligence",
    consumerModuleIds: [
      "portal-revenue-opportunities",
      "portal-property-discovery",
      "customer-revenue",
      "portal-borrower-opportunities",
      "governance-registry-framework",
      "governance-evidence-engine",
      "governance-certification-engine",
      "governance-connector-certification",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "domain_count",
      "insight_count",
      "conflict_count",
      "source_authority_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record advanced intelligence composition posture and route review-bound handoffs without approval, eligibility, underwriting, credit decision, lender commitment, public verification, regulatory reliance, environmental clearance, payment authorization, or legal reliance.",
  },
  {
    eventType: "governance.connector.certification.composed",
    producerModuleId: "governance-connector-certification",
    consumerModuleIds: [
      "connectors",
      "source-ingestion",
      "live-scraper-activation",
      "controlled-promotion-activation",
      "governance-registry-framework",
      "governance-evidence-engine",
      "governance-certification-engine",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "connector_count",
      "certified_connector_count",
      "blocked_connector_count",
      "overall_readiness_percent",
      "live_execution_blocked_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record per-connector certification posture and route review-bound handoffs without live external connector execution, live fetch, external promotion, public verification, regulatory reliance, lender commitment, credit decision, environmental clearance, payment authorization, or legal reliance.",
  },
  {
    eventType: "governance.registry.framework.composed",
    producerModuleId: "governance-registry-framework",
    consumerModuleIds: [
      "governance-evidence-engine",
      "governance-certification-engine",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
      "promotion",
      "controlled-promotion-activation",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "catalog_count",
      "total_entry_count",
      "public_surface_entry_count",
      "internal_only_entry_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record internal registry framework composition and route review-bound handoffs without external promotion, public verification, regulatory reliance, lender commitment, credit decision, environmental clearance, payment authorization, or legal reliance.",
  },
  {
    eventType: "governance.certification.posture.composed",
    producerModuleId: "governance-certification-engine",
    consumerModuleIds: [
      "governance-evidence-engine",
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "application_id",
      "domain_count",
      "certified_domain_count",
      "pending_domain_count",
      "blocked_domain_count",
      "overall_readiness_percent",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record internal certification posture composition and route review-bound handoffs without external certification, public verification, regulatory reliance, lender commitment, credit decision, environmental clearance, payment authorization, or legal reliance.",
  },
  {
    eventType: "governance.evidence.pack.composed",
    producerModuleId: "governance-evidence-engine",
    consumerModuleIds: [
      "evidence-packets",
      "audit-replay",
      "governance",
      "reviews",
      "module-readiness",
      "lender-evidence",
    ],
    classificationLevel: "RESTRICTED",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "pack_intent",
      "application_id",
      "module_count",
      "event_contract_count",
      "handoff_count",
      "human_authority_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record governance evidence pack composition posture and route review-bound handoffs without approval, official certification, public verification, regulatory reliance, lender commitment, credit decision, environmental clearance, payment authorization, or legal reliance.",
  },
  {
    eventType: "lender.workflow.viewed",
    producerModuleId: "lender-workflow",
    consumerModuleIds: [
      "lender-dashboard",
      "lender-applications",
      "lender-overlays",
      "lender-evidence",
      "lender-property-opportunities",
      "lender-revenue-opportunities",
      "partners",
      "reviews",
    ],
    classificationLevel: "CONFIDENTIAL",
    replayRequired: true,
    publicSurfaceAllowed: false,
    productionBlocked: true,
    payloadFields: [
      "lender_id",
      "partner_workflow_id",
      "application_count",
      "ready_for_review_count",
      "human_review_required",
      "replay_ref",
    ],
    purpose:
      "Record lender coordination workflow view posture and route review-bound handoffs without approval, eligibility, underwriting, credit decision, lender commitment, official credit communication, borrower notice send, payment capture, or legal or regulatory reliance.",
  },
  {
    eventType: "public.trust.viewed",
    producerModuleId: "public-trust",
    consumerModuleIds: [
      "portal-borrower-readiness",
      "portal-borrower-financing-pathways",
      "portal-borrower-data-rights",
      "governance",
    ],
    classificationLevel: "PUBLIC",
    replayRequired: true,
    publicSurfaceAllowed: true,
    productionBlocked: true,
    payloadFields: [
      "audience",
      "referrer_route",
      "content_claims_ok",
      "trace_id",
      "replay_ref",
    ],
    purpose:
      "Record public trust content viewing posture and route review-bound handoffs without approval, eligibility, credit decision, certification, public verification, lender commitment, environmental clearance, payment authorization, official report publication, or legal or regulatory reliance.",
  },
];

const moduleIds = new Set(moduleManifests.map((manifest) => manifest.id));

export function eventContractModulesAreRegistered(
  contract: EventContract
): boolean {
  return (
    moduleIds.has(contract.producerModuleId) &&
    contract.consumerModuleIds.every((moduleId) => moduleIds.has(moduleId))
  );
}

export function eventContractsForModule(moduleId: string): EventContract[] {
  return eventContractRegistry.filter(
    (contract) =>
      contract.producerModuleId === moduleId ||
      contract.consumerModuleIds.includes(moduleId)
  );
}
