/**
 * Cross-Module Navigation and Handoff Map
 *
 * Master Volume Governance:
 * - Vol I: keeps module transitions explicit and accountable.
 * - Vol II: preserves regulated workflow boundaries through human review,
 *   notices, decisions, source authority, and data rights.
 * - Vol III: prevents tight coupling by routing handoffs through governed
 *   events and canonical backend surfaces.
 * - Vol IV: supports operator follow-through and recovery.
 * - Vol V: preserves replay, claims, controlled disclosure, and source
 *   authority across module transitions.
 */

export type ModuleHandoff = {
  id: string;
  fromModuleId: string;
  toModuleId: string;
  fromRoute: string;
  toRoute: string;
  eventType: string;
  replayRequired: boolean;
  humanReviewBoundary: boolean;
  productionBlocked: boolean;
};

export const crossModuleHandoffMap: ModuleHandoff[] = [
  {
    id: "borrower-onboarding-to-applications",
    fromModuleId: "portal-borrower-onboarding",
    toModuleId: "portal-borrower-applications",
    fromRoute: "/onboarding",
    toRoute: "/portal/borrower/applications",
    eventType: "borrower.onboarding.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-onboarding-to-financing-pathways",
    fromModuleId: "portal-borrower-onboarding",
    toModuleId: "portal-borrower-financing-pathways",
    fromRoute: "/onboarding",
    toRoute: "/financing-pathways",
    eventType: "borrower.onboarding.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "financing-pathways-to-applications",
    fromModuleId: "portal-borrower-financing-pathways",
    toModuleId: "portal-borrower-applications",
    fromRoute: "/financing-pathways",
    toRoute: "/portal/borrower/applications",
    eventType: "financing.pathway.evaluated",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "financing-pathways-to-documents",
    fromModuleId: "portal-borrower-financing-pathways",
    toModuleId: "portal-borrower-documents",
    fromRoute: "/financing-pathways",
    toRoute: "/portal/borrower/documents",
    eventType: "financing.pathway.evaluated",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "applications-to-documents",
    fromModuleId: "applications",
    toModuleId: "documents",
    fromRoute: "/applications",
    toRoute: "/documents",
    eventType: "application.review.requested",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "documents-to-reviews",
    fromModuleId: "documents",
    toModuleId: "reviews",
    fromRoute: "/documents",
    toRoute: "/reviews",
    eventType: "document.metadata.received",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "reviews-to-rules",
    fromModuleId: "reviews",
    toModuleId: "rules",
    fromRoute: "/reviews",
    toRoute: "/rules",
    eventType: "review.transition.approved",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "reviews-to-decisions",
    fromModuleId: "reviews",
    toModuleId: "decisions",
    fromRoute: "/reviews",
    toRoute: "/decisions",
    eventType: "review.transition.approved",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "decisions-to-notices",
    fromModuleId: "decisions",
    toModuleId: "notices",
    fromRoute: "/decisions",
    toRoute: "/notices",
    eventType: "decision.finalization.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "rules-to-decisions",
    fromModuleId: "rules",
    toModuleId: "decisions",
    fromRoute: "/rules",
    toRoute: "/decisions",
    eventType: "rule.overlay.evaluated",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "connectors-to-source-ingestion",
    fromModuleId: "connectors",
    toModuleId: "source-ingestion",
    fromRoute: "/connectors",
    toRoute: "/source-ingestion",
    eventType: "connector.certification.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "applications-to-environmental-compliance",
    fromModuleId: "applications",
    toModuleId: "environmental-compliance",
    fromRoute: "/applications",
    toRoute: "/environmental-compliance",
    eventType: "application.review.requested",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-environmental-compliance",
    fromModuleId: "source-ingestion",
    toModuleId: "environmental-compliance",
    fromRoute: "/source-ingestion",
    toRoute: "/environmental-compliance",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-live-scraper-activation",
    fromModuleId: "source-ingestion",
    toModuleId: "live-scraper-activation",
    fromRoute: "/source-ingestion",
    toRoute: "/live-scraper-activation",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-source-legal-review",
    fromModuleId: "source-ingestion",
    toModuleId: "source-legal-review",
    fromRoute: "/source-ingestion",
    toRoute: "/source-legal-review",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "connectors-to-live-scraper-activation",
    fromModuleId: "connectors",
    toModuleId: "live-scraper-activation",
    fromRoute: "/connectors",
    toRoute: "/live-scraper-activation",
    eventType: "connector.certification.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "connectors-to-source-legal-review",
    fromModuleId: "connectors",
    toModuleId: "source-legal-review",
    fromRoute: "/connectors",
    toRoute: "/source-legal-review",
    eventType: "connector.certification.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-legal-review-to-live-scraper-activation",
    fromModuleId: "source-legal-review",
    toModuleId: "live-scraper-activation",
    fromRoute: "/source-legal-review",
    toRoute: "/live-scraper-activation",
    eventType: "source.legal.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-legal-review-to-promotion",
    fromModuleId: "source-legal-review",
    toModuleId: "promotion",
    fromRoute: "/source-legal-review",
    toRoute: "/promotion",
    eventType: "source.legal.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-legal-review-to-source-promotion-packets",
    fromModuleId: "source-legal-review",
    toModuleId: "source-promotion-packets",
    fromRoute: "/source-legal-review",
    toRoute: "/source-promotion-packets",
    eventType: "source.legal.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-legal-review-to-module-readiness",
    fromModuleId: "source-legal-review",
    toModuleId: "module-readiness",
    fromRoute: "/source-legal-review",
    toRoute: "/module-readiness",
    eventType: "source.legal.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "live-scraper-activation-to-source-promotion-packets",
    fromModuleId: "live-scraper-activation",
    toModuleId: "source-promotion-packets",
    fromRoute: "/live-scraper-activation",
    toRoute: "/source-promotion-packets",
    eventType: "scraper.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "live-scraper-activation-to-promotion",
    fromModuleId: "live-scraper-activation",
    toModuleId: "promotion",
    fromRoute: "/live-scraper-activation",
    toRoute: "/promotion",
    eventType: "scraper.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-promotion-packets-to-promotion",
    fromModuleId: "source-promotion-packets",
    toModuleId: "promotion",
    fromRoute: "/source-promotion-packets",
    toRoute: "/promotion",
    eventType: "source.promotion.packet.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-promotion-packets-to-source-production-readiness",
    fromModuleId: "source-promotion-packets",
    toModuleId: "source-production-readiness",
    fromRoute: "/source-promotion-packets",
    toRoute: "/source-production-readiness",
    eventType: "source.promotion.packet.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-production-readiness-to-promotion",
    fromModuleId: "source-production-readiness",
    toModuleId: "promotion",
    fromRoute: "/source-production-readiness",
    toRoute: "/promotion",
    eventType: "source.production.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-production-readiness-to-controlled-promotion-activation",
    fromModuleId: "source-production-readiness",
    toModuleId: "controlled-promotion-activation",
    fromRoute: "/source-production-readiness",
    toRoute: "/controlled-promotion-activation",
    eventType: "source.production.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "controlled-promotion-activation-to-promotion",
    fromModuleId: "controlled-promotion-activation",
    toModuleId: "promotion",
    fromRoute: "/controlled-promotion-activation",
    toRoute: "/promotion",
    eventType: "controlled.promotion.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "controlled-promotion-activation-to-module-readiness",
    fromModuleId: "controlled-promotion-activation",
    toModuleId: "module-readiness",
    fromRoute: "/controlled-promotion-activation",
    toRoute: "/module-readiness",
    eventType: "controlled.promotion.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "controlled-promotion-activation-to-production-portal-readiness",
    fromModuleId: "controlled-promotion-activation",
    toModuleId: "production-portal-readiness",
    fromRoute: "/controlled-promotion-activation",
    toRoute: "/production-portal-readiness",
    eventType: "controlled.promotion.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-portal-readiness-to-module-readiness",
    fromModuleId: "production-portal-readiness",
    toModuleId: "module-readiness",
    fromRoute: "/production-portal-readiness",
    toRoute: "/module-readiness",
    eventType: "production.portal.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-portal-readiness-to-governance",
    fromModuleId: "production-portal-readiness",
    toModuleId: "governance",
    fromRoute: "/production-portal-readiness",
    toRoute: "/governance",
    eventType: "production.portal.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-portal-readiness-to-production-launch-evidence",
    fromModuleId: "production-portal-readiness",
    toModuleId: "production-launch-evidence",
    fromRoute: "/production-portal-readiness",
    toRoute: "/production-launch-evidence",
    eventType: "production.portal.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-launch-evidence-to-module-readiness",
    fromModuleId: "production-launch-evidence",
    toModuleId: "module-readiness",
    fromRoute: "/production-launch-evidence",
    toRoute: "/module-readiness",
    eventType: "production.launch.evidence.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-launch-evidence-to-deployment-environment-readiness",
    fromModuleId: "production-launch-evidence",
    toModuleId: "deployment-environment-readiness",
    fromRoute: "/production-launch-evidence",
    toRoute: "/deployment-environment-readiness",
    eventType: "production.launch.evidence.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-launch-evidence-to-governance",
    fromModuleId: "production-launch-evidence",
    toModuleId: "governance",
    fromRoute: "/production-launch-evidence",
    toRoute: "/governance",
    eventType: "production.launch.evidence.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "deployment-environment-readiness-to-module-readiness",
    fromModuleId: "deployment-environment-readiness",
    toModuleId: "module-readiness",
    fromRoute: "/deployment-environment-readiness",
    toRoute: "/module-readiness",
    eventType: "deployment.environment.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "deployment-environment-readiness-to-governance",
    fromModuleId: "deployment-environment-readiness",
    toModuleId: "governance",
    fromRoute: "/deployment-environment-readiness",
    toRoute: "/governance",
    eventType: "deployment.environment.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "deployment-environment-readiness-to-release-candidate-freeze",
    fromModuleId: "deployment-environment-readiness",
    toModuleId: "release-candidate-freeze",
    fromRoute: "/deployment-environment-readiness",
    toRoute: "/release-candidate-freeze",
    eventType: "deployment.environment.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "release-candidate-freeze-to-module-readiness",
    fromModuleId: "release-candidate-freeze",
    toModuleId: "module-readiness",
    fromRoute: "/release-candidate-freeze",
    toRoute: "/module-readiness",
    eventType: "release.candidate.freeze.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "release-candidate-freeze-to-governance",
    fromModuleId: "release-candidate-freeze",
    toModuleId: "governance",
    fromRoute: "/release-candidate-freeze",
    toRoute: "/governance",
    eventType: "release.candidate.freeze.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "release-candidate-freeze-to-production-cutover-hold",
    fromModuleId: "release-candidate-freeze",
    toModuleId: "production-cutover-hold",
    fromRoute: "/release-candidate-freeze",
    toRoute: "/production-cutover-hold",
    eventType: "release.candidate.freeze.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-cutover-hold-to-module-readiness",
    fromModuleId: "production-cutover-hold",
    toModuleId: "module-readiness",
    fromRoute: "/production-cutover-hold",
    toRoute: "/module-readiness",
    eventType: "production.cutover.hold.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-cutover-hold-to-production-release-board",
    fromModuleId: "production-cutover-hold",
    toModuleId: "production-release-board",
    fromRoute: "/production-cutover-hold",
    toRoute: "/production-release-board",
    eventType: "production.cutover.hold.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-release-board-to-module-readiness",
    fromModuleId: "production-release-board",
    toModuleId: "module-readiness",
    fromRoute: "/production-release-board",
    toRoute: "/module-readiness",
    eventType: "production.release.board.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-release-board-to-production-operations-monitoring",
    fromModuleId: "production-release-board",
    toModuleId: "production-operations-monitoring",
    fromRoute: "/production-release-board",
    toRoute: "/production-operations-monitoring",
    eventType: "production.release.board.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-operations-monitoring-to-production-incident-response-readiness",
    fromModuleId: "production-operations-monitoring",
    toModuleId: "production-incident-response-readiness",
    fromRoute: "/production-operations-monitoring",
    toRoute: "/production-incident-response-readiness",
    eventType: "production.operations.monitoring.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-operations-monitoring-to-module-readiness",
    fromModuleId: "production-operations-monitoring",
    toModuleId: "module-readiness",
    fromRoute: "/production-operations-monitoring",
    toRoute: "/module-readiness",
    eventType: "production.operations.monitoring.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-operations-monitoring-to-governance",
    fromModuleId: "production-operations-monitoring",
    toModuleId: "governance",
    fromRoute: "/production-operations-monitoring",
    toRoute: "/governance",
    eventType: "production.operations.monitoring.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-incident-response-readiness-to-module-readiness",
    fromModuleId: "production-incident-response-readiness",
    toModuleId: "module-readiness",
    fromRoute: "/production-incident-response-readiness",
    toRoute: "/module-readiness",
    eventType: "production.incident.response.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-incident-response-readiness-to-production-support-communications-readiness",
    fromModuleId: "production-incident-response-readiness",
    toModuleId: "production-support-communications-readiness",
    fromRoute: "/production-incident-response-readiness",
    toRoute: "/production-support-communications-readiness",
    eventType: "production.incident.response.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-support-communications-readiness-to-production-final-authority",
    fromModuleId: "production-support-communications-readiness",
    toModuleId: "production-final-authority",
    fromRoute: "/production-support-communications-readiness",
    toRoute: "/production-final-authority",
    eventType: "production.support.communications.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-final-authority-to-module-readiness",
    fromModuleId: "production-final-authority",
    toModuleId: "module-readiness",
    fromRoute: "/production-final-authority",
    toRoute: "/module-readiness",
    eventType: "production.final.authority.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-final-authority-to-production-activation-ceremony",
    fromModuleId: "production-final-authority",
    toModuleId: "production-activation-ceremony",
    fromRoute: "/production-final-authority",
    toRoute: "/production-activation-ceremony",
    eventType: "production.final.authority.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-activation-ceremony-to-module-readiness",
    fromModuleId: "production-activation-ceremony",
    toModuleId: "module-readiness",
    fromRoute: "/production-activation-ceremony",
    toRoute: "/module-readiness",
    eventType: "production.activation.ceremony.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-activation-ceremony-to-production-post-activation-verification",
    fromModuleId: "production-activation-ceremony",
    toModuleId: "production-post-activation-verification",
    fromRoute: "/production-activation-ceremony",
    toRoute: "/production-post-activation-verification",
    eventType: "production.activation.ceremony.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-post-activation-verification-to-module-readiness",
    fromModuleId: "production-post-activation-verification",
    toModuleId: "module-readiness",
    fromRoute: "/production-post-activation-verification",
    toRoute: "/module-readiness",
    eventType: "production.post.activation.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-post-activation-verification-to-production-reliance-verification",
    fromModuleId: "production-post-activation-verification",
    toModuleId: "production-reliance-verification",
    fromRoute: "/production-post-activation-verification",
    toRoute: "/production-reliance-verification",
    eventType: "production.post.activation.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-post-activation-verification-to-governance",
    fromModuleId: "production-post-activation-verification",
    toModuleId: "governance",
    fromRoute: "/production-post-activation-verification",
    toRoute: "/governance",
    eventType: "production.post.activation.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-reliance-verification-to-module-readiness",
    fromModuleId: "production-reliance-verification",
    toModuleId: "module-readiness",
    fromRoute: "/production-reliance-verification",
    toRoute: "/module-readiness",
    eventType: "production.reliance.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-reliance-verification-to-production-regulatory-examination",
    fromModuleId: "production-reliance-verification",
    toModuleId: "production-regulatory-examination",
    fromRoute: "/production-reliance-verification",
    toRoute: "/production-regulatory-examination",
    eventType: "production.reliance.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-reliance-verification-to-governance",
    fromModuleId: "production-reliance-verification",
    toModuleId: "governance",
    fromRoute: "/production-reliance-verification",
    toRoute: "/governance",
    eventType: "production.reliance.verification.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-examination-to-module-readiness",
    fromModuleId: "production-regulatory-examination",
    toModuleId: "module-readiness",
    fromRoute: "/production-regulatory-examination",
    toRoute: "/module-readiness",
    eventType: "production.regulatory.examination.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-examination-to-governance",
    fromModuleId: "production-regulatory-examination",
    toModuleId: "governance",
    fromRoute: "/production-regulatory-examination",
    toRoute: "/governance",
    eventType: "production.regulatory.examination.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-examination-to-production-regulatory-response",
    fromModuleId: "production-regulatory-examination",
    toModuleId: "production-regulatory-response",
    fromRoute: "/production-regulatory-examination",
    toRoute: "/production-regulatory-response",
    eventType: "production.regulatory.examination.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-response-to-module-readiness",
    fromModuleId: "production-regulatory-response",
    toModuleId: "module-readiness",
    fromRoute: "/production-regulatory-response",
    toRoute: "/module-readiness",
    eventType: "production.regulatory.response.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-response-to-governance",
    fromModuleId: "production-regulatory-response",
    toModuleId: "governance",
    fromRoute: "/production-regulatory-response",
    toRoute: "/governance",
    eventType: "production.regulatory.response.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-regulatory-response-to-build-preservation",
    fromModuleId: "production-regulatory-response",
    toModuleId: "build-preservation",
    fromRoute: "/production-regulatory-response",
    toRoute: "/build-preservation",
    eventType: "production.regulatory.response.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "build-preservation-to-module-readiness",
    fromModuleId: "build-preservation",
    toModuleId: "module-readiness",
    fromRoute: "/build-preservation",
    toRoute: "/module-readiness",
    eventType: "build.preservation.archived",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "build-preservation-to-governance",
    fromModuleId: "build-preservation",
    toModuleId: "governance",
    fromRoute: "/build-preservation",
    toRoute: "/governance",
    eventType: "build.preservation.archived",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "build-preservation-to-doctrine-gap-ledger",
    fromModuleId: "build-preservation",
    toModuleId: "doctrine-gap-ledger",
    fromRoute: "/build-preservation",
    toRoute: "/doctrine-gap-ledger",
    eventType: "build.preservation.archived",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "doctrine-gap-ledger-to-module-readiness",
    fromModuleId: "doctrine-gap-ledger",
    toModuleId: "module-readiness",
    fromRoute: "/doctrine-gap-ledger",
    toRoute: "/module-readiness",
    eventType: "doctrine.gap.ledger.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "doctrine-gap-ledger-to-governance",
    fromModuleId: "doctrine-gap-ledger",
    toModuleId: "governance",
    fromRoute: "/doctrine-gap-ledger",
    toRoute: "/governance",
    eventType: "doctrine.gap.ledger.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "doctrine-gap-ledger-to-promotion",
    fromModuleId: "doctrine-gap-ledger",
    toModuleId: "promotion",
    fromRoute: "/doctrine-gap-ledger",
    toRoute: "/promotion",
    eventType: "doctrine.gap.ledger.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "doctrine-gap-ledger-to-operator-demo",
    fromModuleId: "doctrine-gap-ledger",
    toModuleId: "operator-demo",
    fromRoute: "/doctrine-gap-ledger",
    toRoute: "/operator-demo",
    eventType: "doctrine.gap.ledger.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-activation-ceremony-to-governance",
    fromModuleId: "production-activation-ceremony",
    toModuleId: "governance",
    fromRoute: "/production-activation-ceremony",
    toRoute: "/governance",
    eventType: "production.activation.ceremony.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-final-authority-to-governance",
    fromModuleId: "production-final-authority",
    toModuleId: "governance",
    fromRoute: "/production-final-authority",
    toRoute: "/governance",
    eventType: "production.final.authority.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-support-communications-readiness-to-module-readiness",
    fromModuleId: "production-support-communications-readiness",
    toModuleId: "module-readiness",
    fromRoute: "/production-support-communications-readiness",
    toRoute: "/module-readiness",
    eventType: "production.support.communications.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-support-communications-readiness-to-governance",
    fromModuleId: "production-support-communications-readiness",
    toModuleId: "governance",
    fromRoute: "/production-support-communications-readiness",
    toRoute: "/governance",
    eventType: "production.support.communications.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-incident-response-readiness-to-governance",
    fromModuleId: "production-incident-response-readiness",
    toModuleId: "governance",
    fromRoute: "/production-incident-response-readiness",
    toRoute: "/governance",
    eventType: "production.incident.response.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-release-board-to-governance",
    fromModuleId: "production-release-board",
    toModuleId: "governance",
    fromRoute: "/production-release-board",
    toRoute: "/governance",
    eventType: "production.release.board.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "production-cutover-hold-to-governance",
    fromModuleId: "production-cutover-hold",
    toModuleId: "governance",
    fromRoute: "/production-cutover-hold",
    toRoute: "/governance",
    eventType: "production.cutover.hold.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-production-readiness-to-module-readiness",
    fromModuleId: "source-production-readiness",
    toModuleId: "module-readiness",
    fromRoute: "/source-production-readiness",
    toRoute: "/module-readiness",
    eventType: "source.production.readiness.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-promotion-packets-to-module-readiness",
    fromModuleId: "source-promotion-packets",
    toModuleId: "module-readiness",
    fromRoute: "/source-promotion-packets",
    toRoute: "/module-readiness",
    eventType: "source.promotion.packet.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "live-scraper-activation-to-module-readiness",
    fromModuleId: "live-scraper-activation",
    toModuleId: "module-readiness",
    fromRoute: "/live-scraper-activation",
    toRoute: "/module-readiness",
    eventType: "scraper.activation.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "environmental-compliance-to-evidence-packets",
    fromModuleId: "environmental-compliance",
    toModuleId: "evidence-packets",
    fromRoute: "/environmental-compliance",
    toRoute: "/evidence-packets",
    eventType: "environmental.compliance.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-portal-property-discovery",
    fromModuleId: "source-ingestion",
    toModuleId: "portal-property-discovery",
    fromRoute: "/source-ingestion",
    toRoute: "/portal/property-discovery",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-lender-property-opportunities",
    fromModuleId: "source-ingestion",
    toModuleId: "lender-property-opportunities",
    fromRoute: "/source-ingestion",
    toRoute: "/lender/property-opportunities",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-sponsor-project-discovery",
    fromModuleId: "source-ingestion",
    toModuleId: "sponsor-project-discovery",
    fromRoute: "/source-ingestion",
    toRoute: "/sponsor/project-discovery",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "source-ingestion-to-customer-revenue",
    fromModuleId: "source-ingestion",
    toModuleId: "customer-revenue",
    fromRoute: "/source-ingestion",
    toRoute: "/customer-revenue",
    eventType: "source.ingestion.gate.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "customer-revenue-to-portal-revenue-opportunities",
    fromModuleId: "customer-revenue",
    toModuleId: "portal-revenue-opportunities",
    fromRoute: "/customer-revenue",
    toRoute: "/portal/revenue-opportunities",
    eventType: "revenue.opportunity.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "customer-revenue-to-lender-revenue-opportunities",
    fromModuleId: "customer-revenue",
    toModuleId: "lender-revenue-opportunities",
    fromRoute: "/customer-revenue",
    toRoute: "/lender/revenue-opportunities",
    eventType: "revenue.opportunity.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "customer-revenue-to-sponsor-revenue-opportunities",
    fromModuleId: "customer-revenue",
    toModuleId: "sponsor-revenue-opportunities",
    fromRoute: "/customer-revenue",
    toRoute: "/sponsor/revenue-opportunities",
    eventType: "revenue.opportunity.reviewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "notices-to-audit-replay",
    fromModuleId: "notices",
    toModuleId: "audit-replay",
    fromRoute: "/notices",
    toRoute: "/audit-replay",
    eventType: "notice.packet.prepared",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "audit-replay-to-evidence-packets",
    fromModuleId: "audit-replay",
    toModuleId: "evidence-packets",
    fromRoute: "/audit-replay",
    toRoute: "/evidence-packets",
    eventType: "audit.replay.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "evidence-packets-to-module-readiness",
    fromModuleId: "evidence-packets",
    toModuleId: "module-readiness",
    fromRoute: "/evidence-packets",
    toRoute: "/module-readiness",
    eventType: "evidence.packet.prepared",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "data-rights-to-reports",
    fromModuleId: "data-rights",
    toModuleId: "reports",
    fromRoute: "/data-rights",
    toRoute: "/reports",
    eventType: "data.rights.export.prepared",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "module-readiness-to-promotion",
    fromModuleId: "module-readiness",
    toModuleId: "promotion",
    fromRoute: "/module-readiness",
    toRoute: "/promotion",
    eventType: "module.readiness.checked",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-onboarding-to-readiness",
    fromModuleId: "portal-borrower-onboarding",
    toModuleId: "portal-borrower-readiness",
    fromRoute: "/onboarding",
    toRoute: "/readiness",
    eventType: "borrower.onboarding.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "financing-pathways-to-readiness",
    fromModuleId: "portal-borrower-financing-pathways",
    toModuleId: "portal-borrower-readiness",
    fromRoute: "/financing-pathways",
    toRoute: "/readiness",
    eventType: "financing.pathway.evaluated",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-readiness-to-applications",
    fromModuleId: "portal-borrower-readiness",
    toModuleId: "portal-borrower-applications",
    fromRoute: "/readiness",
    toRoute: "/portal/borrower/applications",
    eventType: "borrower.readiness.assessed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-readiness-to-documents",
    fromModuleId: "portal-borrower-readiness",
    toModuleId: "portal-borrower-documents",
    fromRoute: "/readiness",
    toRoute: "/portal/borrower/documents",
    eventType: "borrower.readiness.assessed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-readiness-to-data-rights",
    fromModuleId: "portal-borrower-readiness",
    toModuleId: "portal-borrower-data-rights",
    fromRoute: "/readiness",
    toRoute: "/portal/borrower/data-rights",
    eventType: "borrower.readiness.assessed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-onboarding-to-environmental-intake",
    fromModuleId: "portal-borrower-onboarding",
    toModuleId: "portal-borrower-environmental-intake",
    fromRoute: "/onboarding",
    toRoute: "/portal/borrower/environmental-intake",
    eventType: "borrower.onboarding.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-environmental-intake-to-environmental-compliance",
    fromModuleId: "portal-borrower-environmental-intake",
    toModuleId: "environmental-compliance",
    fromRoute: "/portal/borrower/environmental-intake",
    toRoute: "/environmental-compliance",
    eventType: "borrower.environmental.intake.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-environmental-intake-to-applications",
    fromModuleId: "portal-borrower-environmental-intake",
    toModuleId: "portal-borrower-applications",
    fromRoute: "/portal/borrower/environmental-intake",
    toRoute: "/portal/borrower/applications",
    eventType: "borrower.environmental.intake.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-environmental-intake-to-documents",
    fromModuleId: "portal-borrower-environmental-intake",
    toModuleId: "portal-borrower-documents",
    fromRoute: "/portal/borrower/environmental-intake",
    toRoute: "/portal/borrower/documents",
    eventType: "borrower.environmental.intake.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-environmental-intake-to-readiness",
    fromModuleId: "portal-borrower-environmental-intake",
    toModuleId: "portal-borrower-readiness",
    fromRoute: "/portal/borrower/environmental-intake",
    toRoute: "/readiness",
    eventType: "borrower.environmental.intake.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-environmental-intake-to-data-rights",
    fromModuleId: "portal-borrower-environmental-intake",
    toModuleId: "portal-borrower-data-rights",
    fromRoute: "/portal/borrower/environmental-intake",
    toRoute: "/portal/borrower/data-rights",
    eventType: "borrower.environmental.intake.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-onboarding-to-opportunities",
    fromModuleId: "portal-borrower-onboarding",
    toModuleId: "portal-borrower-opportunities",
    fromRoute: "/onboarding",
    toRoute: "/portal/borrower/opportunities",
    eventType: "borrower.onboarding.submitted",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-readiness-to-opportunities",
    fromModuleId: "portal-borrower-readiness",
    toModuleId: "portal-borrower-opportunities",
    fromRoute: "/readiness",
    toRoute: "/portal/borrower/opportunities",
    eventType: "borrower.readiness.assessed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-opportunities-to-revenue-opportunities",
    fromModuleId: "portal-borrower-opportunities",
    toModuleId: "portal-revenue-opportunities",
    fromRoute: "/portal/borrower/opportunities",
    toRoute: "/portal/revenue-opportunities",
    eventType: "borrower.opportunity.discovery.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-opportunities-to-property-discovery",
    fromModuleId: "portal-borrower-opportunities",
    toModuleId: "portal-property-discovery",
    fromRoute: "/portal/borrower/opportunities",
    toRoute: "/portal/property-discovery",
    eventType: "borrower.opportunity.discovery.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-opportunities-to-readiness",
    fromModuleId: "portal-borrower-opportunities",
    toModuleId: "portal-borrower-readiness",
    fromRoute: "/portal/borrower/opportunities",
    toRoute: "/readiness",
    eventType: "borrower.opportunity.discovery.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "borrower-opportunities-to-data-rights",
    fromModuleId: "portal-borrower-opportunities",
    toModuleId: "portal-borrower-data-rights",
    fromRoute: "/portal/borrower/opportunities",
    toRoute: "/portal/borrower/data-rights",
    eventType: "borrower.opportunity.discovery.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "public-trust-to-data-rights",
    fromModuleId: "public-trust",
    toModuleId: "portal-borrower-data-rights",
    fromRoute: "/trust",
    toRoute: "/portal/borrower/data-rights",
    eventType: "public.trust.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "public-trust-to-readiness",
    fromModuleId: "public-trust",
    toModuleId: "portal-borrower-readiness",
    fromRoute: "/trust",
    toRoute: "/readiness",
    eventType: "public.trust.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "public-trust-to-financing-pathways",
    fromModuleId: "public-trust",
    toModuleId: "portal-borrower-financing-pathways",
    fromRoute: "/trust",
    toRoute: "/financing-pathways",
    eventType: "public.trust.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-applications",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-applications",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/applications",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-overlays",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-overlays",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/overlays",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-evidence",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-evidence",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/evidence",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-property-opportunities",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-property-opportunities",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/property-opportunities",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-revenue-opportunities",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-revenue-opportunities",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/revenue-opportunities",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-dashboard",
    fromModuleId: "lender-workflow",
    toModuleId: "lender-dashboard",
    fromRoute: "/lender/workflow",
    toRoute: "/lender/dashboard",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "lender-workflow-to-partners",
    fromModuleId: "lender-workflow",
    toModuleId: "partners",
    fromRoute: "/lender/workflow",
    toRoute: "/partners",
    eventType: "lender.workflow.viewed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-evidence-packets",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "evidence-packets",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/evidence-packets",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-audit-replay",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "audit-replay",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/audit-replay",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-governance",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "governance",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/governance",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-reviews",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "reviews",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/reviews",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-module-readiness",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "module-readiness",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/module-readiness",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
  {
    id: "governance-evidence-engine-to-lender-evidence",
    fromModuleId: "governance-evidence-engine",
    toModuleId: "lender-evidence",
    fromRoute: "/governance/evidence-engine",
    toRoute: "/lender/evidence",
    eventType: "governance.evidence.pack.composed",
    replayRequired: true,
    humanReviewBoundary: true,
    productionBlocked: true,
  },
];

export function handoffsForModule(moduleId: string): ModuleHandoff[] {
  return crossModuleHandoffMap.filter(
    (handoff) =>
      handoff.fromModuleId === moduleId || handoff.toModuleId === moduleId
  );
}
