/**
 * Portable Vertical Surface Registry
 *
 * Master Volume Governance:
 * - Vol 0: separates internal, borrower, lender, and sponsor experiences while
 *   preserving one platform orientation.
 * - Vol I: keeps constitutional boundaries and accountable authority attached
 *   to every vertical surface.
 * - Vol II: prevents borrower, lender, sponsor, notice, payment, report, and
 *   agency-facing surfaces from implying final regulated action.
 * - Vol III: requires each surface to consume governed backend APIs rather than
 *   bypassing ledger, replay, schema, or evidence controls.
 * - Vol III-B: carries classification, permission, observability, and runtime
 *   posture into each vertical.
 * - Vol IV: supports operational handoff, escalation, recovery, and training.
 * - Vol V: keeps claims, portability, source authority, classification,
 *   explainability, and controlled disclosure consistent across modules.
 */

export type PortableSurfaceAudience =
  | "internal"
  | "borrower"
  | "lender"
  | "sponsor";

export type PortableVerticalSurface = {
  id: string;
  label: string;
  route: string;
  audience: PortableSurfaceAudience;
  moduleRefs: string[];
  purpose: string;
  primaryStatus: string;
  safeMessages: string[];
  requiredBackendSurfaces: string[];
  governanceRequirements: string[];
  productionBlocks: string[];
  adjacentRoutes: string[];
};

export const publicSurfaceDisclosureMessages = [
  "Advisory only.",
  "No approval has been granted.",
  "No guarantee is made.",
  "No legal or regulatory reliance is authorized.",
  "No public verification is available unless separately authorized.",
] as const;

export const portableSurfaceSafeMessages = [
  "Your document was received.",
  "Human review is pending.",
  "More information may be needed.",
  ...publicSurfaceDisclosureMessages,
] as const;

function portableSafeMessagesWith(...messages: string[]): string[] {
  return Array.from(new Set<string>([...portableSurfaceSafeMessages, ...messages]));
}

export const portableSurfaceGovernanceRequirements = [
  "Master Volume governance alignment",
  "role and record-level permission checks",
  "classification metadata",
  "content-claims review",
  "version lineage",
  "observability and audit evidence",
  "replay reference or replay-safe read posture",
  "human review boundary",
] as const;

export const portableSurfaceProductionBlocks = [
  "advisory only",
  "no approval",
  "no guarantee",
  "no legal or regulatory reliance",
  "no official report publication",
  "no final lending decision",
  "no borrower notice send",
  "no live external agency call",
  "no source promotion without qualified approval",
  "no release-candidate freeze approval",
  "no production cutover approval",
  "no production release board approval",
  "no payment capture",
  "no raw document-content processing",
  "no public verification claim",
  "no public verification unless authorized",
] as const;

const internalBackendSurfaces = [
  "/api/applications/admin",
  "/api/documents/admin",
  "/api/reviews/admin",
  "/api/rules/admin",
  "/api/reports/admin",
] as const;

export const internalPortableSurfaces: PortableVerticalSurface[] = [
  {
    id: "internal-governance",
    label: "Governance Operations",
    route: "/governance",
    audience: "internal",
    moduleRefs: ["Module 01"],
    purpose: "Internal governance, audit posture, content claims, and live-action holds.",
    primaryStatus: "Internal governance active.",
    safeMessages: [...portableSurfaceSafeMessages],
    requiredBackendSurfaces: ["/api/ledger/admin", "/api/audit/export"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/audit-replay", "/module-readiness"],
  },
  {
    id: "internal-operations",
    label: "Operations Modules",
    route: "/module-readiness",
    audience: "internal",
    moduleRefs: ["Modules 02-42"],
    purpose:
      "Internal operational control surfaces for applications, queues, documents, reviews, rules, notices, connectors, partners, billing, reports, promotion, evidence, ingestion, environmental compliance, live scraper activation, source legal review, source promotion packets, source production readiness, controlled promotion activation, production portal readiness, production launch evidence, deployment environment readiness, release-candidate freeze, production cutover hold, production release board, production operations monitoring, production incident response readiness, production support communications readiness, production final authority, production activation ceremony, production post-activation verification, production reliance verification, production regulatory examination, production regulatory response, build preservation, exceptions, data rights, and readiness.",
    primaryStatus: "Modules 01-42 are available for governed internal operation.",
    safeMessages: [...portableSurfaceSafeMessages],
    requiredBackendSurfaces: [...internalBackendSurfaces],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: [
      "/operator-demo",
      "/case-command",
      "/environmental-compliance",
      "/live-scraper-activation",
      "/source-legal-review",
      "/source-promotion-packets",
      "/source-production-readiness",
      "/controlled-promotion-activation",
      "/production-portal-readiness",
      "/production-launch-evidence",
      "/deployment-environment-readiness",
      "/release-candidate-freeze",
      "/production-cutover-hold",
      "/production-release-board",
      "/production-operations-monitoring",
      "/production-incident-response-readiness",
      "/production-support-communications-readiness",
      "/production-final-authority",
      "/production-activation-ceremony",
      "/production-post-activation-verification",
      "/production-reliance-verification",
      "/production-regulatory-examination",
      "/production-regulatory-response",
      "/build-preservation",
    ],
  },
  {
    id: "internal-environmental-compliance",
    label: "Environmental Compliance Review",
    route: "/environmental-compliance",
    audience: "internal",
    moduleRefs: ["Module 21"],
    purpose:
      "Internal environmental pathway, provider-license, fee-control, spoke-isolation, and audit-anchor review.",
    primaryStatus: "Environmental compliance review is advisory and human-review bound.",
    safeMessages: portableSafeMessagesWith(
      "No official environmental report has been generated.",
      "No live environmental provider action has been performed."
    ),
    requiredBackendSurfaces: [
      "/api/governance/environmental-compliance",
      "/api/governance/environmental-compliance/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "provider-license verification",
      "borrower fee autonomy",
      "spoke isolation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no official environmental assessment",
      "no live environmental provider engagement",
    ],
    adjacentRoutes: [
      "/applications",
      "/source-ingestion",
      "/promotion",
      "/evidence-packets",
    ],
  },
  {
    id: "internal-live-scraper-activation",
    label: "Live Scraper Activation Gate",
    route: "/live-scraper-activation",
    audience: "internal",
    moduleRefs: ["Module 22"],
    purpose:
      "Internal source activation-readiness review for scraper registry, source-stack profile, legal/ToS, credential, adapter, replay, monitoring, rollback, and human approval evidence.",
    primaryStatus: "Live scraper activation is blocked until all governed evidence gates pass.",
    safeMessages: portableSafeMessagesWith(
      "No live external source has been contacted.",
      "No public verification authority has been granted."
    ),
    requiredBackendSurfaces: [
      "/api/governance/live-scraper-activation",
      "/api/scrapers",
      "/api/source-stack",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "source authority review",
      "source-specific legal and ToS review",
      "live-action readiness review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no live source fetch",
      "no source activation without human promotion approval",
    ],
    adjacentRoutes: ["/source-ingestion", "/connectors", "/promotion"],
  },
  {
    id: "internal-source-legal-review",
    label: "Source Legal and Licensing Review Gate",
    route: "/source-legal-review",
    audience: "internal",
    moduleRefs: ["Module 23"],
    purpose:
      "Internal source-specific ToS, licensing, anti-bulk, retention, republication, permitted-use, public DTO, and qualified-review evidence surface.",
    primaryStatus:
      "Source legal and licensing review is blocked until qualified review evidence is recorded.",
    safeMessages: portableSafeMessagesWith(
      "No legal advice has been provided.",
      "No live external source has been contacted."
    ),
    requiredBackendSurfaces: [
      "/api/governance/source-legal-review",
      "/api/source-stack",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "source-specific legal and ToS review",
      "anti-bulk acquisition review",
      "public DTO and redaction review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no legal advice",
      "no live source fetch",
      "no source activation without qualified review",
    ],
    adjacentRoutes: [
      "/source-ingestion",
      "/connectors",
      "/live-scraper-activation",
      "/source-promotion-packets",
      "/promotion",
    ],
  },
  {
    id: "internal-source-promotion-packets",
    label: "Source Promotion Packet Gate",
    route: "/source-promotion-packets",
    audience: "internal",
    moduleRefs: ["Module 24"],
    purpose:
      "Internal source promotion packet review for source-stack, legal, activation, replay, provenance, credential, adapter, monitoring, rollback, incident, and human approval evidence.",
    primaryStatus:
      "Source promotion packets are blocked until qualified source-specific approval is recorded.",
    safeMessages: portableSafeMessagesWith(
      "No legal advice has been provided.",
      "No live external source has been contacted.",
      "No public verification authority has been granted."
    ),
    requiredBackendSurfaces: [
      "/api/governance/source-promotion-packets",
      "/api/governance/source-legal-review",
      "/api/governance/live-scraper-activation",
      "/api/source-stack",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "source-specific legal and ToS review",
      "live adapter certification review",
      "replay and provenance certification",
      "rollback and incident response review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no legal advice",
      "no live source fetch",
      "no public verification claim",
      "no source promotion without qualified approval",
    ],
    adjacentRoutes: [
      "/source-legal-review",
      "/live-scraper-activation",
      "/source-ingestion",
      "/connectors",
      "/source-production-readiness",
      "/promotion",
    ],
  },
  {
    id: "internal-source-production-readiness",
    label: "Source Production Promotion Readiness Gate",
    route: "/source-production-readiness",
    audience: "internal",
    moduleRefs: ["Module 25"],
    purpose:
      "Internal final controlled-promotion readiness review for source promotion packets, credentials, adapters, schema, replay, provenance, monitoring, failover, rollback, incident, audit, claims, activation ceremony, kill switch, and human approval evidence.",
    primaryStatus:
      "Source production promotion remains blocked until controlled promotion and qualified source-specific approval are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No legal advice has been provided.",
      "No live external source has been contacted.",
      "No public verification authority has been granted.",
      "No source has been promoted to production."
    ),
    requiredBackendSurfaces: [
      "/api/governance/source-production-readiness",
      "/api/governance/source-promotion-packets",
      "/api/governance/source-legal-review",
      "/api/governance/live-scraper-activation",
      "/api/source-stack",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "controlled production promotion review",
      "qualified source-specific approval",
      "activation ceremony approval",
      "kill switch and rollback review",
      "audit export and evidence retention review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no legal advice",
      "no live source fetch",
      "no public verification claim",
      "no source production promotion without qualified approval",
      "no activation ceremony execution",
    ],
    adjacentRoutes: [
      "/source-promotion-packets",
      "/source-legal-review",
      "/live-scraper-activation",
      "/connectors",
      "/controlled-promotion-activation",
      "/promotion",
    ],
  },
  {
    id: "internal-controlled-promotion-activation",
    label: "Controlled Promotion Activation Gate",
    route: "/controlled-promotion-activation",
    audience: "internal",
    moduleRefs: ["Module 26"],
    purpose:
      "Internal activation ceremony review for source production readiness, change records, approver quorum, environment lock, credentials, adapters, schema, replay, provenance, monitoring, rollback, incident response, audit, claims, kill switch, and post-activation verification evidence.",
    primaryStatus:
      "Controlled promotion activation remains blocked until final qualified approval and ceremony controls are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No legal advice has been provided.",
      "No live external source has been contacted.",
      "No public verification authority has been granted.",
      "No source has been promoted to production.",
      "No activation ceremony has been executed."
    ),
    requiredBackendSurfaces: [
      "/api/governance/controlled-promotion-activation",
      "/api/governance/source-production-readiness",
      "/api/governance/source-promotion-packets",
      "/api/governance/source-legal-review",
      "/api/governance/live-scraper-activation",
      "/api/source-stack",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "controlled activation ceremony review",
      "approver quorum and accountable authority",
      "production environment lock",
      "kill switch and emergency hold review",
      "post-activation verification plan",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no legal advice",
      "no live source fetch",
      "no public verification claim",
      "no source production promotion without qualified approval",
      "no activation ceremony execution",
    ],
    adjacentRoutes: [
      "/source-production-readiness",
      "/source-promotion-packets",
      "/live-scraper-activation",
      "/connectors",
      "/promotion",
      "/production-portal-readiness",
    ],
  },
  {
    id: "internal-production-portal-readiness",
    label: "Production Portal Readiness Preflight Gate",
    route: "/production-portal-readiness",
    audience: "internal",
    moduleRefs: ["Module 27"],
    purpose:
      "Internal launch preflight review for portable vertical surfaces, backend dependency readiness, auth, security, audit, replay, claims, monitoring, rollback, incident, support routing, public-copy freeze, and final launch-hold evidence.",
    primaryStatus:
      "Production portal launch remains blocked until qualified final approval and controlled production launch controls are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No live external source has been contacted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-portal-readiness",
      "/api/governance/controlled-promotion-activation",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production auth activation gate",
      "security and audit readiness gate",
      "production backend readiness gate",
      "controlled promotion activation evidence",
      "content claims review",
      "public copy freeze",
      "operator launch checklist and support routing",
      "monitoring, incident, and rollback review",
      "final no-live-action launch hold",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no production portal launch",
      "no public production API exposure",
      "no public verification authority",
      "no official reliance",
      "no launch approval without qualified approval",
    ],
    adjacentRoutes: [
      "/controlled-promotion-activation",
      "/module-readiness",
      "/production-launch-evidence",
      "/governance",
      "/portal/borrower",
      "/lender/dashboard",
      "/sponsor/dashboard",
    ],
  },
  {
    id: "internal-production-launch-evidence",
    label: "Production Launch Evidence Packet",
    route: "/production-launch-evidence",
    audience: "internal",
    moduleRefs: ["Module 28"],
    purpose:
      "Internal go-live evidence packet for launch proof, production portal readiness, backend, auth, security, audit, replay, claims, monitoring, rollback, incident, support routing, public-copy freeze, and final launch-hold evidence.",
    primaryStatus:
      "Go-live release remains blocked until qualified final approval, public-copy freeze, and final launch-hold release are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No live external source has been contacted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No go-live release has been approved."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/governance/controlled-promotion-activation",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production portal readiness preflight evidence",
      "production auth activation gate",
      "security and audit readiness gate",
      "production backend readiness gate",
      "content claims and public copy freeze",
      "record access, redaction, replay, and audit export freeze",
      "monitoring, incident, rollback, and emergency hold review",
      "operator support and escalation review",
      "qualified human release ceremony",
      "final launch hold release",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no production portal launch",
      "no public production API exposure",
      "no public verification authority",
      "no official reliance",
      "no go-live release without qualified approval",
      "no launch hold release without qualified approval",
    ],
    adjacentRoutes: [
      "/production-portal-readiness",
      "/deployment-environment-readiness",
      "/release-candidate-freeze",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-operations-monitoring",
    ],
  },
  {
    id: "internal-production-operations-monitoring",
    label: "Production Operations Monitoring Gate",
    route: "/production-operations-monitoring",
    audience: "internal",
    moduleRefs: ["Module 33"],
    purpose:
      "Internal production operations monitoring review for monitoring, alerting, SLO, on-call, incident bridge, rollback, backup, restore, support, communications, audit export, emergency hold, and kill-switch evidence.",
    primaryStatus:
      "Production operations monitoring approval, monitoring activation, on-call activation, incident bridge activation, rollback authorization, emergency hold release, cutover authority, deployment, public production exposure, and portal launch remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No production operations monitoring approval has been granted.",
      "No production monitoring, paging, or on-call activation has been approved.",
      "No incident bridge has been activated for production launch.",
      "No rollback authorization has been granted.",
      "No emergency hold has been released.",
      "No production release board approval has been granted.",
      "No production cutover authority has been granted.",
      "No production cutover has been approved or executed.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "This gate is production operations monitoring review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production release board evidence",
      "monitoring, alerting, and SLO review",
      "on-call roster and escalation review",
      "incident bridge and severity model review",
      "rollback drill and recovery review",
      "backup, restore, and disaster recovery review",
      "audit export and replay evidence review",
      "support routing and communications freeze",
      "emergency hold and kill-switch authority review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no operations monitoring approval",
      "no production monitoring activation",
      "no on-call activation",
      "no incident bridge activation",
      "no rollback authorization",
      "no emergency hold release",
      "no cutover authority grant",
      "no production cutover approval",
      "no production cutover execution",
      "no deployment execution",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no production portal launch",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/production-release-board",
      "/production-cutover-hold",
      "/deployment-environment-readiness",
      "/production-launch-evidence",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-incident-response-readiness",
    ],
  },
  {
    id: "internal-production-incident-response-readiness",
    label: "Production Incident Response Readiness Gate",
    route: "/production-incident-response-readiness",
    audience: "internal",
    moduleRefs: ["Module 34"],
    purpose:
      "Internal production incident response readiness review for incident command, severity, escalation, incident bridge, rollback, data integrity, replay, support, communications, public status, emergency hold, and kill-switch evidence.",
    primaryStatus:
      "Incident response approval, incident activation, incident bridge activation, rollback authorization, emergency rollback, emergency hold release, kill-switch activation, customer communications, public status page, support escalation, cutover authority, deployment, public production exposure, and portal launch remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No production incident response approval has been granted.",
      "No incident response activation has been approved.",
      "No incident bridge has been activated for production launch.",
      "No on-call activation has been approved.",
      "No rollback authorization has been granted.",
      "No emergency rollback has been executed.",
      "No emergency hold has been released.",
      "No kill-switch activation has been executed.",
      "No customer communication has been released.",
      "No regulatory communication has been released.",
      "No public status page has been enabled.",
      "No support escalation has been activated.",
      "No production operations monitoring approval has been granted.",
      "No production cutover authority has been granted.",
      "No production cutover has been approved or executed.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "This gate is production incident response readiness review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/incidents/create",
      "/api/incidents/escalate",
      "/api/incidents/status",
      "/api/incidents/resolve",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production operations monitoring evidence",
      "incident command roles review",
      "severity model and triage review",
      "on-call escalation path review",
      "incident bridge and communications review",
      "rollback decision tree review",
      "data integrity, replay, and audit evidence review",
      "customer-safe communication and status review",
      "regulatory and legal escalation review",
      "emergency hold and kill-switch authority review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no incident response approval",
      "no incident response activation",
      "no incident bridge activation",
      "no rollback authorization",
      "no emergency rollback execution",
      "no emergency hold release",
      "no kill-switch activation",
      "no customer communication release",
      "no public status page enablement",
      "no support escalation activation",
      "no cutover authority grant",
      "no production cutover approval",
      "no production cutover execution",
      "no deployment execution",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no production portal launch",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/deployment-environment-readiness",
      "/production-launch-evidence",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-support-communications-readiness",
    ],
  },
  {
    id: "internal-production-support-communications-readiness",
    label: "Production Support Communications Readiness Gate",
    route: "/production-support-communications-readiness",
    audience: "internal",
    moduleRefs: ["Module 35"],
    purpose:
      "Internal production support communications readiness review for support routing, customer-safe language, public status, support escalation, accessibility, translation, redaction, data rights, audit, replay, and communications freeze evidence.",
    primaryStatus:
      "Support communications approval, support activation, support escalation, customer communications, regulatory communications, public status page, borrower notices, official reports, public verification, cutover authority, deployment, public production exposure, and portal launch remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No production support communications approval has been granted.",
      "No support operations activation has been approved.",
      "No support escalation has been activated.",
      "No customer communication has been released.",
      "No regulatory communication has been released.",
      "No public status page has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No public verification authority has been granted.",
      "No legal advice has been provided.",
      "No official reliance has been created.",
      "No incident response activation has been approved.",
      "No incident bridge has been activated for production launch.",
      "No rollback authorization has been granted.",
      "No production cutover authority has been granted.",
      "No production cutover has been approved or executed.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No payment capture has been enabled.",
      "This gate is production support communications readiness review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production incident response readiness evidence",
      "support queue routing review",
      "customer-safe language review",
      "public status page posture review",
      "borrower notice and adverse-action boundary review",
      "accessibility and translation review",
      "redaction and data-rights handoff review",
      "support escalation runbook review",
      "audit, replay, and communications evidence review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no support communications approval",
      "no support operations activation",
      "no support escalation activation",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no public verification authority",
      "no legal advice",
      "no official reliance",
      "no cutover authority grant",
      "no production cutover approval",
      "no production cutover execution",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
    ],
    adjacentRoutes: [
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-final-authority",
    ],
  },
  {
    id: "internal-production-final-authority",
    label: "Production Final Authority Gate",
    route: "/production-final-authority",
    audience: "internal",
    moduleRefs: ["Module 36"],
    purpose:
      "Internal production final authority review for constitutional authority, qualified release manager, launch, deployment, cutover, operations, incident, support, communications, security, privacy, redaction, claims, audit, replay, and data-rights evidence.",
    primaryStatus:
      "Final authority approval, go-live approval, production launch authorization, hold release, deployment, public production exposure, support activation, communications release, payment capture, notices, official reports, public verification, legal advice, and official reliance remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No final production authority approval has been granted.",
      "No go-live approval has been granted.",
      "No production launch authorization has been granted.",
      "No constitutional officer final attestation has been received.",
      "No qualified release manager final approval has been granted.",
      "No production support communications approval has been granted.",
      "No support operations activation has been approved.",
      "No customer communication has been released.",
      "No regulatory communication has been released.",
      "No public status page has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No public verification authority has been granted.",
      "No legal advice has been provided.",
      "No official reliance has been created.",
      "No production cutover authority has been granted.",
      "No production cutover has been approved or executed.",
      "No launch hold has been released.",
      "No deployment hold has been released.",
      "No deployment has been executed.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No payment capture has been enabled.",
      "This gate is final production authority review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-final-authority",
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production support communications readiness evidence",
      "constitutional final authority review",
      "qualified release manager final review",
      "security and production exposure review",
      "data rights, privacy, and redaction review",
      "public claims and launch copy review",
      "support and communications freeze review",
      "monitoring, incident, rollback, and emergency hold review",
      "audit, replay, and evidence retention review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no final production authority approval",
      "no go-live approval",
      "no production launch authorization",
      "no constitutional officer final attestation",
      "no qualified release manager final approval",
      "no launch hold release",
      "no deployment hold release",
      "no release-candidate freeze hold release",
      "no support operations activation",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no public verification authority",
      "no legal advice",
      "no official reliance",
      "no cutover authority grant",
      "no production cutover approval",
      "no production cutover execution",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
    ],
    adjacentRoutes: [
      "/production-support-communications-readiness",
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-activation-ceremony",
    ],
  },
  {
    id: "internal-production-activation-ceremony",
    label: "Production Activation Ceremony Gate",
    route: "/production-activation-ceremony",
    audience: "internal",
    moduleRefs: ["Module 37"],
    purpose:
      "Internal production activation ceremony readiness review for final authority, dual-control quorum, credential vault release, deployment sequence, monitoring, rollback, incident response, support communications, audit, replay, privacy, redaction, claims, and post-activation verification evidence.",
    primaryStatus:
      "Activation ceremony approval, ceremony execution, production activation, post-activation verification, go-live approval, hold release, deployment, public production exposure, support activation, communications release, payment capture, notices, official reports, public verification, legal advice, and official reliance remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No activation ceremony approval has been granted.",
      "No activation ceremony has been executed.",
      "No production activation has been executed.",
      "No post-activation verification has been started.",
      "No post-activation verification has been completed.",
      "No final production authority approval has been granted.",
      "No go-live approval has been granted.",
      "No production launch authorization has been granted.",
      "No launch hold has been released.",
      "No deployment hold has been released.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No customer communication has been released.",
      "No public status page has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No public verification authority has been granted.",
      "No legal advice has been provided.",
      "No official reliance has been created.",
      "No payment capture has been enabled.",
      "This gate is production activation ceremony readiness review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-activation-ceremony",
      "/api/governance/production-final-authority",
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production final authority evidence",
      "activation ceremony agenda review",
      "dual-control quorum review",
      "credential vault and production secret release review",
      "deployment, migration, DNS, CDN, TLS, WAF, and rollback sequence review",
      "monitoring and post-activation verification review",
      "communications freeze and public-status review",
      "audit, replay, and evidence retention review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no activation ceremony approval",
      "no activation ceremony execution",
      "no production activation execution",
      "no post-activation verification start",
      "no post-activation verification completion",
      "no final production authority approval",
      "no go-live approval",
      "no production launch authorization",
      "no launch hold release",
      "no deployment hold release",
      "no release-candidate freeze hold release",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no support operations activation",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no public verification authority",
      "no legal advice",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/production-final-authority",
      "/production-support-communications-readiness",
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-post-activation-verification",
    ],
  },
  {
    id: "internal-production-post-activation-verification",
    label: "Production Post-Activation Verification Gate",
    route: "/production-post-activation-verification",
    audience: "internal",
    moduleRefs: ["Module 38"],
    purpose:
      "Internal production post-activation verification readiness review for activation ceremony, verification runbook, watch-window ownership, synthetic health checks, public surfaces, audit, replay, monitoring, rollback, emergency hold, kill-switch, incident response, support communications, privacy, redaction, claims, data rights, and source/live-action boundary evidence.",
    primaryStatus:
      "Post-activation verification approval, verification start, verification completion, production health certification, activation ceremony approval, ceremony execution, production activation, go-live approval, hold release, deployment, public production exposure, support activation, communications release, payment capture, notices, official reports, public verification, legal advice, and official reliance remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No post-activation verification approval has been granted.",
      "No post-activation verification has been started.",
      "No post-activation verification has been completed.",
      "No post-activation verification has passed.",
      "No production health has been certified.",
      "No activation ceremony approval has been granted.",
      "No activation ceremony has been executed.",
      "No production activation has been executed.",
      "No final production authority approval has been granted.",
      "No go-live approval has been granted.",
      "No production launch authorization has been granted.",
      "No launch hold has been released.",
      "No deployment hold has been released.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No customer communication has been released.",
      "No public status page has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No public verification authority has been granted.",
      "No legal advice has been provided.",
      "No official reliance has been created.",
      "No payment capture has been enabled.",
      "This gate is post-activation verification readiness review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-post-activation-verification",
      "/api/governance/production-activation-ceremony",
      "/api/governance/production-final-authority",
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production activation ceremony evidence",
      "post-activation verification runbook review",
      "watch-window owner review",
      "synthetic health check review",
      "public surface check review",
      "audit and replay export verification review",
      "monitoring, rollback, emergency hold, and kill-switch watch review",
      "support communications watch review",
      "privacy, redaction, data-rights, and public DTO review",
      "source and live-action boundary review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no post-activation verification approval",
      "no post-activation verification start",
      "no post-activation verification completion",
      "no post-activation verification pass",
      "no production health certification",
      "no activation ceremony approval",
      "no activation ceremony execution",
      "no production activation execution",
      "no final production authority approval",
      "no go-live approval",
      "no production launch authorization",
      "no launch hold release",
      "no deployment hold release",
      "no release-candidate freeze hold release",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no support operations activation",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no public verification authority",
      "no legal advice",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/production-activation-ceremony",
      "/production-final-authority",
      "/production-support-communications-readiness",
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-reliance-verification",
    ],
  },
  {
    id: "internal-production-reliance-verification",
    label: "Production Reliance and Public Verification Boundary Gate",
    route: "/production-reliance-verification",
    audience: "internal",
    moduleRefs: ["Module 39"],
    purpose:
      "Internal production reliance and public verification boundary review for post-activation verification, public claims, public DTOs, audit, replay, privacy, redaction, data rights, source authority, reports, notices, payments, legal advice, regulatory reliance, official reliance, and live-action evidence.",
    primaryStatus:
      "Production reliance approval, public verification authority, public verification gateway operation, public verification artifact publication, external reliance disclosure, regulatory reliance, official reliance, legal advice, post-activation verification approval, production health certification, activation, deployment, public exposure, notices, official reports, payment capture, and live external actions remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No production reliance approval has been granted.",
      "No public verification authority has been granted.",
      "No public verification gateway has been made operational.",
      "No public verification artifact has been published.",
      "No external reliance disclosure has been approved.",
      "No regulatory reliance has been authorized.",
      "No official reliance has been created.",
      "No legal advice has been provided.",
      "No post-activation verification approval has been granted.",
      "No post-activation verification has been started.",
      "No post-activation verification has been completed.",
      "No production health has been certified.",
      "No go-live approval has been granted.",
      "No deployment has been executed.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No payment capture has been enabled.",
      "This gate is production reliance and public verification boundary review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-reliance-verification",
      "/api/governance/production-post-activation-verification",
      "/api/governance/production-activation-ceremony",
      "/api/governance/production-final-authority",
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
      "/api/billing/admin",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production post-activation verification evidence",
      "production reliance authority review",
      "public verification infrastructure review",
      "public claims and customer copy review",
      "external disclosure and reliance recipient review",
      "audit and replay reliance evidence review",
      "privacy, redaction, data-rights, and public DTO review",
      "source authority, report, notice, payment, legal, and live-action boundary review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no production reliance approval",
      "no public verification authority",
      "no public verification gateway operation",
      "no public verification artifact publication",
      "no external reliance disclosure approval",
      "no regulatory reliance authorization",
      "no official reliance",
      "no legal advice",
      "no post-activation verification approval",
      "no post-activation verification start",
      "no post-activation verification completion",
      "no post-activation verification pass",
      "no production health certification",
      "no activation ceremony approval",
      "no activation ceremony execution",
      "no production activation execution",
      "no final production authority approval",
      "no go-live approval",
      "no production launch authorization",
      "no launch hold release",
      "no deployment hold release",
      "no release-candidate freeze hold release",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no payment capture",
      "no live external action",
    ],
    adjacentRoutes: [
      "/production-post-activation-verification",
      "/production-activation-ceremony",
      "/production-final-authority",
      "/production-support-communications-readiness",
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-regulatory-examination",
    ],
  },
  {
    id: "internal-production-regulatory-examination",
    label: "Production Regulatory Examination and Evidence Archive Gate",
    route: "/production-regulatory-examination",
    audience: "internal",
    moduleRefs: ["Module 40"],
    purpose:
      "Internal production regulatory examination and evidence archive readiness review for reliance boundary evidence, examination scope, archive completeness, retention, legal hold, audit, replay, redaction, public records, regulatory communications, source authority, reports, notices, payments, legal advice, official reliance, and live-action evidence.",
    primaryStatus:
      "Regulatory package approval, regulator submission, portal upload, official regulator response, archive certification, retention certification, legal hold release, external examiner disclosure, public verification, official reliance, legal advice, deployment, public exposure, notices, official reports, payment capture, and live external actions remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No regulatory examination package has been approved.",
      "No regulatory examination package has been submitted.",
      "No regulator portal upload has been approved.",
      "No official regulator response has been issued.",
      "No evidence archive has been certified.",
      "No evidence retention certification has been granted.",
      "No legal hold has been released.",
      "No external examiner disclosure has been approved.",
      "No production reliance approval has been granted.",
      "No public verification authority has been granted.",
      "No official reliance has been created.",
      "No legal advice has been provided.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No payment capture has been enabled.",
      "This gate is regulatory examination and evidence archive readiness review only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-regulatory-examination",
      "/api/governance/production-reliance-verification",
      "/api/governance/production-post-activation-verification",
      "/api/governance/production-activation-ceremony",
      "/api/governance/production-final-authority",
      "/api/governance/production-support-communications-readiness",
      "/api/governance/production-incident-response-readiness",
      "/api/governance/production-operations-monitoring",
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
      "/api/billing/admin",
      "/api/audit/export",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production reliance boundary evidence",
      "regulatory examination scope review",
      "evidence archive completeness review",
      "retention and legal hold review",
      "audit and replay export review",
      "privacy, redaction, public-records, and data-rights review",
      "regulatory communication review",
      "source authority, report, notice, payment, legal, and live-action boundary review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no regulatory examination package approval",
      "no regulatory examination package submission",
      "no regulator portal upload",
      "no official regulator response",
      "no evidence archive certification",
      "no evidence retention certification",
      "no legal hold release",
      "no external examiner disclosure approval",
      "no production reliance approval",
      "no public verification authority",
      "no official reliance",
      "no legal advice",
      "no post-activation verification approval",
      "no production health certification",
      "no production activation execution",
      "no go-live approval",
      "no production launch authorization",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no payment capture",
      "no live external action",
    ],
    adjacentRoutes: [
      "/production-reliance-verification",
      "/production-post-activation-verification",
      "/production-activation-ceremony",
      "/production-final-authority",
      "/production-support-communications-readiness",
      "/production-incident-response-readiness",
      "/production-operations-monitoring",
      "/production-release-board",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-regulatory-response",
    ],
  },
  {
    id: "internal-production-regulatory-response",
    label: "Production Regulatory Response and Corrective Action Gate",
    route: "/production-regulatory-response",
    audience: "internal",
    moduleRefs: ["Module 41"],
    purpose:
      "Internal production regulatory response and corrective-action review for examination evidence, examiner findings, response package posture, corrective-action plans, remediation evidence, legal/compliance language, audit, replay, redaction, public records, source authority, reports, notices, payments, legal advice, official reliance, and live-action evidence.",
    primaryStatus:
      "Regulatory response package approval, official regulator response, corrective-action commitment, corrective-action execution, remediation execution, examiner finding closure, legal hold release, external examiner disclosure, public verification, official reliance, legal advice, deployment, public exposure, notices, official reports, payment capture, and live external actions remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No regulatory response package has been approved.",
      "No official regulator response has been issued.",
      "No corrective action plan has been approved.",
      "No corrective action has been committed.",
      "No corrective action has been executed.",
      "No remediation plan has been approved.",
      "No remediation has been executed.",
      "No examiner finding has been closed.",
      "No external examiner disclosure has been approved.",
      "No legal hold has been released.",
      "No production reliance approval has been granted.",
      "No public verification authority has been granted.",
      "No official reliance has been created.",
      "No legal advice has been provided.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No payment capture has been enabled.",
      "This gate is regulatory response and corrective-action review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-regulatory-response",
      "/api/governance/production-regulatory-examination",
      "/api/governance/production-reliance-verification",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
      "/api/notices/admin",
      "/api/reports/admin",
      "/api/billing/admin",
      "/api/audit/export",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production regulatory examination evidence",
      "examiner finding intake review",
      "corrective-action plan review",
      "remediation evidence review",
      "legal and compliance response review",
      "audit and replay response evidence review",
      "privacy, redaction, public-records, and data-rights review",
      "source authority, report, notice, payment, legal, and live-action boundary review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no regulatory response package approval",
      "no official regulator response",
      "no corrective-action plan approval",
      "no corrective-action commitment",
      "no corrective-action execution",
      "no remediation plan approval",
      "no remediation execution",
      "no examiner finding closure",
      "no legal hold release",
      "no external examiner disclosure approval",
      "no production reliance approval",
      "no public verification authority",
      "no official reliance",
      "no legal advice",
      "no production health certification",
      "no production activation execution",
      "no go-live approval",
      "no production launch authorization",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no customer communication release",
      "no regulatory communication release",
      "no public status page enablement",
      "no borrower notice send",
      "no official report publication",
      "no payment capture",
      "no live external action",
    ],
    adjacentRoutes: [
      "/production-regulatory-examination",
      "/production-reliance-verification",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/build-preservation",
    ],
  },
  {
    id: "internal-build-preservation",
    label: "Build Preservation and Evidence Archive Gate",
    route: "/build-preservation",
    audience: "internal",
    moduleRefs: ["Module 42", "Checkpoint BR-2026-06-01-M41"],
    purpose:
      "Internal build preservation and evidence archive review for freezing the verified Module 41 backend governance foundation, attaching backend verification and production build evidence, detecting tree drift, verifying ignored sensitive files, and generating an operator-readable archive.",
    primaryStatus:
      "Build preservation is evidence-only. Production launch, deployment, public exposure, portal launch, payments, notices, official reports, public verification, official reliance, legal advice, regulatory response, corrective-action commitment, remediation execution, and live external actions remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "BR-2026-06-01-M41 has been recorded as a review-bound build checkpoint.",
      "Module 41 conforms to current Master Volumes 0-VI as of the checkpoint evidence.",
      "Build preservation is evidence-only and does not authorize production launch.",
      "Tree drift must be resolved before a new canonical checkpoint is declared.",
      "Sensitive files must remain ignored and outside build history.",
      "No deployment has been executed.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "No public verification authority has been granted.",
      "No official reliance has been created.",
      "No legal advice has been provided.",
      "No live external action has been performed."
    ),
    requiredBackendSurfaces: [
      "/api/governance/build-preservation",
      "/api/governance/production-regulatory-response",
      "/api/governance/production-regulatory-examination",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "Master Volume 0-VI conformance evidence",
      "checkpoint commit evidence",
      "backend verification evidence",
      "production build evidence",
      "module route event and handoff inventory",
      "tree drift detection",
      "ignored sensitive file verification",
      "operator-readable archive generation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no production launch authorization",
      "no deployment execution",
      "no public production API exposure",
      "no production portal launch",
      "no payment capture",
      "no borrower notice send",
      "no official report publication",
      "no public verification approval",
      "no official reliance",
      "no legal advice",
      "no regulatory response issuance",
      "no corrective-action commitment",
      "no remediation execution",
      "no live external action",
    ],
    adjacentRoutes: [
      "/production-regulatory-response",
      "/production-regulatory-examination",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
    ],
  },
  {
    id: "internal-deployment-environment-readiness",
    label: "Deployment Environment Readiness Gate",
    route: "/deployment-environment-readiness",
    audience: "internal",
    moduleRefs: ["Module 29"],
    purpose:
      "Internal deployment environment review for release-candidate, build, typecheck, backend smoke, integration smoke, secrets, migrations, deployment target, DNS, CDN, TLS, WAF, monitoring, backup, rollback, incident, support, and release-manager evidence.",
    primaryStatus:
      "Deployment remains blocked until qualified release manager approval, production environment controls, and final deployment hold release are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No deployment has been executed.",
      "No release candidate has been approved.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published."
    ),
    requiredBackendSurfaces: [
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/governance/production-portal-readiness",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production launch evidence packet",
      "release-candidate build freeze",
      "backend smoke and integration smoke freeze",
      "production secret inventory review",
      "database migration and rollback review",
      "DNS, CDN, TLS, and WAF review",
      "monitoring, alerting, backup, restore, and incident review",
      "qualified release manager attestation",
      "deployment hold release",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no deployment execution",
      "no release candidate approval",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no official reliance",
      "no deployment hold release without qualified approval",
    ],
    adjacentRoutes: [
      "/production-launch-evidence",
      "/release-candidate-freeze",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
    ],
  },
  {
    id: "internal-release-candidate-freeze",
    label: "Release Candidate Freeze Plan",
    route: "/release-candidate-freeze",
    audience: "internal",
    moduleRefs: ["Module 30"],
    purpose:
      "Internal release-candidate freeze review for final build, typecheck, backend smoke, integration smoke, content claims, release notes, secrets, migrations, DNS, CDN, TLS, WAF, monitoring, backup, rollback, incident, support, communications, and release-manager evidence.",
    primaryStatus:
      "Release-candidate freeze remains blocked until qualified release manager approval, production controls, final deployment hold release, and go-live hold release are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No release candidate has been frozen or approved.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "This plan is release-candidate freeze review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "deployment environment readiness evidence",
      "final release-candidate build freeze",
      "backend smoke and integration smoke freeze",
      "content claims and public copy freeze",
      "production secret manifest review",
      "database migration and rollback review",
      "DNS, CDN, TLS, and WAF review",
      "monitoring, alerting, backup, restore, and incident review",
      "qualified release manager signoff",
      "deployment hold and go-live hold release",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no release-candidate freeze approval",
      "no release-candidate freeze",
      "no release candidate approval",
      "no deployment execution",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no official reliance",
      "no freeze hold release without qualified approval",
    ],
    adjacentRoutes: [
      "/deployment-environment-readiness",
      "/production-launch-evidence",
      "/production-cutover-hold",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
    ],
  },
  {
    id: "internal-production-cutover-hold",
    label: "Production Cutover Hold Gate",
    route: "/production-cutover-hold",
    audience: "internal",
    moduleRefs: ["Module 31"],
    purpose:
      "Internal production cutover hold review for release-candidate freeze, launch hold, deployment hold, freeze hold, secret activation, migration execution, DNS, CDN, TLS, WAF, public API exposure, portal launch, monitoring, backup, rollback, incident, support, communications, release board, and release-manager evidence.",
    primaryStatus:
      "Production cutover remains blocked until qualified release approval, final launch hold release, deployment hold release, freeze hold release, and cutover authority are recorded.",
    safeMessages: portableSafeMessagesWith(
      "No production cutover has been approved or executed.",
      "No launch hold has been released.",
      "No deployment hold has been released.",
      "No release-candidate freeze hold has been released.",
      "No release candidate has been frozen or approved.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "This gate is production cutover hold review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-cutover-hold",
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "release-candidate freeze plan evidence",
      "cutover board packet review",
      "final launch hold, deployment hold, and freeze hold review",
      "production secret activation review",
      "database migration execution review",
      "DNS, CDN, TLS, and WAF cutover review",
      "public production API exposure review",
      "production portal launch review",
      "monitoring, alerting, backup, restore, rollback, incident, support, and communications review",
      "qualified release manager cutover signoff",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no production cutover approval",
      "no production cutover execution",
      "no launch hold release",
      "no deployment hold release",
      "no freeze hold release",
      "no deployment execution",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no production portal launch",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/release-candidate-freeze",
      "/deployment-environment-readiness",
      "/production-launch-evidence",
      "/production-release-board",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
    ],
  },
  {
    id: "internal-production-release-board",
    label: "Production Release Board Evidence Packet",
    route: "/production-release-board",
    audience: "internal",
    moduleRefs: ["Module 32"],
    purpose:
      "Internal production release board evidence review for cutover hold, release board agenda, quorum, qualified release manager, security, compliance, operations, support, public copy, incident, rollback, communications, launch hold, deployment hold, freeze hold, secrets, migrations, DNS, CDN, TLS, WAF, public API exposure, and portal launch evidence.",
    primaryStatus:
      "Production release board approval, cutover authority, launch hold release, deployment, secret activation, public DNS cutover, production migrations, public API exposure, and portal launch remain blocked.",
    safeMessages: portableSafeMessagesWith(
      "No production release board approval has been granted.",
      "No production cutover authority has been granted.",
      "No production cutover has been approved or executed.",
      "No launch hold has been released.",
      "No deployment hold has been released.",
      "No release-candidate freeze hold has been released.",
      "No release candidate has been frozen or approved.",
      "No deployment has been executed.",
      "No production secret has been activated.",
      "No public DNS cutover has been approved.",
      "No production database migration has been approved.",
      "No public production API exposure has been approved.",
      "No production portal launch has been executed.",
      "No public verification authority has been granted.",
      "No payment capture has been enabled.",
      "No borrower notice has been sent.",
      "No official report has been published.",
      "This packet is production release board review evidence only."
    ),
    requiredBackendSurfaces: [
      "/api/governance/production-release-board",
      "/api/governance/production-cutover-hold",
      "/api/governance/release-candidate-freeze",
      "/api/governance/deployment-environment-readiness",
      "/api/governance/production-launch-evidence",
      "/api/public/surfaces",
      "/api/claims/public",
      "/api/runtime/state",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "production cutover hold evidence",
      "release board agenda and quorum review",
      "qualified release manager review",
      "security, compliance, operations, and support owner attestation",
      "public-copy and content-claims final review",
      "incident, rollback, support, and communications review",
      "launch hold, deployment hold, and freeze hold review",
      "production secret, migration, DNS, public API, and portal launch review",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no release board approval",
      "no cutover authority grant",
      "no production cutover approval",
      "no production cutover execution",
      "no launch hold release",
      "no deployment hold release",
      "no freeze hold release",
      "no deployment execution",
      "no production secret activation",
      "no public DNS cutover",
      "no production database migration",
      "no public production API exposure",
      "no production portal launch",
      "no official reliance",
    ],
    adjacentRoutes: [
      "/production-cutover-hold",
      "/release-candidate-freeze",
      "/deployment-environment-readiness",
      "/production-launch-evidence",
      "/module-readiness",
      "/governance",
      "/operator-demo",
      "/promotion",
      "/production-operations-monitoring",
    ],
  },
  {
    id: "internal-customer-revenue",
    label: "Customer Revenue Review",
    route: "/customer-revenue",
    audience: "internal",
    moduleRefs: ["Revenue Source Intelligence"],
    purpose:
      "Internal revenue source intelligence review for opportunities, catalog items, programs, costs, markets, geospatial posture, state rules, and advisory fusion.",
    primaryStatus: "Revenue intelligence is advisory and review-bound.",
    safeMessages: portableSafeMessagesWith(
      "Program fit is preliminary and review-required.",
      "Pricing, market, weather, and cost signals may change."
    ),
    requiredBackendSurfaces: [
      "/api/customer-revenue/advisory",
      "/api/revenue-intelligence/opportunities",
      "/api/revenue-intelligence/fusion",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "revenue source intelligence governance",
      "source lineage and replay preservation",
      "claims validation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no guaranteed revenue claims",
      "no program approval claims",
      "no legal advice",
      "no live source refresh",
    ],
    adjacentRoutes: ["/source-ingestion", "/portal/revenue-opportunities"],
  },
];

export const borrowerPortalSurfaces: PortableVerticalSurface[] = [
  {
    id: "borrower-applications",
    label: "Borrower Applications",
    route: "/portal/borrower/applications",
    audience: "borrower",
    moduleRefs: ["Module 03", "Module 15"],
    purpose:
      "Borrower-facing application status translation without approval, eligibility, or lending reliance claims.",
    primaryStatus: "Your application is in governed review.",
    safeMessages: portableSafeMessagesWith("Your application was received."),
    requiredBackendSurfaces: ["/api/applications/admin", "/api/apply"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: [
      "/portal/borrower/documents",
      "/portal/borrower/notices",
      "/portal/borrower/data-rights",
    ],
  },
  {
    id: "borrower-documents",
    label: "Borrower Documents",
    route: "/portal/borrower/documents",
    audience: "borrower",
    moduleRefs: ["Module 04", "Module 18"],
    purpose:
      "Borrower-facing document receipt, metadata, and follow-up status without raw content processing.",
    primaryStatus: "Your document was received.",
    safeMessages: [...portableSurfaceSafeMessages],
    requiredBackendSurfaces: [
      "/api/documents/submit",
      "/api/documents/storage-handoff",
      "/api/documents/admin",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: [
      "/portal/borrower/applications",
      "/portal/borrower/reports",
      "/portal/borrower/data-rights",
    ],
  },
  {
    id: "borrower-notices",
    label: "Borrower Notices",
    route: "/portal/borrower/notices",
    audience: "borrower",
    moduleRefs: ["Module 08", "Module 07"],
    purpose:
      "Borrower-facing notice status translation while external delivery and final action remain gated.",
    primaryStatus: "No final notice has been sent by this demo surface.",
    safeMessages: portableSafeMessagesWith(
      "A notice may require additional review before delivery."
    ),
    requiredBackendSurfaces: ["/api/notices/admin", "/api/reviews/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/portal/borrower/applications", "/portal/borrower/reports"],
  },
  {
    id: "borrower-reports",
    label: "Borrower Reports",
    route: "/portal/borrower/reports",
    audience: "borrower",
    moduleRefs: ["Module 13", "Module 16"],
    purpose:
      "Borrower-facing advisory report status without official report, verification, or regulatory reliance claims.",
    primaryStatus: "Advisory report preparation may require human review.",
    safeMessages: portableSafeMessagesWith("This is not an official report."),
    requiredBackendSurfaces: ["/api/reports/admin", "/api/reports/pdf"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/portal/borrower/data-rights", "/portal/borrower/documents"],
  },
  {
    id: "borrower-data-rights",
    label: "Borrower Data Rights",
    route: "/portal/borrower/data-rights",
    audience: "borrower",
    moduleRefs: ["Module 19", "Module 16"],
    purpose:
      "Borrower-facing data review, portability, export, and correction-preparation surface.",
    primaryStatus: "Borrower data-rights preparation is available for review.",
    safeMessages: [...portableSurfaceSafeMessages],
    requiredBackendSurfaces: [
      "/api/reports/admin",
      "/api/documents/admin",
      "/api/applications/admin",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/portal/borrower/applications", "/portal/borrower/reports"],
  },
  {
    id: "borrower-property-discovery",
    label: "Borrower Property Discovery",
    route: "/portal/property-discovery",
    audience: "borrower",
    moduleRefs: ["Module 17", "Module 03"],
    purpose:
      "Borrower-facing property discovery translation with advisory marketplace data and institutional review boundaries.",
    primaryStatus: "Property discovery is advisory and requires review.",
    safeMessages: portableSafeMessagesWith(
      "Listings may change.",
      "Marketplace data is advisory.",
      "Institutional review may be required.",
      "Displayed properties are not approvals."
    ),
    requiredBackendSurfaces: [
      "/api/properties/discovery",
      "/api/properties/canonical",
      "/api/source-ingestion/submit",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no official collateral certification",
      "no live marketplace scraping",
    ],
    adjacentRoutes: ["/portal/borrower/applications", "/source-ingestion"],
  },
  {
    id: "borrower-revenue-opportunities",
    label: "Borrower Revenue Opportunities",
    route: "/portal/revenue-opportunities",
    audience: "borrower",
    moduleRefs: ["Revenue Source Intelligence"],
    purpose:
      "Borrower-facing revenue opportunity translation with advisory program, product, market, cost, and source-lineage controls.",
    primaryStatus: "Opportunities are advisory and review-bound.",
    safeMessages: portableSafeMessagesWith(
      "Program fit is preliminary and review-required.",
      "Pricing, market, weather, and cost signals may change.",
      "Regional legal and licensing questions require qualified review."
    ),
    requiredBackendSurfaces: [
      "/api/customer-revenue/advisory",
      "/api/revenue-intelligence/opportunities",
      "/api/revenue-intelligence/catalog",
      "/api/revenue-intelligence/programs",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "revenue source intelligence governance",
      "source lineage and replay preservation",
      "claims validation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no guaranteed revenue claims",
      "no program approval claims",
      "no legal advice",
      "no live source refresh",
    ],
    adjacentRoutes: ["/portal/property-discovery", "/portal/borrower/applications"],
  },
];

export const lenderPortalSurfaces: PortableVerticalSurface[] = [
  {
    id: "lender-dashboard",
    label: "Lender Dashboard",
    route: "/lender/dashboard",
    audience: "lender",
    moduleRefs: ["Module 11", "Module 15"],
    purpose:
      "Lender-facing coordination dashboard for intake posture, not a commitment or underwriting decision.",
    primaryStatus: "Lender review package is coordination-only.",
    safeMessages: portableSafeMessagesWith(
      "No lender commitment has been created."
    ),
    requiredBackendSurfaces: ["/api/partners/admin", "/api/applications/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/lender/applications", "/lender/overlays", "/lender/evidence"],
  },
  {
    id: "lender-applications",
    label: "Lender Applications",
    route: "/lender/applications",
    audience: "lender",
    moduleRefs: ["Module 03", "Module 11"],
    purpose:
      "Lender-facing application intake translation with borrower, tenant, and partner scope preserved.",
    primaryStatus: "Application materials are available for governed review.",
    safeMessages: [...portableSurfaceSafeMessages],
    requiredBackendSurfaces: ["/api/applications/admin", "/api/documents/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/lender/dashboard", "/lender/evidence"],
  },
  {
    id: "lender-overlays",
    label: "Lender Overlays",
    route: "/lender/overlays",
    audience: "lender",
    moduleRefs: ["Module 06", "Module 07"],
    purpose:
      "Lender-facing rule and overlay posture with advisory-only interpretation and human review boundary.",
    primaryStatus: "Overlay results are advisory and require review.",
    safeMessages: portableSafeMessagesWith(
      "No eligibility decision has been made."
    ),
    requiredBackendSurfaces: ["/api/rules/admin", "/api/reviews/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/lender/applications", "/lender/evidence"],
  },
  {
    id: "lender-evidence",
    label: "Lender Evidence",
    route: "/lender/evidence",
    audience: "lender",
    moduleRefs: ["Module 16", "Module 09"],
    purpose:
      "Lender-facing evidence packet orientation without public verification or official certification claims.",
    primaryStatus: "Evidence is prepared for governed review only.",
    safeMessages: portableSafeMessagesWith(
      "This evidence is not externally certified."
    ),
    requiredBackendSurfaces: ["/api/reports/admin", "/api/ledger/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/lender/dashboard", "/lender/overlays"],
  },
  {
    id: "lender-property-opportunities",
    label: "Lender Property Opportunities",
    route: "/lender/property-opportunities",
    audience: "lender",
    moduleRefs: ["Module 10", "Module 17"],
    purpose:
      "Lender-facing property opportunity translation without commitments, underwriting reliance, or collateral certification.",
    primaryStatus: "Property opportunities are coordination-only.",
    safeMessages: portableSafeMessagesWith(
      "Listings may change.",
      "Marketplace data is advisory.",
      "Institutional review may be required.",
      "Displayed properties are not approvals."
    ),
    requiredBackendSurfaces: [
      "/api/properties/discovery",
      "/api/properties/canonical",
      "/api/scrapers/provenance",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no official collateral certification",
      "no lender commitment",
      "no live marketplace scraping",
    ],
    adjacentRoutes: ["/lender/dashboard", "/lender/evidence"],
  },
  {
    id: "lender-revenue-opportunities",
    label: "Lender Revenue Opportunities",
    route: "/lender/revenue-opportunities",
    audience: "lender",
    moduleRefs: ["Revenue Source Intelligence"],
    purpose:
      "Lender-facing revenue opportunity context without commitment, underwriting reliance, or program certainty claims.",
    primaryStatus: "Revenue context is coordination-only.",
    safeMessages: portableSafeMessagesWith(
      "Program fit is preliminary and review-required.",
      "Pricing, market, weather, and cost signals may change.",
      "No lender commitment has been created."
    ),
    requiredBackendSurfaces: [
      "/api/customer-revenue/advisory",
      "/api/revenue-intelligence/programs",
      "/api/revenue-intelligence/marketplace",
      "/api/revenue-intelligence/operating-costs",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "revenue source intelligence governance",
      "source lineage and replay preservation",
      "claims validation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no guaranteed revenue claims",
      "no program approval claims",
      "no lender commitment",
      "no underwriting reliance",
    ],
    adjacentRoutes: ["/lender/dashboard", "/lender/evidence"],
  },
];

export const sponsorPortalSurfaces: PortableVerticalSurface[] = [
  {
    id: "sponsor-dashboard",
    label: "Sponsor Dashboard",
    route: "/sponsor/dashboard",
    audience: "sponsor",
    moduleRefs: ["Module 11", "Module 15"],
    purpose:
      "Sponsor-facing readiness and support coordination without borrower disclosure or final commitment.",
    primaryStatus: "Sponsor coordination is available for review.",
    safeMessages: portableSafeMessagesWith(
      "No sponsor commitment has been created."
    ),
    requiredBackendSurfaces: ["/api/partners/admin", "/api/applications/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/sponsor/readiness", "/sponsor/reports"],
  },
  {
    id: "sponsor-readiness",
    label: "Sponsor Readiness",
    route: "/sponsor/readiness",
    audience: "sponsor",
    moduleRefs: ["Module 14", "Module 20"],
    purpose:
      "Sponsor-facing readiness posture while live promotion and external action remain gated.",
    primaryStatus: "Readiness review is internal and not production promotion.",
    safeMessages: portableSafeMessagesWith("No live action has been authorized."),
    requiredBackendSurfaces: [
      "/api/governance/live-action-readiness/admin",
      "/api/partners/admin",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/sponsor/dashboard", "/sponsor/reports"],
  },
  {
    id: "sponsor-reports",
    label: "Sponsor Reports",
    route: "/sponsor/reports",
    audience: "sponsor",
    moduleRefs: ["Module 13", "Module 16"],
    purpose:
      "Sponsor-facing advisory report translation without official reports, public verification, or regulatory reliance.",
    primaryStatus: "Sponsor report summaries are advisory-only.",
    safeMessages: portableSafeMessagesWith("This is not an official report."),
    requiredBackendSurfaces: ["/api/reports/admin", "/api/partners/admin"],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [...portableSurfaceProductionBlocks],
    adjacentRoutes: ["/sponsor/dashboard", "/sponsor/readiness"],
  },
  {
    id: "sponsor-project-discovery",
    label: "Sponsor Project Discovery",
    route: "/sponsor/project-discovery",
    audience: "sponsor",
    moduleRefs: ["Module 11", "Module 17"],
    purpose:
      "Sponsor-facing project discovery translation while institutional validation remains pending.",
    primaryStatus: "Project discovery is advisory and review-bound.",
    safeMessages: portableSafeMessagesWith(
      "Listings may change.",
      "Marketplace data is advisory.",
      "Institutional review may be required.",
      "Displayed properties are not approvals."
    ),
    requiredBackendSurfaces: [
      "/api/properties/discovery",
      "/api/properties/replay",
      "/api/source-ingestion/review",
    ],
    governanceRequirements: [...portableSurfaceGovernanceRequirements],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no official collateral certification",
      "no sponsor commitment",
      "no live marketplace scraping",
    ],
    adjacentRoutes: ["/sponsor/dashboard", "/sponsor/readiness"],
  },
  {
    id: "sponsor-revenue-opportunities",
    label: "Sponsor Revenue Opportunities",
    route: "/sponsor/revenue-opportunities",
    audience: "sponsor",
    moduleRefs: ["Revenue Source Intelligence"],
    purpose:
      "Sponsor-facing revenue and project-support context with advisory source, program, catalog, and suitability boundaries.",
    primaryStatus: "Sponsor revenue context is review-bound.",
    safeMessages: portableSafeMessagesWith(
      "Program fit is preliminary and review-required.",
      "Pricing, market, weather, and cost signals may change.",
      "No sponsor commitment has been created."
    ),
    requiredBackendSurfaces: [
      "/api/customer-revenue/advisory",
      "/api/revenue-intelligence/fusion",
      "/api/revenue-intelligence/geospatial",
      "/api/revenue-intelligence/state-registry",
    ],
    governanceRequirements: [
      ...portableSurfaceGovernanceRequirements,
      "revenue source intelligence governance",
      "source lineage and replay preservation",
      "claims validation",
    ],
    productionBlocks: [
      ...portableSurfaceProductionBlocks,
      "no guaranteed revenue claims",
      "no program approval claims",
      "no sponsor commitment",
      "no live source refresh",
    ],
    adjacentRoutes: ["/sponsor/dashboard", "/sponsor/project-discovery"],
  },
];

export const allPortableVerticalSurfaces: PortableVerticalSurface[] = [
  ...internalPortableSurfaces,
  ...borrowerPortalSurfaces,
  ...lenderPortalSurfaces,
  ...sponsorPortalSurfaces,
];

export function portableSurfacesByAudience(
  audience: PortableSurfaceAudience
): PortableVerticalSurface[] {
  return allPortableVerticalSurfaces.filter(
    (surface) => surface.audience === audience
  );
}

export function portableSurfaceById(
  id: string
): PortableVerticalSurface | null {
  return allPortableVerticalSurfaces.find((surface) => surface.id === id) ?? null;
}
