"use client";
import { useEffect, useState } from "react";

type Finding = { category: string; severity: string; summary: string; route?: string };
export default function NamedTesterAcceptancePage() {
  const [data, setData] = useState<any>(null); const [verdict, setVerdict] = useState("PASS"); const [summary, setSummary] = useState(""); const [category, setCategory] = useState("USABILITY"); const [severity, setSeverity] = useState("LOW"); const [findings, setFindings] = useState<Finding[]>([]); const [message, setMessage] = useState("");
  const load = () => fetch("/api/governance/named-tester-acceptance").then((r) => r.json()).then(setData);
  useEffect(() => { load(); }, []);
  function addFinding() { if (!summary.trim()) return; setFindings([...findings, { category, severity, summary: summary.trim() }]); setSummary(""); }
  async function submit() { setMessage(""); const res = await fetch("/api/governance/named-tester-acceptance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ verdict, findings }) }); const json = await res.json(); setMessage(json.ok ? "Your personal attestation was recorded." : json.error); if (json.ok) setData(json); }
  if (!data) return <main className="mx-auto max-w-4xl p-8"><h1 className="text-3xl font-semibold">P6 named-tester acceptance</h1><p>Loading…</p></main>;
  if (!data.ok) return <main className="mx-auto max-w-4xl p-8"><h1 className="text-3xl font-semibold">P6 named-tester acceptance</h1><p>{data.error}</p></main>;
  const r = data.rollup;
  return <main className="mx-auto max-w-4xl space-y-6 p-8"><div><h1 className="text-3xl font-semibold">P6 named-tester acceptance</h1><p>Signed in as {data.currentTester}. This submission applies only to you.</p></div><section className="rounded border p-4"><p><b>Revision:</b> {r.targetRevision}</p><p><b>Application:</b> {r.targetApplicationId}</p><p><b>P5-B01:</b> {r.p5Blocker.status}</p><p><b>Submitted:</b> {r.submittedTesters.join(", ") || "none"}</p></section><section className="space-y-3 rounded border p-4"><label className="block">Verdict <select className="ml-2 border p-2" value={verdict} onChange={(e) => setVerdict(e.target.value)}><option>PASS</option><option>PASS_WITH_FINDINGS</option><option>FAIL</option></select></label><div className="flex flex-wrap gap-2"><select className="border p-2" value={category} onChange={(e) => setCategory(e.target.value)}><option>USABILITY</option><option>GOVERNANCE</option><option>DATA</option><option>SECURITY</option></select><select className="border p-2" value={severity} onChange={(e) => setSeverity(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>BLOCKER</option></select><input className="min-w-80 flex-1 border p-2" value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Finding summary"/><button className="border px-4" onClick={addFinding}>Add finding</button></div>{findings.map((f, i) => <p key={i}>{f.severity} {f.category}: {f.summary}</p>)}<button className="rounded bg-black px-4 py-2 text-white" onClick={submit}>Submit my attestation</button>{message && <p>{message}</p>}</section><section className="rounded border p-4"><h2 className="text-xl font-semibold">Review path</h2><p>/operator-demo → /applications → /documents → /operator-queue → /reviews → /rules → /connectors → /partners → /reports → /audit-replay</p><p>Public and Interactive Compass surfaces must not expose the seeded application.</p></section></main>;
}
