"use client";
import { useEffect, useState } from "react";
export default function LaunchAuthorizationPage() {
  const [data,setData]=useState<any>(null); const [slot,setSlot]=useState(""); const [decision,setDecision]=useState("APPROVE"); const [evidenceRef,setEvidenceRef]=useState(""); const [condition,setCondition]=useState(""); const [message,setMessage]=useState("");
  const load=()=>fetch("/api/governance/launch-authorization-decisions").then(r=>r.json()).then(setData); useEffect(()=>{load()},[]);
  async function submit(){ const [blockerId,authorityRole]=slot.split("|"); const res=await fetch("/api/governance/launch-authorization-decisions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({blockerId,authorityRole,decision,evidenceRef,conditions:condition.trim()?[condition.trim()]:[]})}); const json=await res.json(); setMessage(json.ok?"Your authority decision was recorded.":json.error); if(json.ok)setData(json); }
  if(!data)return <main className="mx-auto max-w-5xl p-8">Loading…</main>; if(!data.ok)return <main className="mx-auto max-w-5xl p-8">{data.error}</main>;
  const r=data.rollup; return <main className="mx-auto max-w-5xl space-y-6 p-8"><div><h1 className="text-3xl font-semibold">Launch authorization decisions</h1><p>Signed in as {data.actor}. Submit only decisions within your assigned authority. Proxy approval is forbidden.</p></div><section className="rounded border p-4"><p><b>Completed:</b> {r.completed}/{r.required}</p><p><b>Approvals complete:</b> {String(r.approvalsComplete)}</p><p><b>Final launch hold released:</b> false</p><p><b>Production authorized:</b> false</p></section><section className="space-y-3 rounded border p-4"><select className="w-full border p-2" value={slot} onChange={e=>setSlot(e.target.value)}><option value="">Select authority slot</option>{r.slots.map((s:any)=><option key={`${s.blockerId}|${s.authorityRole}`} value={`${s.blockerId}|${s.authorityRole}`}>{s.blockerId} — {s.authorityRole} — {s.decision?.decision??"PENDING"}</option>)}</select><select className="border p-2" value={decision} onChange={e=>setDecision(e.target.value)}><option>APPROVE</option><option>APPROVE_WITH_CONDITIONS</option><option>REJECT</option></select><input className="w-full border p-2" value={evidenceRef} onChange={e=>setEvidenceRef(e.target.value)} placeholder="Evidence reference"/><input className="w-full border p-2" value={condition} onChange={e=>setCondition(e.target.value)} placeholder="Condition, required for conditional approval"/><button className="rounded bg-black px-4 py-2 text-white" disabled={!slot} onClick={submit}>Record my decision</button>{message&&<p>{message}</p>}</section><section className="rounded border p-4"><h2 className="text-xl font-semibold">Decision matrix</h2>{r.slots.map((s:any)=><p key={`${s.blockerId}-${s.authorityRole}`}>{s.blockerId} · {s.authorityRole}: <b>{s.decision?.decision??"PENDING"}</b></p>)}</section></main>;
}
