import type { InstitutionalLifecycleCycleEvaluation } from "@/lib/platform/institutionalLifecycleCycleAuthority";

export const INSTITUTIONAL_LIFECYCLE_CYCLE_REOPENING_SCHEMA_VERSION = "institutional-lifecycle-cycle-reopening-v1";
export type InstitutionalLifecycleCycleReopeningBasis = "NEW_EVIDENCE" | "FRAUD_INDICATOR" | "LEGAL_MANDATE" | "RETENTION_EXCEPTION" | "ARCHIVE_INTEGRITY_FAILURE";
export type InstitutionalLifecycleCycleReopeningDecision = "ALLOW" | "BLOCK" | "REVIEW_REQUIRED";
export type InstitutionalLifecycleCycleReopeningState = "REOPENED_RESTRICTED" | "REOPENED_FULL" | "REVIEW_PENDING" | "ARCHIVED";
export type InstitutionalLifecycleCycleReopeningPolicy = Readonly<{policyId:string;governanceVersion:string;allowedBases:readonly InstitutionalLifecycleCycleReopeningBasis[];requireIndependentReview:boolean;requireMaterialityEvidence:boolean;requireLegalReview:boolean;requireFraudEscalation:boolean;fullReopeningAuthorized:boolean;requiredEvidenceRefs:readonly string[];auditRefs:readonly string[];replayRef:string;versionRefs:readonly string[]}>;
export type InstitutionalLifecycleCycleReopeningEvaluation = Readonly<{schemaVersion:typeof INSTITUTIONAL_LIFECYCLE_CYCLE_REOPENING_SCHEMA_VERSION;cyclePolicyId:string;cycleId:string;generation:number;sourceProjectionPolicyId:string;reopeningPolicyId:string;canonicalObjectId:string;basis:InstitutionalLifecycleCycleReopeningBasis;decision:InstitutionalLifecycleCycleReopeningDecision;resultingState:InstitutionalLifecycleCycleReopeningState;reasons:readonly string[];reviewRefs:readonly string[];evidenceRefs:readonly string[];evaluatedAt:string;auditRefs:readonly string[];replayRef:string}>;
const ISO=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
function ne(v:string,f:string){const n=v.trim();if(!n)throw new Error(`${f} must be non-empty.`);return n;}
function iso(v:string,f:string){if(!ISO.test(ne(v,f)))throw new Error(`${f} must be an explicit UTC ISO-8601 timestamp.`);return v;}
function list<T extends string>(v:readonly T[],f:string,r=false):readonly T[]{const n=v.map(x=>ne(x,f) as T);if(r&&!n.length)throw new Error(`${f} must contain at least one value.`);if(new Set(n).size!==n.length)throw new Error(`${f} must not contain duplicates.`);return Object.freeze([...n].sort()) as readonly T[];}
export function createInstitutionalLifecycleCycleReopeningPolicy(input:InstitutionalLifecycleCycleReopeningPolicy){return Object.freeze({...input,policyId:ne(input.policyId,"policyId"),governanceVersion:ne(input.governanceVersion,"governanceVersion"),allowedBases:list(input.allowedBases,"allowedBases",true),requiredEvidenceRefs:list(input.requiredEvidenceRefs,"requiredEvidenceRefs"),auditRefs:list(input.auditRefs,"auditRefs",true),replayRef:ne(input.replayRef,"replayRef"),versionRefs:list(input.versionRefs,"versionRefs",true)});}
export function evaluateInstitutionalLifecycleCycleReopening(input:{cycle:InstitutionalLifecycleCycleEvaluation;policy:InstitutionalLifecycleCycleReopeningPolicy;basis:InstitutionalLifecycleCycleReopeningBasis;fullReopeningRequested:boolean;independentReviewRefs?:readonly string[];materialityEvidenceRef?:string|null;legalReviewRef?:string|null;fraudEscalationRef?:string|null;evidenceRefs:readonly string[];evaluatedAt:string;auditRefs:readonly string[];replayRef:string;}):InstitutionalLifecycleCycleReopeningEvaluation{
  iso(input.evaluatedAt,"evaluatedAt");const p=createInstitutionalLifecycleCycleReopeningPolicy(input.policy);const reviews=list(input.independentReviewRefs??[],"independentReviewRefs");const evidence=list(input.evidenceRefs,"evidenceRefs");const reasons:string[]=[];
  if(input.cycle.decision!=="ALLOW"||input.cycle.resultingState!=="OPEN")reasons.push("allowed-open-cycle-required");if(input.cycle.replayRef!==input.replayRef)reasons.push("cycle-replay-continuity-required");if(!p.allowedBases.includes(input.basis))reasons.push("reopening-basis-not-authorized");if(p.requireIndependentReview&&!reviews.length)reasons.push("independent-review-required");if(p.requireMaterialityEvidence&&!input.materialityEvidenceRef?.trim())reasons.push("materiality-evidence-required");if((p.requireLegalReview||input.basis==="LEGAL_MANDATE")&&!input.legalReviewRef?.trim())reasons.push("legal-review-required");if((p.requireFraudEscalation||input.basis==="FRAUD_INDICATOR")&&!input.fraudEscalationRef?.trim())reasons.push("fraud-escalation-required");for(const r of p.requiredEvidenceRefs)if(!evidence.includes(r))reasons.push(`missing-evidence:${r}`);if(input.fullReopeningRequested&&!p.fullReopeningAuthorized)reasons.push("full-reopening-not-authorized");
  const reviewable=new Set(["independent-review-required","materiality-evidence-required","legal-review-required","fraud-escalation-required"]);const hard=reasons.some(r=>!reviewable.has(r));const decision:InstitutionalLifecycleCycleReopeningDecision=hard?"BLOCK":reasons.length?"REVIEW_REQUIRED":"ALLOW";const resultingState:InstitutionalLifecycleCycleReopeningState=decision==="REVIEW_REQUIRED"?"REVIEW_PENDING":decision!=="ALLOW"?"ARCHIVED":input.fullReopeningRequested?"REOPENED_FULL":"REOPENED_RESTRICTED";
  return Object.freeze({schemaVersion:INSTITUTIONAL_LIFECYCLE_CYCLE_REOPENING_SCHEMA_VERSION,cyclePolicyId:input.cycle.cyclePolicyId,cycleId:input.cycle.cycleId,generation:input.cycle.generation,sourceProjectionPolicyId:input.cycle.sourceProjectionPolicyId,reopeningPolicyId:p.policyId,canonicalObjectId:input.cycle.canonicalObjectId,basis:input.basis,decision,resultingState,reasons:Object.freeze([...new Set(reasons)].sort()),reviewRefs:reviews,evidenceRefs:evidence,evaluatedAt:input.evaluatedAt,auditRefs:list(input.auditRefs,"auditRefs",true),replayRef:ne(input.replayRef,"replayRef")});
}
export const institutionalLifecycleCycleReopeningAuthority=Object.freeze({createPolicy:createInstitutionalLifecycleCycleReopeningPolicy,evaluate:evaluateInstitutionalLifecycleCycleReopening});
